## InClass Activity 3 (Additional)

One thing we looked at in the lecture and in the preclass activity were some rather "basic" ideas about probability using cards. Here is a couple of very quick questions using dice (or die if you prefer) to make sure you understand this. 

Have a go and see how you get on. If you don't get the right answers, be sure to ask in the lab or post on the slack forum <a href = "https://rguppies.slack.com/" target = "_blank">rguppies.slack.com</a> under the channel **#level2_2018**. Finally, don't forget to add any useful information to your Portfolio before you leave it too long and forget.

### Back to Basics

Show your answer either as a fraction (e.g. 1/52) or to 3 decimal places (e.g. `r round(1/52,3)`).  

* What is the probability of rolling a 4 on a single roll of a six-sided dice? `r fitb(c("1/6", "0.167", ".167"), width = 10, ignore_ws = TRUE)`

* What is the probability of rolling a 4, 5 **or** 6 on a single roll? `r fitb(c("3/6", "1/2", "0.5", ".5"), width = 10, ignore_ws = TRUE)`

* What is the probability of rolling a 4 **and then** a 6 straight after? `r fitb(c("1/6*1/6", "(1/6)*(1/6)", "0.028", ".028"), width = 10, ignore_ws = TRUE)`

`r hide("Explain this - I dont get these answers")`
```{block, type ="info"}
Remember: 

* probability is the number of times or ways an event can occur divided by the total number of all possible outcomes. 

* When you have two separate events the probability of them both happening is the joint probability which is calculated by mutliplying all the individual probabilities together.

1. .167 as you have 1 outcome over 6 possibilities

2. .5 as you have 3 outcomes over 6 possibilities

3. .028 as you have 1 out of 6 on both occasions so the joint probability is used.
```
`r unhide()`
<br>
<span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span>

Well done on completing this activty! Once you have completed the main body inclass assignment on the Normal Distribution, you should be ready to complete the assignment for this lab. Good luck and remember to refer back to the codes and questions in this lab and the preclass if you get stuck!.