## PreClass Activity

A bit of a change of pace in this PreClass Activity. In order to give you a bit more of an understanding of the between-subjects t-test, and a viable alternative to the standard Student's t-test, we ask that you read the following blog (and even the full paper if you have time) and then try out the couple of tasks below.

### Reading

Read the following blog on using Welch's t-test. 

**Blog:**

* <a href = "https://daniellakens.blogspot.co.uk/2015/01/always-use-welchs-t-test-instead-of.html" target = "_blank">Always use Welch's t-test instead of Student's t-test</a> by Daniel Lakens.

For further reading you can look at the paper that resulted from this blog:

**Paper:**

* Delacre, M., Lakens, D., & Leys, C. (in press) <a href = "https://osf.io/sbp6k/" target = "_blank">Why Psychologists Should by Default Use Welch's t-test Instead of Student's t-test</a>. International Review of Social Psychology.

### Task

1. Copy the script within the blog into an R script and try running it to see the difference between Welch's t-test (the recommended in the blog) and Student's t-test (the standard in the field). **Note:** You will need the **`car`** package. This is installed already in the Boyd Orr labs so if doing this in the labs, do not install the package, just call it to the library with library(car).

Don't worry if you don't yet understand all the code. It is highly commented but it is tricky.  The key thing is to try and run it and to look at the figures that come out of it - particularly the third one that you see in the blog, the one with the red line on it that compares p-values in the two tests. Look at how many tests (dots) are significant on one test and not the other.

2. Change the values for n1, n2, sd1 and sd2 at the top of the script to see what effect this has on the Type 1 Error rate (alpha = .05). Again look at the figure with the red line, comparing significance on one test versus significance on the other.  This is what should change depending on the n of each sample and whether the variance is equal or not.

3. Think about the overall point of this blog and which test we should use when conducting a t-test. We will look at this more in the lectures and labs.

<span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span>

That's it for today! This is a bit of a change to the PreClass activities you have done so far, and you will start to see this approach more in Semester 2 - reading blogs and chapters.  Don't forget though that it is really important to store the information in your own words, to help you really understand it, so you might want to go back and add any informative points to your Portfolio. Post any questions on the Moodle forum or the slack forum <a href = "https://rguppies.slack.com/" target = "_blank">rguppies.slack.com</a> under the channel **#level2_2018**. See you in the lab!
