# Correlations

## Overview

As you will read in <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" target = "_blank">Miller and Haden (2013)</a> as part of the preclass reading, correlations are **used to detect and quantify relationships among numerical variables**. In short, you measure two variables and the correlation analysis tells you whether or not they are related in some manner - positively or negatively; one increases as the other increases; one decreases as the other increases; etc. But unfortunately, by now, you may have heard people say lots of negative things about correlations:

* they do not prove causality
* they suffer from the bidirectional problem (A vs B is the same as B vs A)
* any relationship found may be the result of an unknown third variable (e.g. murders and ice-creams)

But whilst these are true, correlations are an incredibly useful and commonly used measure in the field, so don't be put off from using them or designing a study that uses correlations. In fact, they can be used in a variety of areas including: 

* looking at reading ability and IQ scores such as in Miller and Haden Chapter 11, which we will look at today; 
* exploring personality traits in voices (see <a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0185651" target = "_blank">Phil McAleer's work on Voices</a>)
* or traits in faces (see <a href="http://facelab.org/" target = "_blank">Lisa DeBruine's and Ben Jones's work</a>);
* brain-imaging analysis looking at activation in say the Amygdala in relation to emotion of faces (see <a href="https://psych.princeton.edu/person/alexander-todorov" target = "_blank">Alex Todorov's work at Princeton</a>);
* social attidues, both implicity and explicit, as Helena Paterson will discuss in her Social lectures this semester;
* or a whole variety of fields where you simply measure the variables of interest.

To actually carry out a correlation is very simple and we will show you that today in a little while: you just need the `cor.test()` function.  The harder part of correlations is really wrangling the data (which you learned in Semester 1) and interpreting the data (which we will focus more on today). So we are going to run a few correlations today, showing you how to do one, and asking you to peform others to give you some good practice at running and interpreting the relationships between two variables. 

**Note:** When dealing with correlations you should always refer to relationships and not predictions. In a correlation, X does not predict Y, that is regression which we will look at later this semester. In a correlation, all we can say is whether X and Y are related. So try to get the correct terminology and please feel free to pull us up if we say the wrong thing in class. It is an easy slip of the tongue to make!

In this lab we will:
* Introduce the Miller and Haden book we will be using throughout the rest of the semester
* Show you the thought process of a researcher running a correlational analysis
* Give you practice in running and writing up a correlation.