## PreClass Activity

As per the previous Chapter, the PreClass activity for this lab is reading (re-reading in fact) and trying out some of the activities in the book. We will go over similar activities in the lab so it will really help you to spend a few minutes trying out the activities in the book and thinking about them.

### Read

**Chapters**

* Re-read Chapter 3 of <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" target = "_blank">Miller and Haden (2013)</a> and make sure you are understanding it. Particularly focus on how the decomposition matrix leads to the ANOVA output through sums of squares, dfs, and mean squares. 

### Try

**Activities**

* Test your understanding by working through Computational Exercise #1 in section 3.12 of Miller and Haden (page 31) all the way to the summary table. The answer is in section 3.13 but be sure to work through the example first. 
* It may also help to review the probability labs and lectures from Semester 1 as we move onto understanding F distributions and p-values.

<span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span>
