# Continuing the GLM: One-factor ANOVA

## Overview

In the previous lab you learned how to decompose a dependent variable into components of a linear model, expressing them in terms of a decomposition matrix, before finishing up with calculating the sums of squares. In this lab, we will take it a step further and start exploring the relationships between sums of squares (SS), mean squares (MS), degrees of freedom (df), and F-ratios.  In short, in the first part of this class activity, we will show you how you go from the decomposition matrix to actually determining if there is a significant difference or not.  

We've had you work through the calculations step-by-step by hand and in R in order to gain a conceptual understanding. However, when you run an ANOVA, typically the computer does all of these calculations for you. As such, in the second part of the activities, we'll show you how to run a one-factor ANOVA using the `ezANOVA()` function in the **`ez`** add-on package. From there you will see how the output of this function maps onto the concepts you've been learning about. 

As such, the goals of this chapter are to:

* to demonstrate how Sums of Squares leads to an F-value, finishing off the decomposition matrix
* to determine the probability of a F-value for given degrees of freedom (df)
* to explore using the `ezANOVA()` function and how the outcome compares to your decomposition matrix calculations.

**Note:** The package `ez` is already installed on the Boyd Orr machines and only needs read into the library in the normal fashion. Do not install it on the Boyd Orr Lab machines. If you are using your own laptop you will need to make sure you have installed the `ez` package.
