<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lab 13 Continuing the GLM: Two-factor designs | ug2-practical</title>
  <meta name="description" content="Lab 13 Continuing the GLM: Two-factor designs | ug2-practical-materials" />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Lab 13 Continuing the GLM: Two-factor designs | ug2-practical" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Lab 13 Continuing the GLM: Two-factor designs | ug2-practical-materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lab 13 Continuing the GLM: Two-factor designs | ug2-practical" />
  
  <meta name="twitter:description" content="Lab 13 Continuing the GLM: Two-factor designs | ug2-practical-materials" />
  

<meta name="author" content="psyTeachR" />


<meta name="date" content="2019-06-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="continuing-the-glm-one-factor-anova.html">
<link rel="next" href="regression.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include\psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ug2-practical</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html"><i class="fa fa-check"></i><b>1</b> Starting with R Markdown</a><ul>
<li class="chapter" data-level="1.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a><ul>
<li class="chapter" data-level="1.1.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#what-is-r-markdown"><i class="fa fa-check"></i><b>1.1.1</b> What is R Markdown?</a></li>
<li class="chapter" data-level="1.1.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#advantages-of-using-r-markdown"><i class="fa fa-check"></i><b>1.1.2</b> Advantages of using R Markdown</a></li>
<li class="chapter" data-level="1.1.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#creating-an-r-markdown-.rmd-file"><i class="fa fa-check"></i><b>1.1.3</b> Creating an R Markdown (.Rmd) File</a></li>
<li class="chapter" data-level="1.1.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#one-last-thing-before-beginning"><i class="fa fa-check"></i><b>1.1.4</b> One last thing before beginning!</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#preclass-activiy"><i class="fa fa-check"></i><b>1.2</b> PreClass Activiy</a><ul>
<li class="chapter" data-level="1.2.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#lets-begin"><i class="fa fa-check"></i><b>1.2.1</b> Let’s Begin</a></li>
<li class="chapter" data-level="1.2.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#code-chunks"><i class="fa fa-check"></i><b>1.2.2</b> Code Chunks</a></li>
<li class="chapter" data-level="1.2.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#knitting-code"><i class="fa fa-check"></i><b>1.2.3</b> Knitting Code</a></li>
<li class="chapter" data-level="1.2.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#adding-rules-to-code-chunks"><i class="fa fa-check"></i><b>1.2.4</b> Adding Rules to Code Chunks</a></li>
<li class="chapter" data-level="1.2.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#adding-inline-code"><i class="fa fa-check"></i><b>1.2.5</b> Adding Inline Code</a></li>
<li class="chapter" data-level="1.2.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#formatting-the-r-markdown-file"><i class="fa fa-check"></i><b>1.2.6</b> Formatting the R Markdown File</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-activiy"><i class="fa fa-check"></i><b>1.3</b> InClass Activiy</a><ul>
<li class="chapter" data-level="1.3.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#r-markdown-and-the-experimental-design-portfolio"><i class="fa fa-check"></i><b>1.3.1</b> R Markdown and The Experimental Design Portfolio</a></li>
<li class="chapter" data-level="1.3.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#the-ponzo-illusion-and-age"><i class="fa fa-check"></i><b>1.3.2</b> The Ponzo Illusion and Age</a></li>
<li class="chapter" data-level="1.3.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT1"><i class="fa fa-check"></i><b>1.3.3</b> Task 1: Setting up Your R Markdown Portfolio</a></li>
<li class="chapter" data-level="1.3.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT2"><i class="fa fa-check"></i><b>1.3.4</b> Task 2: Give your Report a Heading</a></li>
<li class="chapter" data-level="1.3.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT3"><i class="fa fa-check"></i><b>1.3.5</b> Task 3: Creating a Code Chunk</a></li>
<li class="chapter" data-level="1.3.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT4"><i class="fa fa-check"></i><b>1.3.6</b> Task 4: Writing your Report</a></li>
<li class="chapter" data-level="1.3.7" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT5"><i class="fa fa-check"></i><b>1.3.7</b> Task 5: Making Text Bold or Italicized</a></li>
<li class="chapter" data-level="1.3.8" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT6"><i class="fa fa-check"></i><b>1.3.8</b> Task 6: Adding Links to the Data in your Methods</a></li>
<li class="chapter" data-level="1.3.9" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT7"><i class="fa fa-check"></i><b>1.3.9</b> Task 7: Adding an Image to your Methods</a></li>
<li class="chapter" data-level="1.3.10" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT8"><i class="fa fa-check"></i><b>1.3.10</b> Task 8: Adding a Table to your Results</a></li>
<li class="chapter" data-level="1.3.11" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT9"><i class="fa fa-check"></i><b>1.3.11</b> Task 9: Adding a Figure to your Results</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#assignment"><i class="fa fa-check"></i><b>1.4</b> Assignment</a></li>
<li class="chapter" data-level="1.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#solutions-to-questions"><i class="fa fa-check"></i><b>1.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="1.5.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-activities"><i class="fa fa-check"></i><b>1.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html"><i class="fa fa-check"></i><b>2</b> Data-Wrangling: A Key Skill</a><ul>
<li class="chapter" data-level="2.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#overview-1"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#preclass-activity"><i class="fa fa-check"></i><b>2.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#revisiting-the-wickham-six"><i class="fa fa-check"></i><b>2.2.1</b> Revisiting the Wickham Six</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#learning-to-wrangle-is-there-a-chastity-belt-on-perception"><i class="fa fa-check"></i><b>2.2.2</b> Learning to Wrangle: Is there a Chastity Belt on Perception</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT1"><i class="fa fa-check"></i><b>2.2.3</b> The <strong><code>select()</code></strong> Function - to keep only specific columns</a></li>
<li class="chapter" data-level="2.2.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT2"><i class="fa fa-check"></i><b>2.2.4</b> The <strong><code>arrange()</code></strong> Function - to sort and arrange columns</a></li>
<li class="chapter" data-level="2.2.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT3"><i class="fa fa-check"></i><b>2.2.5</b> The <strong><code>filter()</code></strong> Function - to keep only parts of the data</a></li>
<li class="chapter" data-level="2.2.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT4"><i class="fa fa-check"></i><b>2.2.6</b> The <strong><code>mutate()</code></strong> Function - for adding new columns</a></li>
<li class="chapter" data-level="2.2.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT5"><i class="fa fa-check"></i><b>2.2.7</b> The <strong><code>group_by()</code></strong> Function - to group parts of data altogether</a></li>
<li class="chapter" data-level="2.2.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT6"><i class="fa fa-check"></i><b>2.2.8</b> The <strong><code>summarise()</code></strong> Function - to do some calculations on the data</a></li>
<li class="chapter" data-level="2.2.9" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#two-other-useful-functions"><i class="fa fa-check"></i><b>2.2.9</b> Two Other Useful Functions</a></li>
<li class="chapter" data-level="2.2.10" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#last-but-not-least---pipes-to-make-your-code-efficient"><i class="fa fa-check"></i><b>2.2.10</b> Last but not least - Pipes (<strong><code>%&gt;%</code></strong>) to make your code efficient</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#inclass-activity"><i class="fa fa-check"></i><b>2.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#task-1-open-a-script"><i class="fa fa-check"></i><b>2.3.1</b> Task 1: Open a Script</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT2"><i class="fa fa-check"></i><b>2.3.2</b> Task 2: Bring in Your Library</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT3"><i class="fa fa-check"></i><b>2.3.3</b> Task 3: Load in the Data</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT4"><i class="fa fa-check"></i><b>2.3.4</b> Task 4: Review Your Data.</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT5"><i class="fa fa-check"></i><b>2.3.5</b> Task 5: Gathering Data.</a></li>
<li class="chapter" data-level="2.3.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT6"><i class="fa fa-check"></i><b>2.3.6</b> Task 6: Combining Data.</a></li>
<li class="chapter" data-level="2.3.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT7"><i class="fa fa-check"></i><b>2.3.7</b> Task 7: Calculating the AQ Scores.</a></li>
<li class="chapter" data-level="2.3.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT8"><i class="fa fa-check"></i><b>2.3.8</b> Task 8: One Last Thing on Pipes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#assignment-1"><i class="fa fa-check"></i><b>2.4</b> Assignment</a><ul>
<li class="chapter" data-level="2.4.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#todays-topic---the-ageing-brain"><i class="fa fa-check"></i><b>2.4.1</b> Today’s Topic - The Ageing Brain</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#load-in-the-data"><i class="fa fa-check"></i><b>2.4.2</b> Load in the data</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT1"><i class="fa fa-check"></i><b>2.4.3</b> Task 1 - Oldest Participant</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT2"><i class="fa fa-check"></i><b>2.4.4</b> Task 2 - Arranging D-SPAN</a></li>
<li class="chapter" data-level="2.4.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT3"><i class="fa fa-check"></i><b>2.4.5</b> Task 3 - Foreign Language Speakers</a></li>
<li class="chapter" data-level="2.4.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT4"><i class="fa fa-check"></i><b>2.4.6</b> Task 4 - Creating Percentage MOCA scores</a></li>
<li class="chapter" data-level="2.4.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT5"><i class="fa fa-check"></i><b>2.4.7</b> Task 5 - Remove the MOCA column</a></li>
<li class="chapter" data-level="2.4.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT6"><i class="fa fa-check"></i><b>2.4.8</b> Task 6 - Gather the Responses together</a></li>
<li class="chapter" data-level="2.4.9" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT7"><i class="fa fa-check"></i><b>2.4.9</b> Task 7 - Joining the data</a></li>
<li class="chapter" data-level="2.4.10" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT8"><i class="fa fa-check"></i><b>2.4.10</b> Task 8 - Working the Pipes</a></li>
<li class="chapter" data-level="2.4.11" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT9"><i class="fa fa-check"></i><b>2.4.11</b> Task 9 - Difference in Musical Means</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#solutions-to-questions-1"><i class="fa fa-check"></i><b>2.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="2.5.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#preclass-activities"><i class="fa fa-check"></i><b>2.5.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="2.5.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#inclass-actitivies"><i class="fa fa-check"></i><b>2.5.2</b> InClass Actitivies</a></li>
<li class="chapter" data-level="2.5.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#assignment-solution"><i class="fa fa-check"></i><b>2.5.3</b> Assignment Solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html"><i class="fa fa-check"></i><b>3</b> Visualisation Through <strong><code>ggplot2</code></strong></a><ul>
<li class="chapter" data-level="3.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#overview-2"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#preclass-activity-1"><i class="fa fa-check"></i><b>3.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="3.2.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#scatterplots---geom_point"><i class="fa fa-check"></i><b>3.2.1</b> Scatterplots - <code>geom_point()</code></a></li>
<li class="chapter" data-level="3.2.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#histograms---geom_histogram"><i class="fa fa-check"></i><b>3.2.2</b> Histograms - geom_histogram()</a></li>
<li class="chapter" data-level="3.2.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#boxplots---geom_boxplot"><i class="fa fa-check"></i><b>3.2.3</b> Boxplots - geom_boxplot()</a></li>
<li class="chapter" data-level="3.2.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#barplots---geom_bar-or-geom_col"><i class="fa fa-check"></i><b>3.2.4</b> Barplots - geom_bar() or geom_col()</a></li>
<li class="chapter" data-level="3.2.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#themes-labels-guides-and-facet_wraps"><i class="fa fa-check"></i><b>3.2.5</b> Themes, Labels, Guides, and <strong><code>facet_wraps()</code></strong></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#inclass-activity-1"><i class="fa fa-check"></i><b>3.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="3.3.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#mental-rotation-angle-and-reaction-time"><i class="fa fa-check"></i><b>3.3.1</b> Mental Rotation: Angle and Reaction Time</a></li>
<li class="chapter" data-level="3.3.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT1"><i class="fa fa-check"></i><b>3.3.2</b> Task 1: Loading and Viewing the Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT2"><i class="fa fa-check"></i><b>3.3.3</b> Task 2: Recreating the Figure</a></li>
<li class="chapter" data-level="3.3.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT3"><i class="fa fa-check"></i><b>3.3.4</b> Task 3: Examining Additional Variable Effects</a></li>
<li class="chapter" data-level="3.3.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT4"><i class="fa fa-check"></i><b>3.3.5</b> Task 4: Grouping the Figure Data</a></li>
<li class="chapter" data-level="3.3.6" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT5"><i class="fa fa-check"></i><b>3.3.6</b> Task 5: Identifying Groups Using <strong><code>aes()</code></strong></a></li>
<li class="chapter" data-level="3.3.7" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT6"><i class="fa fa-check"></i><b>3.3.7</b> Task 6: Changing the Shape and Size of Data Points</a></li>
<li class="chapter" data-level="3.3.8" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT7"><i class="fa fa-check"></i><b>3.3.8</b> Task 7: Adding Labels and Changing the Background</a></li>
<li class="chapter" data-level="3.3.9" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT8"><i class="fa fa-check"></i><b>3.3.9</b> Task 8: Separating a Variable and Removing Legends</a></li>
<li class="chapter" data-level="3.3.10" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#additional-considerations-briefly"><i class="fa fa-check"></i><b>3.3.10</b> Additional Considerations (briefly!)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#assignment-2"><i class="fa fa-check"></i><b>3.4</b> Assignment</a></li>
<li class="chapter" data-level="3.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#solutions-to-questions-2"><i class="fa fa-check"></i><b>3.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="3.5.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#inclass-activities-1"><i class="fa fa-check"></i><b>3.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html"><i class="fa fa-check"></i><b>4</b> Revisiting Probability Distributions</a><ul>
<li class="chapter" data-level="4.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#overview-3"><i class="fa fa-check"></i><b>4.1</b> Overview</a><ul>
<li class="chapter" data-level="4.1.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#discrete-or-continuous-datasets"><i class="fa fa-check"></i><b>4.1.1</b> Discrete or Continuous Datasets</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#preclass-activity-1-1"><i class="fa fa-check"></i><b>4.2</b> PreClass Activity 1</a><ul>
<li class="chapter" data-level="4.2.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#general-probability-calculations"><i class="fa fa-check"></i><b>4.2.1</b> General Probability Calculations</a></li>
<li class="chapter" data-level="4.2.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#creating-a-simple-probability-distribution"><i class="fa fa-check"></i><b>4.2.2</b> Creating a Simple Probability Distribution</a></li>
<li class="chapter" data-level="4.2.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#the-binomial-distribution---creating-a-discrete-distribution"><i class="fa fa-check"></i><b>4.2.3</b> The Binomial Distribution - Creating a Discrete Distribution</a></li>
<li class="chapter" data-level="4.2.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#dbinom---the-density-function"><i class="fa fa-check"></i><b>4.2.4</b> <strong><code>dbinom</code></strong> - The Density Function</a></li>
<li class="chapter" data-level="4.2.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#pbinom---the-cumulative-probability-function"><i class="fa fa-check"></i><b>4.2.5</b> <strong><code>pbinom</code></strong> - The Cumulative Probability Function</a></li>
<li class="chapter" data-level="4.2.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#qbinom---the-quartile-function"><i class="fa fa-check"></i><b>4.2.6</b> <strong><code>qbinom</code></strong> - The Quartile Function</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#preclass-activity-2"><i class="fa fa-check"></i><b>4.3</b> PreClass Activity 2</a><ul>
<li class="chapter" data-level="4.3.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#continuous-data---brief-recap-on-the-normal-distribution"><i class="fa fa-check"></i><b>4.3.1</b> Continuous Data - Brief Recap on The Normal Distribution</a></li>
<li class="chapter" data-level="4.3.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#properties-of-the-normal-distribution"><i class="fa fa-check"></i><b>4.3.2</b> Properties of the Normal distribution:</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-1-1"><i class="fa fa-check"></i><b>4.4</b> InClass Activity 1</a><ul>
<li class="chapter" data-level="4.4.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#continuous-data-and-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Continuous Data and the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#estimating-from-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.2</b> Estimating from the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#dnorm---the-density-function-for-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.3</b> <strong><code>dnorm()</code></strong> - The Density Function for the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#pnorm---the-probability-or-distribution-function"><i class="fa fa-check"></i><b>4.4.4</b> <strong><code>pnorm()</code></strong> - The Probability or Distribution Function</a></li>
<li class="chapter" data-level="4.4.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#qnorm---the-quantile-function"><i class="fa fa-check"></i><b>4.4.5</b> <strong><code>qnorm()</code></strong> - The Quantile Function</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-2-additional"><i class="fa fa-check"></i><b>4.5</b> InClass Activity 2 (Additional)</a><ul>
<li class="chapter" data-level="4.5.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#return-of-the-binomial"><i class="fa fa-check"></i><b>4.5.1</b> Return of the Binomial</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-3-additional"><i class="fa fa-check"></i><b>4.6</b> InClass Activity 3 (Additional)</a><ul>
<li class="chapter" data-level="4.6.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#back-to-basics"><i class="fa fa-check"></i><b>4.6.1</b> Back to Basics</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#assignment-3"><i class="fa fa-check"></i><b>4.7</b> Assignment</a><ul>
<li class="chapter" data-level="4.7.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#todays-topic---probability"><i class="fa fa-check"></i><b>4.7.1</b> Today’s Topic - Probability</a></li>
<li class="chapter" data-level="4.7.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueLib"><i class="fa fa-check"></i><b>4.7.2</b> Load in the Library</a></li>
<li class="chapter" data-level="4.7.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT1"><i class="fa fa-check"></i><b>4.7.3</b> Assignment Task 1</a></li>
<li class="chapter" data-level="4.7.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT2"><i class="fa fa-check"></i><b>4.7.4</b> Assignment Task 2</a></li>
<li class="chapter" data-level="4.7.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT3"><i class="fa fa-check"></i><b>4.7.5</b> Assignment Task 3</a></li>
<li class="chapter" data-level="4.7.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT4"><i class="fa fa-check"></i><b>4.7.6</b> Assignment Task 4</a></li>
<li class="chapter" data-level="4.7.7" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT5"><i class="fa fa-check"></i><b>4.7.7</b> Assignment Task 5</a></li>
<li class="chapter" data-level="4.7.8" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT6"><i class="fa fa-check"></i><b>4.7.8</b> Assignment Task 6</a></li>
<li class="chapter" data-level="4.7.9" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT7"><i class="fa fa-check"></i><b>4.7.9</b> Assignment Task 7</a></li>
<li class="chapter" data-level="4.7.10" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT8"><i class="fa fa-check"></i><b>4.7.10</b> Assignment Task 8</a></li>
<li class="chapter" data-level="4.7.11" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT9"><i class="fa fa-check"></i><b>4.7.11</b> Assignment Task 9</a></li>
<li class="chapter" data-level="4.7.12" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT10"><i class="fa fa-check"></i><b>4.7.12</b> Assignment Task 10</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#solutions-to-questions-3"><i class="fa fa-check"></i><b>4.8</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="4.8.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activities-2"><i class="fa fa-check"></i><b>4.8.1</b> InClass Activities</a></li>
<li class="chapter" data-level="4.8.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#assignment-solution-1"><i class="fa fa-check"></i><b>4.8.2</b> Assignment Solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html"><i class="fa fa-check"></i><b>5</b> Permutation Tests - A Skill Set</a><ul>
<li class="chapter" data-level="5.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#overview-4"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#preclass-activity-3"><i class="fa fa-check"></i><b>5.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="5.2.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-1-generating-random-numbers"><i class="fa fa-check"></i><b>5.2.1</b> Skill 1: Generating Random Numbers</a></li>
<li class="chapter" data-level="5.2.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-2-permuting-values"><i class="fa fa-check"></i><b>5.2.2</b> Skill 2: Permuting Values</a></li>
<li class="chapter" data-level="5.2.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-3-creating-tibbles"><i class="fa fa-check"></i><b>5.2.3</b> Skill 3: Creating Tibbles</a></li>
<li class="chapter" data-level="5.2.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-4-computing-differences-in-group-means"><i class="fa fa-check"></i><b>5.2.4</b> Skill 4: Computing Differences in Group Means</a></li>
<li class="chapter" data-level="5.2.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-5-creating-your-own-functions"><i class="fa fa-check"></i><b>5.2.5</b> Skill 5: Creating Your Own Functions</a></li>
<li class="chapter" data-level="5.2.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-6-replicating-operations"><i class="fa fa-check"></i><b>5.2.6</b> Skill 6: Replicating Operations</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#inclass-activity-2"><i class="fa fa-check"></i><b>5.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="5.3.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#permutation-tests-of-hypotheses"><i class="fa fa-check"></i><b>5.3.1</b> Permutation Tests of Hypotheses</a></li>
<li class="chapter" data-level="5.3.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT1"><i class="fa fa-check"></i><b>5.3.2</b> Step 1: Load in Add-on Packages and Data</a></li>
<li class="chapter" data-level="5.3.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT2"><i class="fa fa-check"></i><b>5.3.3</b> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></a></li>
<li class="chapter" data-level="5.3.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT3"><i class="fa fa-check"></i><b>5.3.4</b> Step 3: Permute the Group Labels</a></li>
<li class="chapter" data-level="5.3.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT4"><i class="fa fa-check"></i><b>5.3.5</b> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</a></li>
<li class="chapter" data-level="5.3.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT5"><i class="fa fa-check"></i><b>5.3.6</b> Step 5: Compare the Observed Mean Difference to the NHD</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#assignment-4"><i class="fa fa-check"></i><b>5.4</b> Assignment</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#solutions-to-questions-4"><i class="fa fa-check"></i><b>5.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="5.5.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#inclass-activities-3"><i class="fa fa-check"></i><b>5.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html"><i class="fa fa-check"></i><b>6</b> NHST and One-Sample t-tests</a><ul>
<li class="chapter" data-level="6.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#overview-5"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activity-1-2"><i class="fa fa-check"></i><b>6.2</b> PreClass Activity 1</a><ul>
<li class="chapter" data-level="6.2.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#the-binomial-test"><i class="fa fa-check"></i><b>6.2.1</b> The Binomial Test</a></li>
<li class="chapter" data-level="6.2.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-1-creating-a-dataframe"><i class="fa fa-check"></i><b>6.2.2</b> Task 1: Creating a Dataframe</a></li>
<li class="chapter" data-level="6.2.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-2-comparing-original-and-new-sample-reaction-times"><i class="fa fa-check"></i><b>6.2.3</b> Task 2: Comparing Original and New Sample Reaction Times</a></li>
<li class="chapter" data-level="6.2.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-3-calculating-probability"><i class="fa fa-check"></i><b>6.2.4</b> Task 3: Calculating Probability</a></li>
<li class="chapter" data-level="6.2.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#the-one-sample-t-test"><i class="fa fa-check"></i><b>6.2.5</b> The One-Sample t-test</a></li>
<li class="chapter" data-level="6.2.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-4-calculating-the-mean-and-standard-deviation"><i class="fa fa-check"></i><b>6.2.6</b> Task 4: Calculating the Mean and Standard Deviation</a></li>
<li class="chapter" data-level="6.2.7" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-5-calculating-the-observed-test-statistic"><i class="fa fa-check"></i><b>6.2.7</b> Task 5: Calculating the Observed Test Statistic</a></li>
<li class="chapter" data-level="6.2.8" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-6-comparing-the-observed-test-statistic-to-the-t-distribution-using-pt"><i class="fa fa-check"></i><b>6.2.8</b> Task 6: Comparing the Observed Test Statistic to the t-distribution using <strong><code>pt()</code></strong></a></li>
<li class="chapter" data-level="6.2.9" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-7-comparing-the-observed-test-statistic-to-the-t-distribution-using-t.test"><i class="fa fa-check"></i><b>6.2.9</b> Task 7: Comparing the Observed Test Statistic to the t-distribution using <strong><code>t.test()</code></strong></a></li>
<li class="chapter" data-level="6.2.10" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-8-drawing-conclusions-about-the-new-data"><i class="fa fa-check"></i><b>6.2.10</b> Task 8: Drawing Conclusions about the new data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activity-2-additional"><i class="fa fa-check"></i><b>6.3</b> PreClass Activity 2 (Additional)</a><ul>
<li class="chapter" data-level="6.3.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#a-short-blog-on-barplots"><i class="fa fa-check"></i><b>6.3.1</b> A short blog on Barplots</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#inclass-activity-3"><i class="fa fa-check"></i><b>6.4</b> InClass Activity</a><ul>
<li class="chapter" data-level="6.4.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-1-evaluators"><i class="fa fa-check"></i><b>6.4.1</b> Task 1: Evaluators</a></li>
<li class="chapter" data-level="6.4.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-2-ratings"><i class="fa fa-check"></i><b>6.4.2</b> Task 2: Ratings</a></li>
<li class="chapter" data-level="6.4.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-3-creating-a-figure"><i class="fa fa-check"></i><b>6.4.3</b> Task 3: Creating a Figure</a></li>
<li class="chapter" data-level="6.4.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-4-t-tests"><i class="fa fa-check"></i><b>6.4.4</b> Task 4: t-tests</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#assignment-5"><i class="fa fa-check"></i><b>6.5</b> Assignment</a><ul>
<li class="chapter" data-level="6.5.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-1a-libraries"><i class="fa fa-check"></i><b>6.5.1</b> Task 1A: Libraries</a></li>
<li class="chapter" data-level="6.5.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-1b-loading-in-the-data"><i class="fa fa-check"></i><b>6.5.2</b> Task 1B: Loading in the data</a></li>
<li class="chapter" data-level="6.5.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-2-identify-relevant-columns"><i class="fa fa-check"></i><b>6.5.3</b> Task 2: Identify relevant columns</a></li>
<li class="chapter" data-level="6.5.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-3-verify-the-number-of-subjects-in-each-group"><i class="fa fa-check"></i><b>6.5.4</b> Task 3: Verify the number of subjects in each group</a></li>
<li class="chapter" data-level="6.5.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-4-reproduce-figure-2a"><i class="fa fa-check"></i><b>6.5.5</b> Task 4: Reproduce Figure 2a</a></li>
<li class="chapter" data-level="6.5.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-5-interpreting-your-figure"><i class="fa fa-check"></i><b>6.5.6</b> Task 5: Interpreting your Figure</a></li>
<li class="chapter" data-level="6.5.7" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-6-t-test"><i class="fa fa-check"></i><b>6.5.7</b> Task 6: t-test</a></li>
<li class="chapter" data-level="6.5.8" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#task-7-reporting-results"><i class="fa fa-check"></i><b>6.5.8</b> Task 7: Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#solutions-to-questions-5"><i class="fa fa-check"></i><b>6.6</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="6.6.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activities-1"><i class="fa fa-check"></i><b>6.6.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="6.6.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#inclass-activities-4"><i class="fa fa-check"></i><b>6.6.2</b> InClass Activities</a></li>
<li class="chapter" data-level="6.6.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#homework-activity"><i class="fa fa-check"></i><b>6.6.3</b> Homework Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html"><i class="fa fa-check"></i><b>7</b> Within-Subjects t-test</a><ul>
<li class="chapter" data-level="7.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#overview-6"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#preclass-activity-4"><i class="fa fa-check"></i><b>7.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="7.2.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#reading"><i class="fa fa-check"></i><b>7.2.1</b> Reading</a></li>
<li class="chapter" data-level="7.2.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task"><i class="fa fa-check"></i><b>7.2.2</b> Task</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#inclass-activity-4"><i class="fa fa-check"></i><b>7.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="7.3.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-1-load-the-data"><i class="fa fa-check"></i><b>7.3.1</b> Task 1: Load the Data</a></li>
<li class="chapter" data-level="7.3.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-2-wrangle-the-data"><i class="fa fa-check"></i><b>7.3.2</b> Task 2: Wrangle the Data</a></li>
<li class="chapter" data-level="7.3.3" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-3-look-at-the-histograms-for-normality"><i class="fa fa-check"></i><b>7.3.3</b> Task 3: Look at the Histograms for Normality</a></li>
<li class="chapter" data-level="7.3.4" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-4-a-boxplot-of-outliers"><i class="fa fa-check"></i><b>7.3.4</b> Task 4: A Boxplot of Outliers</a></li>
<li class="chapter" data-level="7.3.5" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-5-the-violin-plot"><i class="fa fa-check"></i><b>7.3.5</b> Task 5: The Violin Plot</a></li>
<li class="chapter" data-level="7.3.6" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-6-calculating-descriptives"><i class="fa fa-check"></i><b>7.3.6</b> Task 6: Calculating Descriptives</a></li>
<li class="chapter" data-level="7.3.7" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-7-visualising-means-and-descriptives"><i class="fa fa-check"></i><b>7.3.7</b> Task 7: Visualising Means and Descriptives</a></li>
<li class="chapter" data-level="7.3.8" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-8-the-t-test"><i class="fa fa-check"></i><b>7.3.8</b> Task 8: The t-test</a></li>
<li class="chapter" data-level="7.3.9" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task-9-the-write-up"><i class="fa fa-check"></i><b>7.3.9</b> Task 9: The Write-up</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#assignment-6"><i class="fa fa-check"></i><b>7.4</b> Assignment</a></li>
<li class="chapter" data-level="7.5" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#solutions-to-questions-6"><i class="fa fa-check"></i><b>7.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="7.5.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#inclass-activities-5"><i class="fa fa-check"></i><b>7.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html"><i class="fa fa-check"></i><b>8</b> APES - Alpha, Power, Effect Sizes, Sample Size</a><ul>
<li class="chapter" data-level="8.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#overview-7"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#preclass-activity-5"><i class="fa fa-check"></i><b>8.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="8.2.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#reading-1"><i class="fa fa-check"></i><b>8.2.1</b> Reading</a></li>
<li class="chapter" data-level="8.2.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#watch"><i class="fa fa-check"></i><b>8.2.2</b> Watch</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#inclass-activity-5"><i class="fa fa-check"></i><b>8.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="8.3.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#effect-sizes---cohens-d"><i class="fa fa-check"></i><b>8.3.1</b> Effect Sizes - Cohen’s D</a></li>
<li class="chapter" data-level="8.3.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-1-effect-size-from-a-one-sample-t-test"><i class="fa fa-check"></i><b>8.3.2</b> Task 1: Effect size from a one-sample t-test</a></li>
<li class="chapter" data-level="8.3.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-2-effect-size-from-between-subjects-t-test"><i class="fa fa-check"></i><b>8.3.3</b> Task 2: Effect size from between-subjects t-test</a></li>
<li class="chapter" data-level="8.3.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-3-effect-size-from-matched-pairs-t-test"><i class="fa fa-check"></i><b>8.3.4</b> Task 3: Effect Size from matched-pairs t-test</a></li>
<li class="chapter" data-level="8.3.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-4-t-value-and-effect-size-for-a-between-subjects-experiment"><i class="fa fa-check"></i><b>8.3.5</b> Task 4: t-value and effect size for a between-subjects Experiment</a></li>
<li class="chapter" data-level="8.3.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#power-calculations"><i class="fa fa-check"></i><b>8.3.6</b> Power Calculations</a></li>
<li class="chapter" data-level="8.3.7" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-5-sample-size-for-standard-power-one-sample-t-test"><i class="fa fa-check"></i><b>8.3.7</b> Task 5: Sample size for standard power one-sample t-test</a></li>
<li class="chapter" data-level="8.3.8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-6-effect-size-from-a-high-power-between-subjects-t-test"><i class="fa fa-check"></i><b>8.3.8</b> Task 6: Effect size from a high power between-subjects t-test</a></li>
<li class="chapter" data-level="8.3.9" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-7-power-of-published-research"><i class="fa fa-check"></i><b>8.3.9</b> Task 7: Power of Published Research</a></li>
<li class="chapter" data-level="8.3.10" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#group-discussion-point-4"><i class="fa fa-check"></i><b>8.3.10</b> <span style="color:DARKBLUE"> <strong>Group Discussion Point</strong> </span></a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#assignment-7"><i class="fa fa-check"></i><b>8.4</b> Assignment</a><ul>
<li class="chapter" data-level="8.4.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-1-3"><i class="fa fa-check"></i><b>8.4.1</b> Task 1</a></li>
<li class="chapter" data-level="8.4.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-2-3"><i class="fa fa-check"></i><b>8.4.2</b> Task 2</a></li>
<li class="chapter" data-level="8.4.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-3-2"><i class="fa fa-check"></i><b>8.4.3</b> Task 3</a></li>
<li class="chapter" data-level="8.4.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-4-3"><i class="fa fa-check"></i><b>8.4.4</b> Task 4</a></li>
<li class="chapter" data-level="8.4.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-5-2"><i class="fa fa-check"></i><b>8.4.5</b> Task 5</a></li>
<li class="chapter" data-level="8.4.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-6-2"><i class="fa fa-check"></i><b>8.4.6</b> Task 6</a></li>
<li class="chapter" data-level="8.4.7" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-7-2"><i class="fa fa-check"></i><b>8.4.7</b> Task 7</a></li>
<li class="chapter" data-level="8.4.8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-8-1"><i class="fa fa-check"></i><b>8.4.8</b> Task 8</a></li>
<li class="chapter" data-level="8.4.9" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-9-1"><i class="fa fa-check"></i><b>8.4.9</b> Task 9</a></li>
<li class="chapter" data-level="8.4.10" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-10"><i class="fa fa-check"></i><b>8.4.10</b> Task 10</a></li>
<li class="chapter" data-level="8.4.11" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#task-11"><i class="fa fa-check"></i><b>8.4.11</b> Task 11</a></li>
<li class="chapter" data-level="8.4.12" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#the-pwr-package"><i class="fa fa-check"></i><b>8.4.12</b> The <strong><code>pwr</code></strong> package</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#solutions-to-questions-7"><i class="fa fa-check"></i><b>8.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="8.5.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#inclass-activities-6"><i class="fa fa-check"></i><b>8.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="8.5.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#homework-activities"><i class="fa fa-check"></i><b>8.5.2</b> Homework Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html"><i class="fa fa-check"></i><b>9</b> Reflection - Semester 1</a><ul>
<li class="chapter" data-level="9.1" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#overview-8"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#preclass-activity-6"><i class="fa fa-check"></i><b>9.2</b> PreClass Activity</a></li>
<li class="chapter" data-level="9.3" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#inclass-activity-6"><i class="fa fa-check"></i><b>9.3</b> InClass Activity</a></li>
<li class="chapter" data-level="9.4" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#assignment-8"><i class="fa fa-check"></i><b>9.4</b> Assignment</a></li>
<li class="chapter" data-level="9.5" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#solutions-to-questions-8"><i class="fa fa-check"></i><b>9.5</b> Solutions to Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>10</b> Correlations</a><ul>
<li class="chapter" data-level="10.1" data-path="correlations.html"><a href="correlations.html#overview-9"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="correlations.html"><a href="correlations.html#preclass-activity-7"><i class="fa fa-check"></i><b>10.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="10.2.1" data-path="correlations.html"><a href="correlations.html#read"><i class="fa fa-check"></i><b>10.2.1</b> Read</a></li>
<li class="chapter" data-level="10.2.2" data-path="correlations.html"><a href="correlations.html#watch-1"><i class="fa fa-check"></i><b>10.2.2</b> Watch</a></li>
<li class="chapter" data-level="10.2.3" data-path="correlations.html"><a href="correlations.html#play"><i class="fa fa-check"></i><b>10.2.3</b> Play</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="correlations.html"><a href="correlations.html#inclass-activity-7"><i class="fa fa-check"></i><b>10.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="10.3.1" data-path="correlations.html"><a href="correlations.html#assumption-1-level-of-measurement"><i class="fa fa-check"></i><b>10.3.1</b> Assumption 1: Level of Measurement</a></li>
<li class="chapter" data-level="10.3.2" data-path="correlations.html"><a href="correlations.html#assumption-2-pairs-of-data"><i class="fa fa-check"></i><b>10.3.2</b> Assumption 2: Pairs of Data</a></li>
<li class="chapter" data-level="10.3.3" data-path="correlations.html"><a href="correlations.html#assumption-3-the-shape-of-my-data"><i class="fa fa-check"></i><b>10.3.3</b> Assumption 3: The shape of my data</a></li>
<li class="chapter" data-level="10.3.4" data-path="correlations.html"><a href="correlations.html#descriptives-of-a-correlation"><i class="fa fa-check"></i><b>10.3.4</b> Descriptives of a correlation</a></li>
<li class="chapter" data-level="10.3.5" data-path="correlations.html"><a href="correlations.html#the-correlation-itself"><i class="fa fa-check"></i><b>10.3.5</b> The Correlation itself</a></li>
<li class="chapter" data-level="10.3.6" data-path="correlations.html"><a href="correlations.html#interpreting-the-correlation"><i class="fa fa-check"></i><b>10.3.6</b> Interpreting the Correlation</a></li>
<li class="chapter" data-level="10.3.7" data-path="correlations.html"><a href="correlations.html#in-summary"><i class="fa fa-check"></i><b>10.3.7</b> In summary</a></li>
<li class="chapter" data-level="10.3.8" data-path="correlations.html"><a href="correlations.html#advanced-1-matrix-of-scatterplots"><i class="fa fa-check"></i><b>10.3.8</b> Advanced 1: Matrix of Scatterplots</a></li>
<li class="chapter" data-level="10.3.9" data-path="correlations.html"><a href="correlations.html#advanced-2-attitudes-towards-vaping"><i class="fa fa-check"></i><b>10.3.9</b> Advanced 2: Attitudes towards Vaping</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="correlations.html"><a href="correlations.html#assignment-9"><i class="fa fa-check"></i><b>10.4</b> Assignment</a></li>
<li class="chapter" data-level="10.5" data-path="correlations.html"><a href="correlations.html#solutions-to-questions-9"><i class="fa fa-check"></i><b>10.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="10.5.1" data-path="correlations.html"><a href="correlations.html#inclass-activity-8"><i class="fa fa-check"></i><b>10.5.1</b> InClass Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html"><i class="fa fa-check"></i><b>11</b> Introduction to GLM: One-factor ANOVA</a><ul>
<li class="chapter" data-level="11.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#overview-10"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#preclass-activity-8"><i class="fa fa-check"></i><b>11.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="11.2.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#read-1"><i class="fa fa-check"></i><b>11.2.1</b> Read</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#inclass-activity-9"><i class="fa fa-check"></i><b>11.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="11.3.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#test-your-understanding"><i class="fa fa-check"></i><b>11.3.1</b> Test your understanding</a></li>
<li class="chapter" data-level="11.3.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#estimating-model-components"><i class="fa fa-check"></i><b>11.3.2</b> Estimating model components</a></li>
<li class="chapter" data-level="11.3.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#test-your-understanding-1"><i class="fa fa-check"></i><b>11.3.3</b> Test your understanding</a></li>
<li class="chapter" data-level="11.3.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#recreate-decomposition-matrix-from-the-raw-data"><i class="fa fa-check"></i><b>11.3.4</b> Recreate decomposition matrix from the raw data</a></li>
<li class="chapter" data-level="11.3.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#step-1-create-the-basic-tibble"><i class="fa fa-check"></i><b>11.3.5</b> Step 1: Create the basic tibble</a></li>
<li class="chapter" data-level="11.3.6" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#step-3-entering-the-estimates-hata_1-hata_2-hata_3"><i class="fa fa-check"></i><b>11.3.6</b> Step 3: Entering the estimates <span class="math inline">\(\hat{A}_1\)</span>, <span class="math inline">\(\hat{A}_2\)</span>, <span class="math inline">\(\hat{A}_3\)</span></a></li>
<li class="chapter" data-level="11.3.7" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#step-4-calculate-widehatsa_ijs"><i class="fa fa-check"></i><b>11.3.7</b> Step 4: Calculate <span class="math inline">\(\widehat{S(A)}_{ij}\)</span>s</a></li>
<li class="chapter" data-level="11.3.8" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#step-5-sums-of-squares"><i class="fa fa-check"></i><b>11.3.8</b> Step 5: Sums of squares</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#assignment-10"><i class="fa fa-check"></i><b>11.4</b> Assignment</a><ul>
<li class="chapter" data-level="11.4.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-1"><i class="fa fa-check"></i><b>11.4.1</b> Question 1</a></li>
<li class="chapter" data-level="11.4.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-2"><i class="fa fa-check"></i><b>11.4.2</b> Question 2</a></li>
<li class="chapter" data-level="11.4.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-3"><i class="fa fa-check"></i><b>11.4.3</b> Question 3</a></li>
<li class="chapter" data-level="11.4.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-4"><i class="fa fa-check"></i><b>11.4.4</b> Question 4</a></li>
<li class="chapter" data-level="11.4.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-5"><i class="fa fa-check"></i><b>11.4.5</b> Question 5</a></li>
<li class="chapter" data-level="11.4.6" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-6"><i class="fa fa-check"></i><b>11.4.6</b> Question 6</a></li>
<li class="chapter" data-level="11.4.7" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-7"><i class="fa fa-check"></i><b>11.4.7</b> Question 7</a></li>
<li class="chapter" data-level="11.4.8" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-8"><i class="fa fa-check"></i><b>11.4.8</b> Question 8</a></li>
<li class="chapter" data-level="11.4.9" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#question-9-create-your-own-decomposition-matrix"><i class="fa fa-check"></i><b>11.4.9</b> Question 9: Create your own decomposition matrix</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#solutions-to-questions-10"><i class="fa fa-check"></i><b>11.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="11.5.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#inclass-activities-7"><i class="fa fa-check"></i><b>11.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="11.5.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#homework-activities-1"><i class="fa fa-check"></i><b>11.5.2</b> Homework Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html"><i class="fa fa-check"></i><b>12</b> Continuing the GLM: One-factor ANOVA</a><ul>
<li class="chapter" data-level="12.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#overview-11"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#preclass-activity-9"><i class="fa fa-check"></i><b>12.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="12.2.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#read-2"><i class="fa fa-check"></i><b>12.2.1</b> Read</a></li>
<li class="chapter" data-level="12.2.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#try"><i class="fa fa-check"></i><b>12.2.2</b> Try</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#inclass-activity-10"><i class="fa fa-check"></i><b>12.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="12.3.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#task-1-7"><i class="fa fa-check"></i><b>12.3.1</b> Task 1</a></li>
<li class="chapter" data-level="12.3.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#task-2-mean-squares-and-degrees-of-freedom"><i class="fa fa-check"></i><b>12.3.2</b> Task 2: Mean squares and degrees of freedom</a></li>
<li class="chapter" data-level="12.3.3" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#task-3-f-ratios"><i class="fa fa-check"></i><b>12.3.3</b> Task 3: F-ratios</a></li>
<li class="chapter" data-level="12.3.4" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#using-ezezanova"><i class="fa fa-check"></i><b>12.3.4</b> Using ez::ezANOVA()</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#assignment-11"><i class="fa fa-check"></i><b>12.4</b> Assignment</a></li>
<li class="chapter" data-level="12.5" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#solutions-to-questions-11"><i class="fa fa-check"></i><b>12.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="12.5.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#inclass-activities-8"><i class="fa fa-check"></i><b>12.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html"><i class="fa fa-check"></i><b>13</b> Continuing the GLM: Two-factor designs</a><ul>
<li class="chapter" data-level="13.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#overview-12"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#preclass-activity-10"><i class="fa fa-check"></i><b>13.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="13.2.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#read-3"><i class="fa fa-check"></i><b>13.2.1</b> Read</a></li>
<li class="chapter" data-level="13.2.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#try-1"><i class="fa fa-check"></i><b>13.2.2</b> TRY</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#inclass-activity-11"><i class="fa fa-check"></i><b>13.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="13.3.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#estimation-equations-and-decomposition-matrix"><i class="fa fa-check"></i><b>13.3.1</b> Estimation equations and decomposition matrix</a></li>
<li class="chapter" data-level="13.3.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#adding-the-missing-columns"><i class="fa fa-check"></i><b>13.3.2</b> Adding the missing columns</a></li>
<li class="chapter" data-level="13.3.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#understanding-the-two-factor-decomposition-matrix"><i class="fa fa-check"></i><b>13.3.3</b> Understanding the two-factor decomposition matrix</a></li>
<li class="chapter" data-level="13.3.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#get-your-data-ready-for-analysis"><i class="fa fa-check"></i><b>13.3.4</b> Get your data ready for analysis</a></li>
<li class="chapter" data-level="13.3.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#visualizing-2x2-designs-in-r-the-interaction-plot"><i class="fa fa-check"></i><b>13.3.5</b> Visualizing 2x2 designs in R: The interaction plot</a></li>
<li class="chapter" data-level="13.3.6" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#running-a-2x2-between-subjects-anova-with-ezanova"><i class="fa fa-check"></i><b>13.3.6</b> Running a 2x2 between-subjects ANOVA with ezANOVA</a></li>
<li class="chapter" data-level="13.3.7" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#summarising-the-output"><i class="fa fa-check"></i><b>13.3.7</b> Summarising the output</a></li>
<li class="chapter" data-level="13.3.8" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#app-understanding-main-effects-and-interactions"><i class="fa fa-check"></i><b>13.3.8</b> App: Understanding main effects and interactions</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#assignment-12"><i class="fa fa-check"></i><b>13.4</b> Assignment</a><ul>
<li class="chapter" data-level="13.4.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-1a-libraries-2"><i class="fa fa-check"></i><b>13.4.1</b> Task 1A: Libraries</a></li>
<li class="chapter" data-level="13.4.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-1b-loading-in-the-data-2"><i class="fa fa-check"></i><b>13.4.2</b> Task 1B: Loading in the data</a></li>
<li class="chapter" data-level="13.4.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-2-calculate-cell-means"><i class="fa fa-check"></i><b>13.4.3</b> Task 2: Calculate cell means</a></li>
<li class="chapter" data-level="13.4.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-3-marginal-means-for-sex"><i class="fa fa-check"></i><b>13.4.4</b> Task 3: Marginal means for sex</a></li>
<li class="chapter" data-level="13.4.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-4-marginal-means-for-condition"><i class="fa fa-check"></i><b>13.4.5</b> Task 4: Marginal means for condition</a></li>
<li class="chapter" data-level="13.4.6" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-5-interaction-plot"><i class="fa fa-check"></i><b>13.4.6</b> Task 5: Interaction plot</a></li>
<li class="chapter" data-level="13.4.7" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-6-recap-question-1"><i class="fa fa-check"></i><b>13.4.7</b> Task 6: Recap Question 1</a></li>
<li class="chapter" data-level="13.4.8" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-7-recap-question-2"><i class="fa fa-check"></i><b>13.4.8</b> Task 7: Recap Question 2</a></li>
<li class="chapter" data-level="13.4.9" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-8-recap-question-3"><i class="fa fa-check"></i><b>13.4.9</b> Task 8: Recap Question 3</a></li>
<li class="chapter" data-level="13.4.10" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-9-running-the-factorial-anova"><i class="fa fa-check"></i><b>13.4.10</b> Task 9: Running the factorial ANOVA</a></li>
<li class="chapter" data-level="13.4.11" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-10-interpreting-the-anova-output-question"><i class="fa fa-check"></i><b>13.4.11</b> Task 10: Interpreting the ANOVA output Question</a></li>
<li class="chapter" data-level="13.4.12" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#task-11-report-your-results"><i class="fa fa-check"></i><b>13.4.12</b> Task 11: Report your results</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#solutions-to-questions-12"><i class="fa fa-check"></i><b>13.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="13.5.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#inclass-activities-9"><i class="fa fa-check"></i><b>13.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="13.5.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#homework-activities-2"><i class="fa fa-check"></i><b>13.5.2</b> Homework Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>14</b> Regression</a><ul>
<li class="chapter" data-level="14.1" data-path="regression.html"><a href="regression.html#overview-13"><i class="fa fa-check"></i><b>14.1</b> Overview</a></li>
<li class="chapter" data-level="14.2" data-path="regression.html"><a href="regression.html#preclass-activity-11"><i class="fa fa-check"></i><b>14.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="14.2.1" data-path="regression.html"><a href="regression.html#read-4"><i class="fa fa-check"></i><b>14.2.1</b> Read</a></li>
<li class="chapter" data-level="14.2.2" data-path="regression.html"><a href="regression.html#try-2"><i class="fa fa-check"></i><b>14.2.2</b> Try</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="regression.html"><a href="regression.html#inclass-activity-12"><i class="fa fa-check"></i><b>14.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="14.3.1" data-path="regression.html"><a href="regression.html#the-voice"><i class="fa fa-check"></i><b>14.3.1</b> The Voice</a></li>
<li class="chapter" data-level="14.3.2" data-path="regression.html"><a href="regression.html#task-1-setup"><i class="fa fa-check"></i><b>14.3.2</b> Task 1: Setup</a></li>
<li class="chapter" data-level="14.3.3" data-path="regression.html"><a href="regression.html#task-2-restructuring-the-ratings"><i class="fa fa-check"></i><b>14.3.3</b> Task 2: Restructuring the ratings</a></li>
<li class="chapter" data-level="14.3.4" data-path="regression.html"><a href="regression.html#task-3-calculate-mean-trustworthiness-rating-for-each-voice"><i class="fa fa-check"></i><b>14.3.4</b> Task 3: Calculate mean trustworthiness rating for each voice</a></li>
<li class="chapter" data-level="14.3.5" data-path="regression.html"><a href="regression.html#task-4-joining-the-data-together"><i class="fa fa-check"></i><b>14.3.5</b> Task 4: Joining the Data together</a></li>
<li class="chapter" data-level="14.3.6" data-path="regression.html"><a href="regression.html#task-5-scatterplot"><i class="fa fa-check"></i><b>14.3.6</b> Task 5: Scatterplot</a></li>
<li class="chapter" data-level="14.3.7" data-path="regression.html"><a href="regression.html#task-6-spreading-the-data"><i class="fa fa-check"></i><b>14.3.7</b> Task 6: Spreading the data</a></li>
<li class="chapter" data-level="14.3.8" data-path="regression.html"><a href="regression.html#task-7-the-regressions"><i class="fa fa-check"></i><b>14.3.8</b> Task 7: The Regressions</a></li>
<li class="chapter" data-level="14.3.9" data-path="regression.html"><a href="regression.html#task-8-making-interpretations"><i class="fa fa-check"></i><b>14.3.9</b> Task 8: Making interpretations</a></li>
<li class="chapter" data-level="14.3.10" data-path="regression.html"><a href="regression.html#task-9-making-predictions"><i class="fa fa-check"></i><b>14.3.10</b> Task 9: Making predictions</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="regression.html"><a href="regression.html#assignment-13"><i class="fa fa-check"></i><b>14.4</b> Assignment</a></li>
<li class="chapter" data-level="14.5" data-path="regression.html"><a href="regression.html#solutions-to-questions-13"><i class="fa fa-check"></i><b>14.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="14.5.1" data-path="regression.html"><a href="regression.html#inclass-ativities"><i class="fa fa-check"></i><b>14.5.1</b> InClass Ativities</a></li>
<li class="chapter" data-level="14.5.2" data-path="regression.html"><a href="regression.html#task-3-6"><i class="fa fa-check"></i><b>14.5.2</b> Task 3</a></li>
<li class="chapter" data-level="14.5.3" data-path="regression.html"><a href="regression.html#task-4-7"><i class="fa fa-check"></i><b>14.5.3</b> Task 4</a></li>
<li class="chapter" data-level="14.5.4" data-path="regression.html"><a href="regression.html#task-5-6"><i class="fa fa-check"></i><b>14.5.4</b> Task 5</a></li>
<li class="chapter" data-level="14.5.5" data-path="regression.html"><a href="regression.html#task-6-6"><i class="fa fa-check"></i><b>14.5.5</b> Task 6</a></li>
<li class="chapter" data-level="14.5.6" data-path="regression.html"><a href="regression.html#task-7-6"><i class="fa fa-check"></i><b>14.5.6</b> Task 7</a></li>
<li class="chapter" data-level="14.5.7" data-path="regression.html"><a href="regression.html#task-8-4"><i class="fa fa-check"></i><b>14.5.7</b> Task 8</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html"><i class="fa fa-check"></i><b>15</b> Combining ANOVA And Regression</a><ul>
<li class="chapter" data-level="15.1" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#overview-14"><i class="fa fa-check"></i><b>15.1</b> Overview</a></li>
<li class="chapter" data-level="15.2" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#preclass-activity-12"><i class="fa fa-check"></i><b>15.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="15.2.1" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#read-5"><i class="fa fa-check"></i><b>15.2.1</b> Read</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#inclass-activity-13"><i class="fa fa-check"></i><b>15.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="15.3.1" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#loading-in-the-data"><i class="fa fa-check"></i><b>15.3.1</b> Loading in the data</a></li>
<li class="chapter" data-level="15.3.2" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#the-data"><i class="fa fa-check"></i><b>15.3.2</b> The Data</a></li>
<li class="chapter" data-level="15.3.3" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#compute-the-well-being-score-for-each-participant"><i class="fa fa-check"></i><b>15.3.3</b> Compute the well-being score for each participant</a></li>
<li class="chapter" data-level="15.3.4" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#visualising-screen-time-on-all-technologies"><i class="fa fa-check"></i><b>15.3.4</b> Visualising Screen time on all technologies</a></li>
<li class="chapter" data-level="15.3.5" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#visualising-the-screen-time-and-well-being-relationship"><i class="fa fa-check"></i><b>15.3.5</b> Visualising the Screen time and Well-being relationship</a></li>
<li class="chapter" data-level="15.3.6" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#smartphone-and-well-being-for-boys-and-girls"><i class="fa fa-check"></i><b>15.3.6</b> Smartphone and well-being for boys and girls</a></li>
<li class="chapter" data-level="15.3.7" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#visualise-and-interpreting-the-relationship-of-smartphone-use-and-wellbeing-by-sex"><i class="fa fa-check"></i><b>15.3.7</b> Visualise and Interpreting the relationship of smartphone use and wellbeing by sex</a></li>
<li class="chapter" data-level="15.3.8" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#a-side-point-on-mean-centering-and-deviation-coding"><i class="fa fa-check"></i><b>15.3.8</b> A side point on mean centering and deviation coding</a></li>
<li class="chapter" data-level="15.3.9" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#estimating-model-parameters"><i class="fa fa-check"></i><b>15.3.9</b> Estimating model parameters</a></li>
<li class="chapter" data-level="15.3.10" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#final-interpretations"><i class="fa fa-check"></i><b>15.3.10</b> Final Interpretations</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#assignment-14"><i class="fa fa-check"></i><b>15.4</b> Assignment</a></li>
<li class="chapter" data-level="15.5" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#solutions-to-questions-14"><i class="fa fa-check"></i><b>15.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="15.5.1" data-path="combining-anova-and-regression.html"><a href="combining-anova-and-regression.html#inclass-activities-10"><i class="fa fa-check"></i><b>15.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html"><i class="fa fa-check"></i><b>16</b> Reflection - Semester 2</a><ul>
<li class="chapter" data-level="16.1" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#overview-15"><i class="fa fa-check"></i><b>16.1</b> Overview</a></li>
<li class="chapter" data-level="16.2" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#preclass-activity-13"><i class="fa fa-check"></i><b>16.2</b> PreClass Activity</a></li>
<li class="chapter" data-level="16.3" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#inclass-activity-14"><i class="fa fa-check"></i><b>16.3</b> InClass Activity</a></li>
<li class="chapter" data-level="16.4" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#assignment-15"><i class="fa fa-check"></i><b>16.4</b> Assignment</a></li>
<li class="chapter" data-level="16.5" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#solutions-to-questions-15"><i class="fa fa-check"></i><b>16.5</b> Solutions to Questions</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>A</b> References</a></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ug2-practical</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="continuing-the-glm-two-factor-designs" class="section level1">
<h1><span class="header-section-number">Lab 13</span> Continuing the GLM: Two-factor designs</h1>
<div id="overview-12" class="section level2">
<h2><span class="header-section-number">13.1</span> Overview</h2>
<p>For the past couple of weeks we have been building our understanding of the General Linear Model and in particular how it applies to a one-factor between-subjects ANOVA. Remember this is the scenario where you have one IV (categorical) and one DV (continuous) and you want to know if there is a significant effect at the different levels of your factor; where factor is another name for variable (or IV) and level is another name for condition (or group). We started out with the decomposition matrix, calculated our sums of squares, and from there our F-value to determine if there was a significant effect. One thing that is really worth keeping in mind is that the ANOVA is an omnibus test in that it tells you there is a significant effect of that factor, but it doesn’t specifically say in which way is that effect manifested; you always have to do a little work there to tease out the pattern of the effect. Say for instance you test a one-way ANOVA on three animal categories on some test (dogs, cats, gerbils). The ANOVA will tell you if there is an overall effect (or difference between groups) but you need to do a little work to find out is the difference between cats and dogs, dogs and gerbils, etc etc. But more on that another time.</p>
<p>One-way ANOVAs are great when you only have one IV but the really useful thing about ANOVAs, and the GLM really, is that it can handle much more complex situations; which we are going to look at a little today. You were asked to read up on Chapter 4 of Miller and Haden (2013) looking at two-factor, between-subjects designs. This is the scenario where you have two factors (IVs) and it is different people in each condition. For example, say your IVs were people who can/can’t juggle, and people who do/don’t have pets. You have 4 groups here as you have people who can juggle and have pets, people who can’t juggle and have pets, people who can juggle and don’t have pets, and people who can’t juggle and who don’t have pets (how sad!!!). This would be an example of a two-way between-subjects factorial ANOVA. And it is this scenario that we will look at today.</p>

</div>
<div id="preclass-activity-10" class="section level2">
<h2><span class="header-section-number">13.2</span> PreClass Activity</h2>
<div id="read-3" class="section level3">
<h3><span class="header-section-number">13.2.1</span> Read</h3>
<p>Read Chapter 4 of &lt;a href=“<a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" class="uri">https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view</a>”, target = &quot;_blank&quot;&gt;Miller and Haden (2013)</a> and try to understand the situation where you have 2 factors with at least two levels each; in this lab we will look at interactions.</p>
</div>
<div id="try-1" class="section level3">
<h3><span class="header-section-number">13.2.2</span> TRY</h3>
<p><strong>Test your understanding of Miller and Haden (2013) Chapter 4</strong></p>
<ol style="list-style-type: decimal">
<li><p>To test your understanding, work through Computational Exercise #1 in Section 4.9 of Miller and Haden - the answer is in Section 4.10 so check your working but be sure to work through the example first. The concept of interactions should be familiar to you from Stats Lecture 6 Semester 2.</p></li>
<li><p>Try these short MCQs on two factor, between-subjects designs:</p></li>
<li><p>A 2x2 factorial design contains how many cells? <select class='solveme' data-answer='["four"]'> <option></option> <option>two</option> <option>four</option> <option>six</option> <option>eight</option> <option>who do we appreciate!</option></select></p></li>
<li><p>What effect is / effects are tested in a 2x2 ANOVA with factors A and B? <select class='solveme' data-answer='["the main effects of A and B, and the AB interaction"]'> <option></option> <option>the main effects of A and B, and the AB interaction</option> <option>only the main effects of A and B</option> <option>only the AB interaction</option> <option>a correlation between A and B</option></select></p></li>
<li><p>What is a marginal mean? <select class='solveme' data-answer='["the mean DV at a given level of one factor, averaged over the levels of the other"]'> <option></option> <option>the mean DV at a given level of one factor, averaged over the levels of the other</option> <option>the mean DV at a given level of one factor, at a particular level of the other factor</option> <option>a mean that is nearly statistically significant</option> <option>a mean defined based on marginal likelihood</option></select></p></li>
<li><p>A statistical test for a main effect tests the null hypothesis that <select class='solveme' data-answer='["population marginal means are equivalent"]'> <option></option> <option>simple effects in the sample are equivalent</option> <option>simple effects in the population are equivalent</option> <option>sample marginal means are equivalent</option> <option>population marginal means are equivalent</option></select></p></li>
<li><p>A statistical test for an interaction tests the null hypothesis that <select class='solveme' data-answer='["the effect of one factor is constant across the levels of the other in the population"]'> <option></option> <option>the effect of one factor is constant across the levels of the other in the population</option> <option>the effect of one factor is constant across the levels of the other in the sample</option> <option>sample marginal means are equivalent</option> <option>population marginal means are equivalent</option></select></p></li>
</ol>
<p>If you are not sure about the above questions, go back and read the chapter and make sure you understand the difference between a main effect (the effect at one of the IVs) and the interaction (the effect of one factor dependent on the levels of the other factor). Those are the key elements to really wrap your head around in a factorial ANOVA.</p>
<p><strong>Note:</strong> factorial ANOVAs can get really complex with three, four, or more IVs, so when writing about one, it is often good to state something like two-way (meaning two IVs) or three-way (meaning three IVs) etc. Be clear for your reader.</p>

</div>
</div>
<div id="inclass-activity-11" class="section level2">
<h2><span class="header-section-number">13.3</span> InClass Activity</h2>
<div id="estimation-equations-and-decomposition-matrix" class="section level3">
<h3><span class="header-section-number">13.3.1</span> Estimation equations and decomposition matrix</h3>
<p>We will start today by working with a decomposition matrix for a two-way between-subjects ANOVA and then finish by using the <code>ez::ezANOVA()</code> function to show you how you might practically carry out this analysis.</p>
<p>Consider the data below from a 2x2 design with 3 observations per cell. Keep in mind that each cell is a particular combination of levels of A and B, and each value in a cell, in this instance, is a unique participant.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="left">B1</th>
<th align="left">B2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A1</td>
<td align="left">74, 65, 77</td>
<td align="left">70, 74, 66</td>
</tr>
<tr class="even">
<td>A2</td>
<td align="left">67, 67, 64</td>
<td align="left">78, 78, 84</td>
</tr>
</tbody>
</table>
<p>The decomposition matrix for these data is shown below; however, rather unfortunately for us, it is missing the columns <code>AB_ij</code> (<span class="math inline">\(\hat{A}_{ij}\)</span>) and <code>err</code> (<span class="math inline">\(\widehat{S(AB)}_{ijk}\)</span>) which we will need to calculate to complete our analysis.</p>
<p>Here is a little recap of the columns (plus the two we will add):</p>
<ul>
<li><span class="math inline">\(i\)</span> - the first factor (here with two levels)</li>
<li><span class="math inline">\(j\)</span> - the second factor (again here with two levels)</li>
<li><span class="math inline">\(k\)</span> - the participant number within that <span class="math inline">\(ij\)</span> combination</li>
<li><span class="math inline">\(Y_ijk\)</span> - a participants score on a DV</li>
<li><span class="math inline">\(mu\)</span> - the overall grand mean (or baseline effect)</li>
<li><span class="math inline">\(A_i\)</span> - the effect of the first factor <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(B_j\)</span> - the effect of the second factor <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(\hat{A}_{ij}\)</span> - the effect of the AB interaction</li>
<li><span class="math inline">\(\widehat{S(AB)}_{ijk}\)</span> - the effect of within-group variability or error, <code>err</code></li>
</ul>
<pre><code>## # A tibble: 12 x 7
##        i     j     k Y_ijk    mu   A_i   B_j
##    &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1     1     1     1    74    72    -1    -3
##  2     1     1     2    65    72    -1    -3
##  3     1     1     3    77    72    -1    -3
##  4     1     2     1    70    72    -1     3
##  5     1     2     2    74    72    -1     3
##  6     1     2     3    66    72    -1     3
##  7     2     1     1    67    72     1    -3
##  8     2     1     2    67    72     1    -3
##  9     2     1     3    64    72     1    -3
## 10     2     2     1    78    72     1     3
## 11     2     2     2    78    72     1     3
## 12     2     2     3    84    72     1     3</code></pre>
<p>The code to create the above matrix is in the solutions at the end of this chapter in case you want to create the matrix yourself as practice. If not, copy and paste this code into a code chunk of an RMarkdown file or into an R script (and make sure you also load tidyverse so that you can use the dplyr functions and pipes.) As Yoda once said, “do or do not, there is no try!”</p>
<p>Run the code and look at <code>decomp</code> to confirm to yourself that it worked. Note the use of the <code>group_by()</code> function so that the values calculated with in <code>mutate()</code> are only calculated for each group.</p>
</div>
<div id="adding-the-missing-columns" class="section level3">
<h3><span class="header-section-number">13.3.2</span> Adding the missing columns</h3>
<p>Once you understand the table and code, try writing code to add the two missing columns to our matrix. Store the resulting table in <code>decomp2</code>.</p>
<p>Here are some hints but again the code is in the solutions if you can’t quite get it - remember, as Dumbledore once paraphrased, “Help will always be given at Glasgow to those that look for it.”</p>
<p><strong>Hints:</strong></p>
<ul>
<li><code>AB_ij</code> (<span class="math inline">\(\hat{A}_{ij}\)</span>) is what is left of the mean value of all participants in that group once you have removed the effect of the grand mean, the effect of factor one, and the effect of factor two</li>
<li><code>err</code> (<span class="math inline">\(\widehat{S(AB)}_{ijk}\)</span>) is what is left from an individual’s score after removing the effect of the grand mean, the effect of factor A, the effect of factor B, and the interaction effect.</li>
</ul>
</div>
<div id="understanding-the-two-factor-decomposition-matrix" class="section level3">
<h3><span class="header-section-number">13.3.3</span> Understanding the two-factor decomposition matrix</h3>
<p>If you have performed the above steps correctly, then the decomp matrix should now look like</p>
<table>
<thead>
<tr class="header">
<th align="right">i</th>
<th align="right">j</th>
<th align="right">k</th>
<th align="right">Y_ijk</th>
<th align="right">mu</th>
<th align="right">A_i</th>
<th align="right">B_j</th>
<th align="right">AB_ij</th>
<th align="right">err</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">74</td>
<td align="right">72</td>
<td align="right">-1</td>
<td align="right">-3</td>
<td align="right">4</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">65</td>
<td align="right">72</td>
<td align="right">-1</td>
<td align="right">-3</td>
<td align="right">4</td>
<td align="right">-7</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">77</td>
<td align="right">72</td>
<td align="right">-1</td>
<td align="right">-3</td>
<td align="right">4</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">70</td>
<td align="right">72</td>
<td align="right">-1</td>
<td align="right">3</td>
<td align="right">-4</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">74</td>
<td align="right">72</td>
<td align="right">-1</td>
<td align="right">3</td>
<td align="right">-4</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">66</td>
<td align="right">72</td>
<td align="right">-1</td>
<td align="right">3</td>
<td align="right">-4</td>
<td align="right">-4</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">67</td>
<td align="right">72</td>
<td align="right">1</td>
<td align="right">-3</td>
<td align="right">-4</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">67</td>
<td align="right">72</td>
<td align="right">1</td>
<td align="right">-3</td>
<td align="right">-4</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">64</td>
<td align="right">72</td>
<td align="right">1</td>
<td align="right">-3</td>
<td align="right">-4</td>
<td align="right">-2</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">78</td>
<td align="right">72</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">-2</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">78</td>
<td align="right">72</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">-2</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">84</td>
<td align="right">72</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">4</td>
</tr>
</tbody>
</table>
<p>So let’s now make sure we understand the table that we have and that we can pinpoint different elements of it by answering the following questions:</p>
<ol style="list-style-type: decimal">
<li><p>From the options, what was the DV-value of participant <span class="math inline">\(Y_{212}\)</span>? <select class='solveme' data-answer='["67"]'> <option></option> <option>64</option> <option>65</option> <option>66</option> <option>67</option></select></p></li>
<li><p>Type in the value of <span class="math inline">\(SS_{B}\)</span>: <input class='solveme nospaces' size='3' data-answer='["108"]'/></p></li>
<li><p>Type in the value of <span class="math inline">\(SS_{error}\)</span> is: <input class='solveme nospaces' size='3' data-answer='["140"]'/></p></li>
<li><p>Type in the value of <span class="math inline">\(MS_{B}\)</span> is: <input class='solveme nospaces' size='3' data-answer='["108"]'/></p></li>
<li><p>Type in the value of <span class="math inline">\(MS_{error}\)</span> (to one decimal places) is: <input class='solveme nospaces' size='3' data-answer='["17.5"]'/></p></li>
<li><p>The value of <span class="math inline">\(F_{B}\)</span> (the F-ratio for the main effect of B) to 3 decimal places is: <input class='solveme nospaces' size='3' data-answer='["6.171"]'/></p></li>
<li><p>The numerator and denominator degrees of freedom associated with this <span class="math inline">\(F\)</span> ratio are <input class='solveme nospaces' size='3' data-answer='["1"]'/> and <input class='solveme nospaces' size='3' data-answer='["8"]'/> respectively</p></li>
<li><p>The <span class="math inline">\(p\)</span> value associated with this F ratio to three decimal places is (HINT: <code>?pf</code>): <input class='solveme nospaces' size='3' data-answer='["0.038",".038"]'/></p></li>
</ol>
</div>
<div id="get-your-data-ready-for-analysis" class="section level3">
<h3><span class="header-section-number">13.3.4</span> Get your data ready for analysis</h3>
<p>It is excellent that you now understand a decomposition matrix and how it relates to an F-ratio. In reality however, we rarely will you ever derive a decomposition matrix by hand; the point was to improve your understanding of the calculations behind an ANOVA.</p>
<p>Let’s continue using the simulated data from above and run through the analysis steps we would normally follow. But first, let’s put it in a more useful format.</p>
<p>The first thing we might want to do is to add columns that more clearly indicate the levels of our two factors. Right now the levels of A are represented by <code>i</code> and the levels of <code>B</code> are represented by <code>j</code>. But the data should really look more like this below:</p>
<pre><code>## # A tibble: 12 x 4
##       id A     B     Y_ijk
##    &lt;int&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;
##  1     1 A1    B1       74
##  2     2 A1    B1       65
##  3     3 A1    B1       77
##  4     4 A1    B2       70
##  5     5 A1    B2       74
##  6     6 A1    B2       66
##  7     7 A2    B1       67
##  8     8 A2    B1       67
##  9     9 A2    B1       64
## 10    10 A2    B2       78
## 11    11 A2    B2       78
## 12    12 A2    B2       84</code></pre>
<p>We will need the <code>id</code> column (a unique value for each participant) for when we run <code>ezANOVA()</code> later.</p>
<p>Again the code to convert <code>decomp</code> into this table (named <code>dat</code>) is hidden below and you can use it if you like, but if you want to practice your skills first and convert the table yourself, that is also fine. Don’t spend too long on it though as it is more the output we want to look at. So if you are stuck, copy the code and run it in your session. We’ll be working with the new table <code>dat</code> for the remaining exercises.</p>
</div>
<div id="visualizing-2x2-designs-in-r-the-interaction-plot" class="section level3">
<h3><span class="header-section-number">13.3.5</span> Visualizing 2x2 designs in R: The interaction plot</h3>
<p>A critical part of data analysis is visualization. When dealing with factorial data, one of the most important visualizations is the <em>interaction plot</em> showing the cell means. You have already seen some of these in the Miller and Haden chapter and in the previous labs.</p>
<p>Remember that before you can make an interaction plot, you need to calculate the cell means.</p>
<ul>
<li><p>First create a table called <code>cell_means</code> with the cell means stored in the column <code>m</code>. <strong>HINT</strong> - think group_by and summarise to leave three columns only, each with 4 rows. For example, one row will show A, A, mean-value</p></li>
<li><p>Next, reproduce the plot below. Don’t look at the solution below until you’ve really tried! You will need two geoms: one to draw the points, one to draw the lines. And think about what is your x and y axes and how do you group the lines.</p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-10"></span>
<img src="13-s02-lab13c_files/figure-html/unnamed-chunk-10-1.png" alt="**CAPTION THIS FIGURE!!**" width="100%" />
<p class="caption">
Figure 13.1: <strong>CAPTION THIS FIGURE!!</strong>
</p>
</div>
</div>
<div id="running-a-2x2-between-subjects-anova-with-ezanova" class="section level3">
<h3><span class="header-section-number">13.3.6</span> Running a 2x2 between-subjects ANOVA with ezANOVA</h3>
<p>Excellent! So we have a figure now! In reality, you would want to embellish this figure to make it look more professional, add some error bars, make sure the whole of the y-axis is shown, give proper names to the factors and levels, but it will do for now. You also want to look at the figure and think about what it is telling you. Do you think there will be:</p>
<ol style="list-style-type: lower-alpha">
<li>A main effect of Factor A?</li>
<li>A main effect of Factor B?</li>
<li>An interaction between Factors A and B?</li>
</ol>
<p>To some degree these are the three basic hypotheses laid out in any two-way ANOVA. To answer these you can think about:</p>
<ol style="list-style-type: lower-alpha">
<li>Are the means of <span class="math inline">\(A_1\)</span> and <span class="math inline">\(A_2\)</span> different, disregarding the effect of Factor B?</li>
<li>Are the means of <span class="math inline">\(B_1\)</span> and <span class="math inline">\(B_2\)</span> different, disregarding the effect of Factor A?</li>
<li>Are the means of <span class="math inline">\(A_1\)</span> and <span class="math inline">\(A_2\)</span> influenced by the effect of Factor B? What do non-parallel (or crossing lines) suggest about an interaction?</li>
</ol>
<p>Looking at the figure you might suggest, no main effect of A, no main effect of B, but that there is an interaction between A and B. Let’s test this using the <code>ez:ezANOVA()</code> function!</p>
<ul>
<li>Perform the 2x2 ANOVA on <code>dat</code> and store the output in <code>result</code>.
<ul>
<li>Try not to look at the solution until you have tried the <code>?ezANOVA</code> to see how to add more than one condition of the same design.</li>
<li>a second hint is that both factors are “between”, so you want to focus on adding a second “between” condition</li>
</ul></li>
</ul>
<p>We have also hidden a short summary of the output of the ANOVA to give you an idea of the outcome. Think about the outcome for a moment or two before looking at the summary.</p>
</div>
<div id="summarising-the-output" class="section level3">
<h3><span class="header-section-number">13.3.7</span> Summarising the output</h3>
<p>So it turns out we were sort of right and sort of wrong. There was no main effect of Factor A as we predicted. The means at <span class="math inline">\(A_1\)</span> and <span class="math inline">\(A_2\)</span> are very similar when you disregard the effect of Factor B. However, there actually was a main effect of Factor B; i.e. there was a significant difference between the means of <span class="math inline">\(B_1\)</span> and <span class="math inline">\(B_2\)</span> when you disregard the effect of Factor A. In fact, you could go on to say that the mean of <span class="math inline">\(B_2\)</span> (M = 75) is significantly larger than the mean of <span class="math inline">\(B_1\)</span> (M = 69). And finally, we predicted that there would be a significant interaction and there was one because the effect of Factor A is modulated by Factor B, and vice versa.</p>
<p>One thing to point out here, when there are only two conditions in a factor and there is a significant main effect of that Factor (in this example Factor B) then to further qualify that effect you simply have to say which of the two conditions was bigger than the other! Group 2 bigger than Group 1 or Group 1 bigger than Group 2. When there is more than two conditions in a facor (e.g. three) or in the interaction, it is not that straightforward and you need to do further comparisons such as pairwise comparisons, t-test, simple main effects, or TUKEY HSDs, to tease those effects a part. We will cover more of that in the lecture series.</p>
</div>
<div id="app-understanding-main-effects-and-interactions" class="section level3">
<h3><span class="header-section-number">13.3.8</span> App: Understanding main effects and interactions</h3>
<p>If time permits (or on your own time), check out the accompanying shiny app on main effects and interactions. This allows you to move sliders and change the sizes of main effects / interactions and see how it affects cell means and effect decompositions. This will help sharpen your intuitions about these concepts. Download the app from Moodle or &lt;a href=“./data/13-s02/inclass/factorial_app.zip”, target = &quot;_blank&quot;&gt;from this link</a>.</p>
<p><strong>Job Done!</strong></p>
<p>You should now be ready to complete the Homework Assignment for this lab. <strong>The assignment for this Lab is FORMATIVE and is NOT to be submitted and will NOT count towards the overall grade for this module.</strong> However you are strongly encouraged to do the assignment as it will continue to boost your skills which you will need in future assignments. If you have any questions, please post them on the slack forum under the channel <strong>#level2_2018</strong></p>

</div>
</div>
<div id="assignment-12" class="section level2">
<h2><span class="header-section-number">13.4</span> Assignment</h2>
<p>This is a summative assignment. Instructions as to how to access and submit your assignment will be made available during the course.</p>
<p><strong>Lab 13: Two-Factor ANOVA: Perspective-Taking in Language Comprehension</strong></p>
<p>In order to complete this assignment you first have to download the assignment .Rmd file which you need to edit for this assignment: titled <code>GUID_Level2_Semester2_Lab4.Rmd</code>. This can be downloaded within a zip file from the below link. Once downloaded and unzipped you should create a new folder that you will use as your working directory; put the .Rmd file in that folder and set your working directory to that folder through the drop-down menus at the top. &lt;a href=“<a href="https://www.psy.gla.ac.uk/~phil/L2Labs_201819/semester_two/lab_04/homework/Level2_Semester2_Lab4_AssignmentFiles.zip" class="uri">https://www.psy.gla.ac.uk/~phil/L2Labs_201819/semester_two/lab_04/homework/Level2_Semester2_Lab4_AssignmentFiles.zip</a>”, target = &quot;_blank&quot;&gt;Download the Assignment .zip file from here</a> or on Moodle.</p>
<p><strong>Background: Perspective-Taking in Language Comprehension</strong></p>
<p>For this assignment, you will be looking at real data from <strong>Experiment 2</strong> of &lt;a href = “<a href="https://www.sciencedirect.com/science/article/pii/S0010027703000647?via%3Dihub">https://www.sciencedirect.com/science/article/pii/S0010027703000647?via%3Dihub</a>”, target = &quot;_blank“&gt;Keysar, Lin, and Barr (2003)</a>,”Limits on Theory of Mind Use in Adults&quot;, <strong>Cognition</strong>, <strong>89</strong>, 29–41. This study used eye-tracking to investigate people’s ability to take another’s perspective during a kind of communication game. (The data that you will be analysing, while real, did not appear in the original report.)</p>
<p>The communication game that participants played was as follows. Each participant sat at a table opposite a confederate participant (a stooge from the lab who pretended to be a naive participant). Between the two participants was an upright set of shelves (see figure below). The participants played a game in which the real participant was assigned the role of the “matcher” and the confederate the role of the “director”. The director was given a picture with a goal state for the grid, showing how the objects needed to be arranged. However, the director was not allowed to touch the objects. To get the objects in their proper places, the director needed to give instructions to the matcher to move the objects. For example, the director might say, “take the red box in the top corner and move it down to the very bottom row,” and the matcher would then perform the action. The matcher’s eye movements were tracked as they listened to and interpreted the director’s instructions.</p>
<div class="figure" style="text-align: center"><span id="fig:img-lab13-grids"></span>
<img src="images/s02-lab13/homework/grids.png" alt="Director-Matcher Viewpoints from Keysar, Lin, and Barr (2003)" width="50%" />
<p class="caption">
Figure 13.2: Director-Matcher Viewpoints from Keysar, Lin, and Barr (2003)
</p>
</div>
<p>To investigate perspective taking, the instructions given by the director were actually scripted beforehand in order to create certain ambiguities. Most of the objects in the grid, such as the red box, were mutually visible to both participants (i.e., visible from both sides of the grid). However, some of objects, like the brush and the green candle, were occluded from the director’s view; the matcher could see them, but had no reason to believe that the director knew the contents of these occluded squares, and thus had no reason to expect her to ever refer to them. However, sometimes the director would refer to a mutually visible object using a description that also happened to match one of the hidden objects. For instance, the director might instruct the matcher to “pick up the small candle.” Note that for the director, the small candle is the purple candle. A given matcher would see this grid in one of two conditions: In the <strong>Experimental</strong> condition, the matcher saw an additional green candle in a hidden box that was even smaller than the purple candle (see middle panel of the above figure). This object was called a “competitor” because it matched the description of the intended referent (the purple candle). In the <strong>Baseline</strong> condition, the green candle was replaced with an object that did not match the director’s description, such as an apple. These ambiguous situations provided the main data for the experiment, and in total there were eight different grids in the experiment that presented analogous situations to the example above.</p>
<p>&lt;a href=“<a href="https://journals.sagepub.com/doi/abs/10.1111/1467-9280.00211" class="uri">https://journals.sagepub.com/doi/abs/10.1111/1467-9280.00211</a>”, target = &quot;_blank“&gt;A previous eye-tracking study by the same authors</a> had found the presence of the competitors severely confused the matchers, suggesting that people were surprisingly egocentric—they found it hard to ignore”privileged&quot; information when interpreting another person’s speech. For example, when the director said to “pick up the small candle,” they spent far more time looking at a hidden green candle than a hidden apple, even though neither one of these objects, being hidden, was a viable referent. We refer to the difference in looking time as the ‘egocentric interference effect’.</p>
<p>Experiment 2 by Keysar, Lin, and Barr aimed to follow up on this finding. In the previous article, the matcher had reason to believe that the director was merely ignorant of the identity of the hidden objects. But what would happen if the matcher was given reason to believe that the director actually had a <strong>false belief</strong> about the hidden object? For example, would the matcher experience less egocentric interference if he or she had reason to think that the director thought that the hidden candle was a toy truck?</p>
<p>To test this, half of the participants were randomly assigned to a <strong>false belief</strong> condition, where the matcher was led to believe that the director had a false belief about the identity of the hidden object; the other half participated in the <strong>ignorance</strong> condition, where as in previous experiments, they were led to believe that the director simply did not know what was in the hidden squares.</p>
<p>There were 40 participants in this study, 20 in the false belief condition, and 20 in the ignorance condition. There were also an equal number of male and female participants in the study. To spoil the plot a bit, Keysar, Lin and Barr did not find any effect of condition on looking time. However, they did not consider sex as a potential moderating variable. Thus, we will explore the effects of ignorance vs. false belief on egocentric interference, broken down by the sex of the matcher.</p>
<p><strong>Before starting lets check:</strong></p>
<ol style="list-style-type: decimal">
<li><p>The <code>.csv</code> file is saved into a folder on your computer and you have manually set this folder as your working directory.</p></li>
<li><p>The <code>.Rmd</code> file is saved in the same folder as the <code>.csv</code> files. For assessments we ask that you save it with the format <code>GUID_Level2_Semester2_Lab4.Rmd</code> where <code>GUID</code> is replaced with your <code>GUID</code>. Though this is a formative assessment, it may be good practice to do the same here.</p></li>
</ol>
<div id="task-1a-libraries-2" class="section level3">
<h3><span class="header-section-number">13.4.1</span> Task 1A: Libraries</h3>
<ul>
<li>In today’s assignment you will need both the <code>tidyverse</code> and <code>ez</code> packages. Enter code into the t1A code chunk below to load in both of these libraries.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load in the packages</span></code></pre>
</div>
<div id="task-1b-loading-in-the-data-2" class="section level3">
<h3><span class="header-section-number">13.4.2</span> Task 1B: Loading in the data</h3>
<ul>
<li>Use <code>read_csv()</code> to replace the <code>NULL</code> in the t1B code chunk below to load in the data stored in the datafile <code>keysar_lin_barr_2003.csv</code>. Store the data in the variable <code>dat</code>. Do not change the filename of the datafile.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
<p>Take a look at your data (<code>dat</code>) in the console using <code>glimpse()</code> or <code>View()</code>, or just display it by typing in the name. You will see the following columns:</p>
<table>
<thead>
<tr class="header">
<th>variable</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>subject</code></td>
<td>unique identifier for each subject</td>
</tr>
<tr class="even">
<td><code>sex</code></td>
<td>whether the subject was male or female</td>
</tr>
<tr class="odd">
<td><code>condition</code></td>
<td>what condition the subject was in</td>
</tr>
<tr class="even">
<td><code>looktime</code></td>
<td>egocentric interference</td>
</tr>
</tbody>
</table>
<p>We have simplified things from the original experiment by collapsing the baseline vs. experimental conditions into a single DV. Our DV, egocentric interference, is the average difference in looking time for each subject (in milliseconds per trial) for hidden competitors (e.g., small candle) versus hidden noncompetitors (e.g., apple). The larger this number, the more egocentric interference the subject experienced.</p>
</div>
<div id="task-2-calculate-cell-means" class="section level3">
<h3><span class="header-section-number">13.4.3</span> Task 2: Calculate cell means</h3>
<p>Today we are going to focus on just the main analysis and write-up, and not the assumptions, but as always before running any analysis you should check that your assumptions hold.</p>
<p>One of the elements we will need for our write-up is some descriptives. We want to start by creating some summary statistics for the four conditions. Remember, two factors (sex, condition) with 2 levels each (sex: female vs male; condition: false belief vs ignorance) will give four conditions, and as such in our summary table, four cells created by factorially combining sex and condition.</p>
<ul>
<li>Replace the NULL in the <code>t2</code> code chunk below to create the four cells created by factorially combining sex and condition, summarising the mean and standard deviation for each cell.
<ul>
<li>Store the descriptives in the tibble <code>cell_means</code></li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have four rows and four columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">cell_means &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
<table>
<thead>
<tr class="header">
<th align="left">sex</th>
<th align="left">condition</th>
<th align="left">m</th>
<th align="left">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="left">false belief</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="even">
<td align="left">female</td>
<td align="left">ignorance</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="odd">
<td align="left">male</td>
<td align="left">false belief</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="left">ignorance</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
</tbody>
</table>
</div>
<div id="task-3-marginal-means-for-sex" class="section level3">
<h3><span class="header-section-number">13.4.4</span> Task 3: Marginal means for sex</h3>
<p>We will also need to have some descriptives where we just look at the means of a given factor; the marginal means - the means of the levels of one factor regardless of the other factor.</p>
<ul>
<li>Replace the NULL in the <code>t3</code> code chunk below to calculate the marginal means and standard deviations for the factor, sex.
<ul>
<li>Store these descriptives in the tibble <code>marg_sex</code></li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have two rows and three columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">marg_sex &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
<table>
<thead>
<tr class="header">
<th align="left">sex</th>
<th align="left">m</th>
<th align="left">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
</tbody>
</table>
</div>
<div id="task-4-marginal-means-for-condition" class="section level3">
<h3><span class="header-section-number">13.4.5</span> Task 4: Marginal means for condition</h3>
<p>And now do the same for condition.</p>
<ul>
<li>Replace the NULL in the <code>t4</code> code chunk below to calculate the marginal means and standard deviations for the factor, condition
<ul>
<li>Store these descriptives in the tibble <code>marg_cond</code></li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have two rows and three columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">marg_cond &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
<table>
<thead>
<tr class="header">
<th align="left">condition</th>
<th align="left">m</th>
<th align="left">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">false belief</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="even">
<td align="left">ignorance</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
</tbody>
</table>
</div>
<div id="task-5-interaction-plot" class="section level3">
<h3><span class="header-section-number">13.4.6</span> Task 5: Interaction plot</h3>
<p>And finally we are going to need a plot. When you have two factors, you want to show both factors on the plot to give the reader as much information as possible and save on figure space. The best way to do this is through some sort of interaction plot as shown in the lab. It is really a lot easier than it looks and just requires you to think about setting the aes by the different conditions.</p>
<ul>
<li>Insert code into the <code>t5</code> code chunk below to replicate the figure shown to you
<ul>
<li>Pay particular attention to labels, axes dimensions, color and background.</li>
<li>Note that the figure must appear when your code is knitted.</li>
</ul></li>
<li><strong>Note:</strong> The figure below is a nice figure but should really have error bars on it if I was including it in an actual paper. Including the error bars may help in clarifying the descriptive statistics as you would see as although the means are different, there is huge overlap in terms of error bars.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># to do: something with ggplot to replicate the figure</span></code></pre>
<div class="figure" style="text-align: center"><span id="fig:t5-hide"></span>
<img src="13-s02-lab13d_files/figure-html/t5-hide-1.png" alt="**CAPTION THIS FIGURE!!**" width="100%" />
<p class="caption">
Figure 13.3: <strong>CAPTION THIS FIGURE!!</strong>
</p>
</div>
</div>
<div id="task-6-recap-question-1" class="section level3">
<h3><span class="header-section-number">13.4.7</span> Task 6: Recap Question 1</h3>
<p>Thinking about the above information, one of the below statements would be an acceptable hypothesis for the interaction effect of sex and condition, but which one:</p>
<ul>
<li>In the <code>t6</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t6</code></li>
</ul>
<ol style="list-style-type: decimal">
<li>We hypothesised that there will be a significant difference between males and females in egocentric interference (mean looking time (msecs)) regardless of condition.</li>
<li>We hypothesised that there will be a significant difference between participants in the false belief condition and those in the ignorance condition in terms of egocentric interference (mean looking time (msecs)) regardless of sex of participant.</li>
<li>We hypothesised that there would be a significant interaction between condition and sex of participant on egocentric interference (mean looking time (msecs))</li>
<li>We hypothesised that there will be no significant difference between males and females in egocentric interference (mean looking time (msecs)) regardless of condition but that there would be a significant difference between participants in the false belief condition and those in the ignorance condition in terms of egocentric interference (mean looking time (msecs)) regardless of sex of participant.</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r">answer_t6 &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
</div>
<div id="task-7-recap-question-2" class="section level3">
<h3><span class="header-section-number">13.4.8</span> Task 7: Recap Question 2</h3>
<p>Thinking about the above information, one of the below statements is a good description of the marginal means for sex, but which one:</p>
<ul>
<li>In the <code>t7</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t7</code></li>
</ul>
<ol style="list-style-type: decimal">
<li>The female participants have an average longer looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of sex</li>
<li>The female participants have an average shorter looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of condition</li>
<li>The female participants have an average shorter looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of sex</li>
<li>The female participants have an average longer looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of condition</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r">answer_t7 &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
</div>
<div id="task-8-recap-question-3" class="section level3">
<h3><span class="header-section-number">13.4.9</span> Task 8: Recap Question 3</h3>
<p>Thinking about the above information, one of the below statements is a good description of the marginal means for condition, but which one:</p>
<ul>
<li>In the <code>t8</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t8</code></li>
</ul>
<ol style="list-style-type: decimal">
<li>The participants in the false belief group had an average longer looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23) which may suggest a significant main effect of condition.</li>
<li>The participants in the false belief group had an average shorter looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23) which may suggest a significant main effect of condition.</li>
<li>The participants in the false belief group had an average longer looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23) which may suggest a significant main effect of sex.</li>
<li>The participants in the false belief group had an average shorter looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23) which may suggest a significant main effect of sex.</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r">answer_t8 &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
</div>
<div id="task-9-running-the-factorial-anova" class="section level3">
<h3><span class="header-section-number">13.4.10</span> Task 9: Running the factorial ANOVA</h3>
<p>Great, so we have looked at our descriptives and thought about what effects there might be. What we need to do now is run the ANOVA using the <code>ezANOVA()</code> function. The ANOVA we are going to run is a two-way between-subjects ANOVA because both conditions are between-subjects variables. You may need to refer back to the lab or to have a look at the help on <code>ezANOVA()</code> to see how to add a second variable/factor.</p>
<ul>
<li>Replace the NULL in the <code>t9</code> code chunk below to run this two-way between-subjects ANOVA.
<ul>
<li>Look at the inclass for guidance. You need the data, the dv, the two between condition, and the participant id.</li>
<li>Do not <code>tidy()</code> the output. Do nothing to the output other than store it in the variable named <code>mod</code> (note: technically it will store as a list).</li>
<li>The code will convert the condition and participant ids to factors automatically. This is fine.</li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">mod &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
</div>
<div id="task-10-interpreting-the-anova-output-question" class="section level3">
<h3><span class="header-section-number">13.4.11</span> Task 10: Interpreting the ANOVA output Question</h3>
<p>Thinking about the above information, one of the below statements is a good summary of the outcome ANOVA, but which one:</p>
<ul>
<li>In the <code>t10</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t10</code></li>
</ul>
<ol style="list-style-type: decimal">
<li>There is a significant main effect of sex, but no main effect of condition and no interaction betwen condition and sex.</li>
<li>There is a significant main effect of condition, but no main effect of sex and no interaction betwen condition and sex.</li>
<li>There is no significant main effect of sex or condition and there is no significant interaction between condition and sex.</li>
<li>There is a significant main effect of sex, a significant main effect of condition, and a significant interaction between condition and sex</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r">answer_t10 &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
</div>
<div id="task-11-report-your-results" class="section level3">
<h3><span class="header-section-number">13.4.12</span> Task 11: Report your results</h3>
<p>Write a paragraph reporting your findings. <em>NOTE:</em> You can use inline code to report the <span class="math inline">\(F\)</span> values, but note that you cannot use <code>broom::tidy()</code> for objects created by <code>ezANOVA()</code>. Here is a hint: <code>mod$ANOVA</code> gives you a table of your results (<code>ezANOVA()</code> returns a list with two elements; <code>mod$ANOVA</code> returns the element of the list called <code>ANOVA</code> that has the results). You can <code>pull()</code> and <code>pluck()</code> whatever you need from this table.</p>
<!-- start of results: don't delete this line -->
<p>Write your summary between the two green lines shown in the GUID file.</p>
<!-- end of results: don't delete this line -->
<p><strong>Finished</strong></p>
<p>Well done, you are finshed! Now you should go check your answers against the solution file which can be found on Moodle. You are looking to check that the resulting output from the answers that you have submitted are exactly the same as the output in the solution - for example, remember that a single value is not the same as a coded answer. Where there are alternative answers it means that you could have submitted any one of the options as they should all return the same answer. If you have any questions please post them on the moodle forum or on the &lt;a href = “<a href="https://rguppies.slack.com" class="uri">https://rguppies.slack.com</a>”, target = &quot;_blank&quot;&gt;rguppies.slack.com</a> forum <strong>#level2_2018</strong>.</p>
<p>See you in the next lab!</p>

</div>
</div>
<div id="solutions-to-questions-12" class="section level2">
<h2><span class="header-section-number">13.5</span> Solutions to Questions</h2>
<p>Below you will find the solutions to the questions for the Activities for this chapter. Only look at them after giving the questions a good try and speaking to the tutor about any issues.</p>
<div id="inclass-activities-9" class="section level3">
<h3><span class="header-section-number">13.5.1</span> InClass Activities</h3>
<div id="decomp-matrix-code" class="section level4">
<h4><span class="header-section-number">13.5.1.1</span> Decomp Matrix Code</h4>
<pre><code>decomp &lt;- tibble(i = rep(1:2, each = 6),
                 j = rep(rep(1:2, each = 3), times = 2),
                 k = rep(1:3, times = 4),
                 Y_ijk = c(74, 65, 77, 70, 74, 66, 67, 67, 64, 78, 78, 84)) %&gt;%
    mutate(mu = mean(Y_ijk)) %&gt;% # calculate mu
    group_by(i) %&gt;% 
    mutate(A_i = mean(Y_ijk) - mu) %&gt;% # calculate A_i
    group_by(j) %&gt;% 
    mutate(B_j = mean(Y_ijk) - mu) %&gt;% # calculate B_j
    ungroup()</code></pre>
</div>
<div id="to-add-the-last-columns" class="section level4">
<h4><span class="header-section-number">13.5.1.2</span> To Add the last columns</h4>
<pre class="sourceCode r"><code class="sourceCode r">decomp2 &lt;-<span class="st"> </span>decomp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(i, j) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">AB_ij =</span> <span class="kw">mean</span>(Y_ijk) <span class="op">-</span><span class="st"> </span>mu <span class="op">-</span><span class="st"> </span>A_i <span class="op">-</span><span class="st"> </span>B_j) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">err =</span> Y_ijk <span class="op">-</span><span class="st"> </span>mu <span class="op">-</span><span class="st"> </span>A_i <span class="op">-</span><span class="st"> </span>B_j <span class="op">-</span><span class="st"> </span>AB_ij)</code></pre>
</div>
<div id="understanding-the-two-factor-decomposition-matrix-1" class="section level4">
<h4><span class="header-section-number">13.5.1.3</span> Understanding the two-factor decomposition matrix</h4>
<div id="q1" class="section level5">
<h5><span class="header-section-number">13.5.1.3.1</span> Q1</h5>
<p>The DV value of participant <span class="math inline">\(Y_{212}\)</span> or the 2nd Participant in <span class="math inline">\(I_2\)</span>, <span class="math inline">\(J_1\)</span>, is 67</p>
</div>
<div id="q2" class="section level5">
<h5><span class="header-section-number">13.5.1.3.2</span> Q2</h5>
<p>The Sums of Squares of Factor B is 108</p>
</div>
<div id="q3" class="section level5">
<h5><span class="header-section-number">13.5.1.3.3</span> Q3</h5>
<p>The Sums of Squares of the Error is 140</p>
</div>
<div id="q4" class="section level5">
<h5><span class="header-section-number">13.5.1.3.4</span> Q4</h5>
<p>The <span class="math inline">\(MS_{B}\)</span> is 108</p>
</div>
<div id="q5" class="section level5">
<h5><span class="header-section-number">13.5.1.3.5</span> Q5</h5>
<p>The <span class="math inline">\(MS_{error}\)</span> (to one decimal places) is 17.5</p>
</div>
<div id="q6" class="section level5">
<h5><span class="header-section-number">13.5.1.3.6</span> Q6</h5>
<p>The F-ratio for the main effect of B to 3 decimal places is 6.171</p>
</div>
<div id="q7" class="section level5">
<h5><span class="header-section-number">13.5.1.3.7</span> Q7</h5>
<p>The numerator and denominator degrees of freedom associated with this <span class="math inline">\(F\)</span> ratio are 1 and 8 respectively</p>
</div>
<div id="q8" class="section level5">
<h5><span class="header-section-number">13.5.1.3.8</span> Q8</h5>
<p>And based on <code>pf(fratio, 1,</code>8<code>, lower.tail = FALSE)</code> the <span class="math inline">\(p\)</span>-value associated with this F ratio to three decimal places is 0.038 or .038</p>
</div>
</div>
<div id="table-converter-code" class="section level4">
<h4><span class="header-section-number">13.5.1.4</span> Table converter code</h4>
<pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span>decomp <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">A =</span> <span class="kw">paste0</span>(<span class="st">&quot;A&quot;</span>, i),
         <span class="dt">B =</span> <span class="kw">paste0</span>(<span class="st">&quot;B&quot;</span>, j),
         <span class="dt">id =</span> <span class="kw">row_number</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(id, A, B, Y_ijk)</code></pre>
</div>
<div id="visualizing-2x2-designs-in-r-the-interaction-plot-1" class="section level4">
<h4><span class="header-section-number">13.5.1.5</span> Visualizing 2x2 designs in R: The interaction plot</h4>
<div id="cell-means" class="section level5">
<h5><span class="header-section-number">13.5.1.5.1</span> Cell means</h5>
<pre class="sourceCode r"><code class="sourceCode r">cell_means &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(A, B) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y_ijk))

cell_means</code></pre>
<pre><code>## # A tibble: 4 x 3
## # Groups:   A [2]
##   A     B         m
##   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;
## 1 A1    B1       72
## 2 A1    B2       70
## 3 A2    B1       66
## 4 A2    B2       80</code></pre>
</div>
<div id="the-plot" class="section level5">
<h5><span class="header-section-number">13.5.1.5.2</span> The Plot</h5>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(cell_means, <span class="kw">aes</span>(A, m, <span class="dt">group =</span> B, <span class="dt">shape =</span> B, <span class="dt">color =</span> B)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-8"></span>
<img src="13-s02-lab13e_files/figure-html/unnamed-chunk-8-1.png" alt="**CAPTION THIS FIGURE!!**" width="100%" />
<p class="caption">
Figure 6.3: <strong>CAPTION THIS FIGURE!!</strong>
</p>
</div>
</div>
<div id="easter-egg-figure-solution" class="section level5">
<h5><span class="header-section-number">13.5.1.5.3</span> Easter Egg Figure Solution</h5>
<p>The plot above is functional but sometimes you want something a bit more communicative. It is worth working on your figures so here is an example that you can think about for your report. Remember to look back through previous labs and homework as well (Semester 1: Lab 3, Lab 7, Lab 6, Lab 5 &amp; 9 assignments, for instance) to see how figures can be improved.</p>
<p>The code below adds another few dimensions to the above figure. Copy and run the code in your Rmd, knitting it to HTML, and play with the different parts to see what they do. We have changed the legends to be more descriptive and to have more readable text, fixed the scale for the vertical axis, made the figure black and white without a box, we also added 95% confidence intervals and a figure caption.
There are of course various ways to do these changes, in particular the caption, but this is an option.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Will only run if you have the tibble dat from earlier in this worksheet</span>
cell_means1 &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span>
<span class="kw">group_by</span>(A, B) <span class="op">%&gt;%</span>
<span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y_ijk),
          <span class="dt">n =</span> <span class="kw">n</span>(),
          <span class="dt">sd_scores =</span> <span class="kw">sd</span>(Y_ijk),
          <span class="dt">ste_scores =</span> sd_scores<span class="op">/</span><span class="kw">sqrt</span>(n),
          <span class="dt">ci =</span> <span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>ste_scores)
  
<span class="kw">ggplot</span>(cell_means1, <span class="kw">aes</span>(A, m, <span class="dt">group =</span> B)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">shape =</span> B), <span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> m <span class="op">-</span><span class="st"> </span>ci, <span class="dt">ymax =</span> m <span class="op">+</span><span class="st"> </span>ci), 
                <span class="dt">width =</span> <span class="fl">0.05</span>, 
                <span class="dt">size =</span> <span class="fl">.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">100</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Groups in Factor A&quot;</span>, 
       <span class="dt">y =</span> <span class="st">&quot;Mean Scores&quot;</span>, 
       <span class="dt">caption =</span> <span class="st">&quot;Figure 1. Mean scores from the example data for the two-way </span><span class="ch">\n</span><span class="st">between-subjects design ANOVA. Error bars indicate 95% </span><span class="ch">\n</span><span class="st">confidence intervals.&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_shape_discrete</span>(<span class="st">&quot;Groups in Factor B&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>),
        <span class="dt">axis.text.y =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">12</span>),
        <span class="dt">axis.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">14</span>),
        <span class="dt">legend.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">14</span>),
        <span class="dt">legend.text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">14</span>),
        <span class="dt">plot.caption  =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">14</span>, <span class="dt">hjust =</span> <span class="dv">0</span>))</code></pre>
<div class="figure" style="text-align: center"><span id="fig:easter-figure"></span>
<img src="13-s02-lab13e_files/figure-html/easter-figure-1.png" alt="**CAPTION THIS FIGURE!!**" width="100%" />
<p class="caption">
Figure 13.4: <strong>CAPTION THIS FIGURE!!</strong>
</p>
</div>
</div>
</div>
<div id="anova-using-ez" class="section level4">
<h4><span class="header-section-number">13.5.1.6</span> ANOVA Using Ez</h4>
<p><strong>The code</strong></p>
<pre class="sourceCode r"><code class="sourceCode r">result &lt;-<span class="st"> </span><span class="kw">ezANOVA</span>(dat, 
                  <span class="dt">dv =</span> Y_ijk, 
                  <span class="dt">wid =</span> id, 
                  <span class="dt">between =</span> .(A, B),
                  <span class="dt">detailed =</span> <span class="ot">TRUE</span>) <span class="co"># This gives sum squares information</span></code></pre>
<pre><code>## Coefficient covariances computed by hccm()</code></pre>
<p><strong>The output</strong></p>
<pre class="sourceCode r"><code class="sourceCode r">result<span class="op">$</span>ANOVA</code></pre>
<pre><code>##   Effect DFn DFd SSn SSd          F          p p&lt;.05        ges
## 1      A   1   8  12 140  0.6857143 0.43163404       0.07894737
## 2      B   1   8 108 140  6.1714286 0.03786084     * 0.43548387
## 3    A:B   1   8 192 140 10.9714286 0.01066139     * 0.57831325</code></pre>
</div>
</div>
<div id="homework-activities-2" class="section level3">
<h3><span class="header-section-number">13.5.2</span> Homework Activities</h3>
<div id="task-1a-libraries-3" class="section level4">
<h4><span class="header-section-number">13.5.2.1</span> Task 1A: Libraries</h4>
<ul>
<li>In today’s assignment you will need both the <code>tidyverse</code> and <code>ez</code> packages. Enter code into the t1A code chunk below to load in both of these libraries.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ez)
<span class="kw">library</span>(tidyverse)</code></pre>
</div>
<div id="task-1b-loading-in-the-data-3" class="section level4">
<h4><span class="header-section-number">13.5.2.2</span> Task 1B: Loading in the data</h4>
<ul>
<li>Use <code>read_csv()</code> to replace the <code>NULL</code> in the t1B code chunk below to load in the data stored in the datafile <code>keysar_lin_barr_2003.csv</code>. Store the data in the variable <code>dat</code>. Do not change the filename of the datafile.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;keysar_lin_barr_2003.csv&quot;</span>)</code></pre>
<p>Take a look at your data (<code>dat</code>) in the console using <code>glimpse()</code> or <code>View()</code>, or just display it by typing in the name. You will see the following columns:</p>
<table>
<thead>
<tr class="header">
<th>variable</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>subject</code></td>
<td>unique identifier for each subject</td>
</tr>
<tr class="even">
<td><code>sex</code></td>
<td>whether the subject was male or female</td>
</tr>
<tr class="odd">
<td><code>condition</code></td>
<td>what condition the subject was in</td>
</tr>
<tr class="even">
<td><code>looktime</code></td>
<td>egocentric interference</td>
</tr>
</tbody>
</table>
<p>We have simplified things from the original experiment by collapsing the baseline vs. experimental conditions into a single DV. Our DV, egocentric interference, is the average difference in looking time for each subject (in milliseconds per trial) for hidden competitors (e.g., small candle) versus hidden noncompetitors (e.g., apple). The larger this number, the more egocentric interference the subject experienced.</p>
</div>
<div id="task-2-calculate-cell-means-1" class="section level4">
<h4><span class="header-section-number">13.5.2.3</span> Task 2: Calculate cell means</h4>
<p>Today we are going to focus on just the main analysis and write-up, and not the assumptions, but as always before running any analysis you should check that your assumptions hold.</p>
<p>One of the elements we will need for our write-up is some descriptives. We want to start by creating some summary statistics for the four conditions. Remember, two factors (sex, condition) with 2 levels each (sex: female vs male; condition: false belief vs ignorance) will give four conditions, and as such in our summary table, four cells created by factorially combining sex and condition.</p>
<ul>
<li>Replace the NULL in the <code>t2</code> code chunk below to create the four cells created by factorially combining sex and condition, summarising the mean and standard deviation for each cell.
<ul>
<li>Store the descriptives in the tibble <code>cell_means</code></li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have four rows and four columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">cell_means &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(sex, condition) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(looktime), <span class="dt">sd =</span> <span class="kw">sd</span>(looktime))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">sex</th>
<th align="left">condition</th>
<th align="right">m</th>
<th align="right">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="left">false belief</td>
<td align="right">594.5833</td>
<td align="right">899.1660</td>
</tr>
<tr class="even">
<td align="left">female</td>
<td align="left">ignorance</td>
<td align="right">944.6970</td>
<td align="right">932.6990</td>
</tr>
<tr class="odd">
<td align="left">male</td>
<td align="left">false belief</td>
<td align="right">504.5833</td>
<td align="right">676.7338</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="left">ignorance</td>
<td align="right">611.1111</td>
<td align="right">778.0212</td>
</tr>
</tbody>
</table>
</div>
<div id="task-3-marginal-means-for-sex-1" class="section level4">
<h4><span class="header-section-number">13.5.2.4</span> Task 3: Marginal means for sex</h4>
<p>We will also need to have some descriptives where we just look at the means of a given factor; the marginal means - the means of the levels of one factor regardless of the other factor.</p>
<ul>
<li>Replace the NULL in the <code>t3</code> code chunk below to calculate the marginal means and standard deviations for the factor, sex.
<ul>
<li>Store these descriptives in the tibble <code>marg_sex</code></li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have two rows and three columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">marg_sex &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(looktime), <span class="dt">sd =</span> <span class="kw">sd</span>(looktime))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">sex</th>
<th align="right">m</th>
<th align="right">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="right">777.9762</td>
<td align="right">911.5331</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="right">555.0439</td>
<td align="right">707.8138</td>
</tr>
</tbody>
</table>
</div>
<div id="task-4-marginal-means-for-condition-1" class="section level4">
<h4><span class="header-section-number">13.5.2.5</span> Task 4: Marginal means for condition</h4>
<p>And now do the same for condition.</p>
<ul>
<li>Replace the NULL in the <code>t4</code> code chunk below to calculate the marginal means and standard deviations for the factor, condition
<ul>
<li>Store these descriptives in the tibble <code>marg_cond</code></li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have two rows and three columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">marg_cond &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(condition) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(looktime), <span class="dt">sd =</span> <span class="kw">sd</span>(looktime))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">condition</th>
<th align="right">m</th>
<th align="right">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">false belief</td>
<td align="right">549.5833</td>
<td align="right">775.9108</td>
</tr>
<tr class="even">
<td align="left">ignorance</td>
<td align="right">794.5833</td>
<td align="right">861.2306</td>
</tr>
</tbody>
</table>
</div>
<div id="task-5-interaction-plot-1" class="section level4">
<h4><span class="header-section-number">13.5.2.6</span> Task 5: Interaction plot</h4>
<p>And finally we are going to need a plot. When you have two factors, you want to show both factors on the plot to give the reader as much information as possible and save on figure space. The best way to do this is through some sort of interaction plot as shown in the lab. It is really a lot easier than it looks and just requires you to think about setting the aes by the different conditions.</p>
<ul>
<li>Insert code into the <code>t5</code> code chunk below to replicate the figure shown to you
<ul>
<li>Pay particular attention to labels, axes dimensions, color and background.</li>
<li>Note that the figure must appear when your code is knitted.</li>
</ul></li>
<li><strong>Note:</strong> The figure below is a nice figure but should really have error bars on it if I was including it in an actual paper. Including the error bars may help in clarifying the descriptive statistics as you would see as although the means are different, there is huge overlap in terms of error bars.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># to do: something with ggplot to replicate the figure</span>
<span class="kw">ggplot</span>(cell_means, <span class="kw">aes</span>(condition, m, <span class="dt">shape =</span> sex, <span class="dt">group =</span> sex, <span class="dt">color =</span> sex)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;mean looking time (msecs)&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1000</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:t5"></span>
<img src="13-s02-lab13e_files/figure-html/t5-1.png" alt="**CAPTION THIS FIGURE!!**" width="100%" />
<p class="caption">
Figure 13.5: <strong>CAPTION THIS FIGURE!!</strong>
</p>
</div>
</div>
<div id="task-6-recap-question-1-1" class="section level4">
<h4><span class="header-section-number">13.5.2.7</span> Task 6: Recap Question 1</h4>
<p>Thinking about the above information, one of the below statements would be an acceptable hypothesis for the interaction effect of sex and condition, but which one:</p>
<ul>
<li>In the <code>t6</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t6</code></li>
</ul>
<ol style="list-style-type: decimal">
<li>We hypothesised that there will be a significant difference between males and females in egocentric interference (mean looking time (msecs)) regardless of condition.</li>
<li>We hypothesised that there will be a significant difference between participants in the false belief condition and those in the ignorance condition in terms of egocentric interference (mean looking time (msecs)) regardless of sex of participant.</li>
<li>We hypothesised that there would be a significant interaction between condition and sex of participant on egocentric interference (mean looking time (msecs))</li>
<li>We hypothesised that there will be no significant difference between males and females in egocentric interference (mean looking time (msecs)) regardless of condition but that there would be a significant difference between participants in the false belief condition and those in the ignorance condition in terms of egocentric interference (mean looking time (msecs)) regardless of sex of participant.</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r">answer_t6 &lt;-<span class="st"> </span><span class="dv">3</span></code></pre>
</div>
<div id="task-7-recap-question-2-1" class="section level4">
<h4><span class="header-section-number">13.5.2.8</span> Task 7: Recap Question 2</h4>
<p>Thinking about the above information, one of the below statements is a good description of the marginal means for sex, but which one:</p>
<ul>
<li>In the <code>t7</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t7</code></li>
</ul>
<ol style="list-style-type: decimal">
<li>The female participants have an average longer looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of sex</li>
<li>The female participants have an average shorter looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of condition</li>
<li>The female participants have an average shorter looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of sex</li>
<li>The female participants have an average longer looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of condition</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r">answer_t7 &lt;-<span class="st"> </span><span class="dv">1</span></code></pre>
</div>
<div id="task-8-recap-question-3-1" class="section level4">
<h4><span class="header-section-number">13.5.2.9</span> Task 8: Recap Question 3</h4>
<p>Thinking about the above information, one of the below statements is a good description of the marginal means for condition, but which one:</p>
<ul>
<li>In the <code>t8</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t8</code></li>
</ul>
<ol style="list-style-type: decimal">
<li>The participants in the false belief group had an average longer looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23) which may suggest a significant main effect of condition.</li>
<li>The participants in the false belief group had an average shorter looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23) which may suggest a significant main effect of condition.</li>
<li>The participants in the false belief group had an average longer looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23) which may suggest a significant main effect of sex.</li>
<li>The participants in the false belief group had an average shorter looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23) which may suggest a significant main effect of sex.</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r">answer_t8 &lt;-<span class="st"> </span><span class="dv">2</span></code></pre>
</div>
<div id="task-9-running-the-factorial-anova-1" class="section level4">
<h4><span class="header-section-number">13.5.2.10</span> Task 9: Running the factorial ANOVA</h4>
<p>Great, so we have looked at our descriptives and thought about what effects there might be. What we need to do now is run the ANOVA using the <code>ezANOVA()</code> function. The ANOVA we are going to run is a two-way between-subjects ANOVA because both conditions are between-subjects variables. You may need to refer back to the lab or to have a look at the help on <code>ezANOVA()</code> to see how to add a second variable/factor.</p>
<ul>
<li>Replace the NULL in the <code>t9</code> code chunk below to run this two-way between-subjects ANOVA.
<ul>
<li>Look at the inclass for guidance. You need the data, the dv, the two between condition, and the participant id.</li>
<li>Do not <code>tidy()</code> the output. Do nothing to the output other than store it in the variable named <code>mod</code> (note: technically it will store as a list).</li>
<li>The code will convert the condition and participant ids to factors automatically. This is fine.</li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">mod &lt;-<span class="st"> </span><span class="kw">ezANOVA</span>(dat, <span class="dt">dv =</span> looktime, <span class="dt">wid =</span> subject,
               <span class="dt">between =</span> .(condition, sex))

mod<span class="op">$</span>ANOVA</code></pre>
<pre><code>##          Effect DFn DFd         F         p p&lt;.05         ges
## 1     condition   1  36 0.7913759 0.3795907       0.021509820
## 2           sex   1  36 0.6405277 0.4287699       0.017481399
## 3 condition:sex   1  36 0.2130405 0.6471716       0.005882978</code></pre>
</div>
<div id="task-10-interpreting-the-anova-output-question-1" class="section level4">
<h4><span class="header-section-number">13.5.2.11</span> Task 10: Interpreting the ANOVA output Question</h4>
<p>Thinking about the above information, one of the below statements is a good summary of the outcome ANOVA, but which one:</p>
<ul>
<li>In the <code>t10</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t10</code></li>
</ul>
<ol style="list-style-type: decimal">
<li>There is a significant main effect of sex, but no main effect of condition and no interaction betwen condition and sex.</li>
<li>There is a significant main effect of condition, but no main effect of sex and no interaction betwen condition and sex.</li>
<li>There is no significant main effect of sex or condition and there is no significant interaction between condition and sex.</li>
<li>There is a significant main effect of sex, a significant main effect of condition, and a significant interaction between condition and sex</li>
</ol>
<pre class="sourceCode r"><code class="sourceCode r">answer_t10 &lt;-<span class="st"> </span><span class="dv">3</span></code></pre>
</div>
<div id="task-11-report-your-results-1" class="section level4">
<h4><span class="header-section-number">13.5.2.12</span> Task 11: Report your results</h4>
<p>Write a paragraph reporting your findings. <em>NOTE:</em> You can use inline code to report the <span class="math inline">\(F\)</span> values, but note that you cannot use <code>broom::tidy()</code> for objects created by <code>ezANOVA()</code>. Here is a hint: <code>mod$ANOVA</code> gives you a table of your results (<code>ezANOVA()</code> returns a list with two elements; <code>mod$ANOVA</code> returns the element of the list called <code>ANOVA</code> that has the results). You can <code>pull()</code> and <code>pluck()</code> whatever you need from this table.</p>
<!-- start of results: don't delete this line -->
<p>There is no definitive way to write this paragraph but essentially your findings should report both main effects and the interaction, giving appropriate F outputs, e.g. F(1, 36) = .79, p = .38, and give some interpretation/qualification of the results using the means and standard deviations above, e.g. looking time was not significantly different between the false belief task (M = X, SD = XX) or the Ignorance task (M = XX, SD = XX). Something along the following would be appropriate:</p>
<p><strong>A two-way between-subjects factorial ANOVA was conducted testing the main effects and interaction between sex(Male vs Female) and condition (false belief vs ignorance) on the average looking time (msecs) on a matching task. Results revealed no significant interaction (F(1, 36) = .21, p = .647) suggesting that there is no modulation of condition by sex of participant in this looking task. Furthermore there was no significant main effect of sex (F(1, 36) = .64, p = .429) suggesting that male (M = 555.04, SD = 707.81) and female participants (M = 777.98, SD = 911.53) perform similarly in this task. Finally, there was no significant main effect of condition (F(1, 36) = .79, p = .38) suggesting that whether participants were given a false belief scenario (M = 594.58, SD = 775.91) or an ignorance scenario (M = 794.58, SD = 861.23) had no overall impact on their performance.</strong></p>
<!-- end of results: don't delete this line -->
<p><strong>Finished</strong></p>
<p>Well done, you are finshed! Now you should go check your answers against the solution file which can be found on Moodle. You are looking to check that the resulting output from the answers that you have submitted are exactly the same as the output in the solution - for example, remember that a single value is not the same as a coded answer. Where there are alternative answers it means that you could have submitted any one of the options as they should all return the same answer. If you have any questions please post them on the moodle forum or on the &lt;a href = “<a href="https://rguppies.slack.com" class="uri">https://rguppies.slack.com</a>”, target = &quot;_blank&quot;&gt;rguppies.slack.com</a> forum <strong>#level2_2018</strong>.</p>
<p>See you in the next lab!</p>

</div>
</div>
</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="continuing-the-glm-one-factor-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
