<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lab 5 Permutation Tests - A Skill Set | Level 2 Research Methods and Statistics Practical Skills</title>
  <meta name="description" content="ug2-practical-materials" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Lab 5 Permutation Tests - A Skill Set | Level 2 Research Methods and Statistics Practical Skills" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="ug2-practical-materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lab 5 Permutation Tests - A Skill Set | Level 2 Research Methods and Statistics Practical Skills" />
  
  <meta name="twitter:description" content="ug2-practical-materials" />
  



<meta name="date" content="2020-06-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="revisiting-probability-distributions.html"/>
<link rel="next" href="nhst-and-one-sample-t-tests.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include\psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Level 2 Practical</a></li>
<li><a href="https://zenodo.org/badge/latestdoi/166541567"><img src="https://zenodo.org/badge/166541567.svg" alt="DOI"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html"><i class="fa fa-check"></i><b>1</b> Starting with R Markdown</a><ul>
<li class="chapter" data-level="1.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#overview-1"><i class="fa fa-check"></i><b>1.1</b> Overview</a><ul>
<li class="chapter" data-level="1.1.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#what-is-r-markdown"><i class="fa fa-check"></i><b>1.1.1</b> What is R Markdown?</a></li>
<li class="chapter" data-level="1.1.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#advantages-of-using-r-markdown"><i class="fa fa-check"></i><b>1.1.2</b> Advantages of using R Markdown</a></li>
<li class="chapter" data-level="1.1.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#creating-an-r-markdown-.rmd-file"><i class="fa fa-check"></i><b>1.1.3</b> Creating an R Markdown (.Rmd) File</a></li>
<li class="chapter" data-level="1.1.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#one-last-thing-before-beginning"><i class="fa fa-check"></i><b>1.1.4</b> One last thing before beginning!</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#preclass-activiy"><i class="fa fa-check"></i><b>1.2</b> PreClass Activiy</a><ul>
<li class="chapter" data-level="1.2.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#lets-begin"><i class="fa fa-check"></i><b>1.2.1</b> Let’s Begin</a></li>
<li class="chapter" data-level="1.2.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#code-chunks"><i class="fa fa-check"></i><b>1.2.2</b> Code Chunks</a></li>
<li class="chapter" data-level="1.2.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#knitting-code"><i class="fa fa-check"></i><b>1.2.3</b> Knitting Code</a></li>
<li class="chapter" data-level="1.2.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#adding-code-chunk-rules-and-options"><i class="fa fa-check"></i><b>1.2.4</b> Adding Code Chunk Rules and Options</a></li>
<li class="chapter" data-level="1.2.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#adding-inline-code"><i class="fa fa-check"></i><b>1.2.5</b> Adding Inline Code</a></li>
<li class="chapter" data-level="1.2.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#formatting-the-r-markdown-file"><i class="fa fa-check"></i><b>1.2.6</b> Formatting the R Markdown File</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-activiy"><i class="fa fa-check"></i><b>1.3</b> InClass Activiy</a><ul>
<li class="chapter" data-level="1.3.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#r-markdown-and-the-experimental-design-portfolio"><i class="fa fa-check"></i><b>1.3.1</b> R Markdown and The Experimental Design Portfolio</a></li>
<li class="chapter" data-level="1.3.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#the-ponzo-illusion-and-age"><i class="fa fa-check"></i><b>1.3.2</b> The Ponzo Illusion and Age</a></li>
<li class="chapter" data-level="1.3.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT1"><i class="fa fa-check"></i><b>1.3.3</b> Task 1: Setting up Your R Markdown Portfolio</a></li>
<li class="chapter" data-level="1.3.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT2"><i class="fa fa-check"></i><b>1.3.4</b> Task 2: Give your Report a Heading</a></li>
<li class="chapter" data-level="1.3.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT3"><i class="fa fa-check"></i><b>1.3.5</b> Task 3: Creating a Code Chunk</a></li>
<li class="chapter" data-level="1.3.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT4"><i class="fa fa-check"></i><b>1.3.6</b> Task 4: Writing your Report</a></li>
<li class="chapter" data-level="1.3.7" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT5"><i class="fa fa-check"></i><b>1.3.7</b> Task 5: Making Text Bold or Italicized</a></li>
<li class="chapter" data-level="1.3.8" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT6"><i class="fa fa-check"></i><b>1.3.8</b> Task 6: Adding Links to the Data in your Methods</a></li>
<li class="chapter" data-level="1.3.9" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT7"><i class="fa fa-check"></i><b>1.3.9</b> Task 7: Adding an Image to your Methods</a></li>
<li class="chapter" data-level="1.3.10" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT8"><i class="fa fa-check"></i><b>1.3.10</b> Task 8: Adding a Table to your Results</a></li>
<li class="chapter" data-level="1.3.11" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT9"><i class="fa fa-check"></i><b>1.3.11</b> Task 9: Adding a Figure to your Results</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#assignment"><i class="fa fa-check"></i><b>1.4</b> Assignment</a></li>
<li class="chapter" data-level="1.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#solutions-to-questions"><i class="fa fa-check"></i><b>1.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="1.5.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-activities"><i class="fa fa-check"></i><b>1.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-comparison"><i class="fa fa-check"></i><b>1.6</b> InClass Comparison</a><ul>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#lab-1---the-magnitude-of-the-ponzo-illusion-varies-as-a-function-of-age"><i class="fa fa-check"></i>Lab 1 - The Magnitude of the Ponzo Illusion varies as a function of Age</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#methods"><i class="fa fa-check"></i>Methods</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#results"><i class="fa fa-check"></i>Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html"><i class="fa fa-check"></i><b>2</b> Data-Wrangling: A Key Skill</a><ul>
<li class="chapter" data-level="2.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#overview-2"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#preclass-activity"><i class="fa fa-check"></i><b>2.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#revisiting-the-wickham-six"><i class="fa fa-check"></i><b>2.2.1</b> Revisiting the Wickham Six</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#learning-to-wrangle-is-there-a-chastity-belt-on-perception"><i class="fa fa-check"></i><b>2.2.2</b> Learning to Wrangle: Is there a Chastity Belt on Perception</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT1"><i class="fa fa-check"></i><b>2.2.3</b> The <strong><code>select()</code></strong> Function - to keep only specific columns</a></li>
<li class="chapter" data-level="2.2.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT2"><i class="fa fa-check"></i><b>2.2.4</b> The <strong><code>arrange()</code></strong> Function - to sort and arrange columns</a></li>
<li class="chapter" data-level="2.2.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT3"><i class="fa fa-check"></i><b>2.2.5</b> The <strong><code>filter()</code></strong> Function - to keep only parts of the data</a></li>
<li class="chapter" data-level="2.2.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT4"><i class="fa fa-check"></i><b>2.2.6</b> The <strong><code>mutate()</code></strong> Function - for adding new columns</a></li>
<li class="chapter" data-level="2.2.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT5"><i class="fa fa-check"></i><b>2.2.7</b> The <strong><code>group_by()</code></strong> Function - to group parts of data altogether</a></li>
<li class="chapter" data-level="2.2.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT6"><i class="fa fa-check"></i><b>2.2.8</b> The <strong><code>summarise()</code></strong> Function - to do some calculations on the data</a></li>
<li class="chapter" data-level="2.2.9" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#two-other-useful-functions"><i class="fa fa-check"></i><b>2.2.9</b> Two Other Useful Functions</a></li>
<li class="chapter" data-level="2.2.10" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#last-but-not-least---pipes-to-make-your-code-efficient"><i class="fa fa-check"></i><b>2.2.10</b> Last but not least - Pipes (<strong><code>%&gt;%</code></strong>) to make your code efficient</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#inclass-activity"><i class="fa fa-check"></i><b>2.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#task-1-open-a-script"><i class="fa fa-check"></i><b>2.3.1</b> Task 1: Open a Script</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT2"><i class="fa fa-check"></i><b>2.3.2</b> Task 2: Bring in Your Library</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT3"><i class="fa fa-check"></i><b>2.3.3</b> Task 3: Load in the Data</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT4"><i class="fa fa-check"></i><b>2.3.4</b> Task 4: Review Your Data.</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT5"><i class="fa fa-check"></i><b>2.3.5</b> Task 5: Gathering Data.</a></li>
<li class="chapter" data-level="2.3.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT6"><i class="fa fa-check"></i><b>2.3.6</b> Task 6: Combining Data.</a></li>
<li class="chapter" data-level="2.3.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT7"><i class="fa fa-check"></i><b>2.3.7</b> Task 7: Calculating the AQ Scores.</a></li>
<li class="chapter" data-level="2.3.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT8"><i class="fa fa-check"></i><b>2.3.8</b> Task 8: One Last Thing on Pipes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#assignment-1"><i class="fa fa-check"></i><b>2.4</b> Assignment</a><ul>
<li class="chapter" data-level="2.4.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#todays-topic---the-ageing-brain"><i class="fa fa-check"></i><b>2.4.1</b> Today’s Topic - The Ageing Brain</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#load-in-the-data"><i class="fa fa-check"></i><b>2.4.2</b> Load in the data</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT1"><i class="fa fa-check"></i><b>2.4.3</b> Task 1 - Oldest Participant</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT2"><i class="fa fa-check"></i><b>2.4.4</b> Task 2 - Arranging D-SPAN</a></li>
<li class="chapter" data-level="2.4.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT3"><i class="fa fa-check"></i><b>2.4.5</b> Task 3 - Foreign Language Speakers</a></li>
<li class="chapter" data-level="2.4.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT4"><i class="fa fa-check"></i><b>2.4.6</b> Task 4 - Creating Percentage MOCA scores</a></li>
<li class="chapter" data-level="2.4.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT5"><i class="fa fa-check"></i><b>2.4.7</b> Task 5 - Remove the MOCA column</a></li>
<li class="chapter" data-level="2.4.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT6"><i class="fa fa-check"></i><b>2.4.8</b> Task 6 - Gather the Responses together</a></li>
<li class="chapter" data-level="2.4.9" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT7"><i class="fa fa-check"></i><b>2.4.9</b> Task 7 - Joining the data</a></li>
<li class="chapter" data-level="2.4.10" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT8"><i class="fa fa-check"></i><b>2.4.10</b> Task 8 - Working the Pipes</a></li>
<li class="chapter" data-level="2.4.11" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT9"><i class="fa fa-check"></i><b>2.4.11</b> Task 9 - Difference in Musical Means</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#solutions-to-questions-1"><i class="fa fa-check"></i><b>2.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="2.5.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#preclass-activities"><i class="fa fa-check"></i><b>2.5.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="2.5.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#inclass-actitivies"><i class="fa fa-check"></i><b>2.5.2</b> InClass Actitivies</a></li>
<li class="chapter" data-level="2.5.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#assignment-solution"><i class="fa fa-check"></i><b>2.5.3</b> Assignment Solution</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#additional-material"><i class="fa fa-check"></i><b>2.6</b> Additional Material</a><ul>
<li class="chapter" data-level="" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#more-on-read_csv"><i class="fa fa-check"></i>More on read_csv()</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#more-on-code-layout"><i class="fa fa-check"></i>More on Code Layout</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html"><i class="fa fa-check"></i><b>3</b> Visualisation Through <strong><code>ggplot2</code></strong></a><ul>
<li class="chapter" data-level="3.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#overview-3"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#preclass-activity-1"><i class="fa fa-check"></i><b>3.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="3.2.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#scatterplots---geom_point"><i class="fa fa-check"></i><b>3.2.1</b> Scatterplots - <code>geom_point()</code></a></li>
<li class="chapter" data-level="3.2.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#histograms---geom_histogram"><i class="fa fa-check"></i><b>3.2.2</b> Histograms - geom_histogram()</a></li>
<li class="chapter" data-level="3.2.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#boxplots---geom_boxplot"><i class="fa fa-check"></i><b>3.2.3</b> Boxplots - geom_boxplot()</a></li>
<li class="chapter" data-level="3.2.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#barplots---geom_bar-or-geom_col"><i class="fa fa-check"></i><b>3.2.4</b> Barplots - geom_bar() or geom_col()</a></li>
<li class="chapter" data-level="3.2.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#themes-labels-guides-and-facet_wraps"><i class="fa fa-check"></i><b>3.2.5</b> Themes, Labels, Guides, and <strong><code>facet_wraps()</code></strong></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#inclass-activity-1"><i class="fa fa-check"></i><b>3.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="3.3.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#mental-rotation-angle-and-reaction-time"><i class="fa fa-check"></i><b>3.3.1</b> Mental Rotation: Angle and Reaction Time</a></li>
<li class="chapter" data-level="3.3.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT1"><i class="fa fa-check"></i><b>3.3.2</b> Task 1: Loading and Viewing the Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT2"><i class="fa fa-check"></i><b>3.3.3</b> Task 2: Recreating the Figure</a></li>
<li class="chapter" data-level="3.3.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT3"><i class="fa fa-check"></i><b>3.3.4</b> Task 3: Examining Additional Variable Effects</a></li>
<li class="chapter" data-level="3.3.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT4"><i class="fa fa-check"></i><b>3.3.5</b> Task 4: Grouping the Figure Data</a></li>
<li class="chapter" data-level="3.3.6" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT5"><i class="fa fa-check"></i><b>3.3.6</b> Task 5: Identifying Groups Using <strong><code>aes()</code></strong></a></li>
<li class="chapter" data-level="3.3.7" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT6"><i class="fa fa-check"></i><b>3.3.7</b> Task 6: Changing the Shape and Size of Data Points</a></li>
<li class="chapter" data-level="3.3.8" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT7"><i class="fa fa-check"></i><b>3.3.8</b> Task 7: Adding Labels and Changing the Background</a></li>
<li class="chapter" data-level="3.3.9" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT8"><i class="fa fa-check"></i><b>3.3.9</b> Task 8: Separating a Variable and Removing Legends</a></li>
<li class="chapter" data-level="3.3.10" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#additional-considerations-briefly"><i class="fa fa-check"></i><b>3.3.10</b> Additional Considerations (briefly!)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#assignment-2"><i class="fa fa-check"></i><b>3.4</b> Assignment</a></li>
<li class="chapter" data-level="3.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#solutions-to-questions-2"><i class="fa fa-check"></i><b>3.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="3.5.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#inclass-activities-1"><i class="fa fa-check"></i><b>3.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#additional-material-1"><i class="fa fa-check"></i><b>3.6</b> Additional Material</a><ul>
<li class="chapter" data-level="3.6.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#combining-figures"><i class="fa fa-check"></i><b>3.6.1</b> Combining Figures</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html"><i class="fa fa-check"></i><b>4</b> Revisiting Probability Distributions</a><ul>
<li class="chapter" data-level="4.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#overview-4"><i class="fa fa-check"></i><b>4.1</b> Overview</a><ul>
<li class="chapter" data-level="4.1.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#discrete-or-continuous-datasets"><i class="fa fa-check"></i><b>4.1.1</b> Discrete or Continuous Datasets</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#preclass-activity-1-1"><i class="fa fa-check"></i><b>4.2</b> PreClass Activity 1</a><ul>
<li class="chapter" data-level="4.2.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#general-probability-calculations"><i class="fa fa-check"></i><b>4.2.1</b> General Probability Calculations</a></li>
<li class="chapter" data-level="4.2.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#creating-a-simple-probability-distribution"><i class="fa fa-check"></i><b>4.2.2</b> Creating a Simple Probability Distribution</a></li>
<li class="chapter" data-level="4.2.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#the-binomial-distribution---creating-a-discrete-distribution"><i class="fa fa-check"></i><b>4.2.3</b> The Binomial Distribution - Creating a Discrete Distribution</a></li>
<li class="chapter" data-level="4.2.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#dbinom---the-density-function"><i class="fa fa-check"></i><b>4.2.4</b> <strong><code>dbinom</code></strong> - The Density Function</a></li>
<li class="chapter" data-level="4.2.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#pbinom---the-cumulative-probability-function"><i class="fa fa-check"></i><b>4.2.5</b> <strong><code>pbinom</code></strong> - The Cumulative Probability Function</a></li>
<li class="chapter" data-level="4.2.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#qbinom---the-quantile-function"><i class="fa fa-check"></i><b>4.2.6</b> <strong><code>qbinom</code></strong> - The Quantile Function</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#preclass-activity-2"><i class="fa fa-check"></i><b>4.3</b> PreClass Activity 2</a><ul>
<li class="chapter" data-level="4.3.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#continuous-data---brief-recap-on-the-normal-distribution"><i class="fa fa-check"></i><b>4.3.1</b> Continuous Data - Brief Recap on The Normal Distribution</a></li>
<li class="chapter" data-level="4.3.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#properties-of-the-normal-distribution"><i class="fa fa-check"></i><b>4.3.2</b> Properties of the Normal distribution:</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-1-1"><i class="fa fa-check"></i><b>4.4</b> InClass Activity 1</a><ul>
<li class="chapter" data-level="4.4.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#continuous-data-and-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Continuous Data and the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#estimating-from-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.2</b> Estimating from the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#dnorm---the-density-function-for-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.3</b> <strong><code>dnorm()</code></strong> - The Density Function for the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#pnorm---the-probability-or-distribution-function"><i class="fa fa-check"></i><b>4.4.4</b> <strong><code>pnorm()</code></strong> - The Probability or Distribution Function</a></li>
<li class="chapter" data-level="4.4.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#qnorm---the-quantile-function"><i class="fa fa-check"></i><b>4.4.5</b> <strong><code>qnorm()</code></strong> - The Quantile Function</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-2-additional"><i class="fa fa-check"></i><b>4.5</b> InClass Activity 2 (Additional)</a><ul>
<li class="chapter" data-level="4.5.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#return-of-the-binomial"><i class="fa fa-check"></i><b>4.5.1</b> Return of the Binomial</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-3-additional"><i class="fa fa-check"></i><b>4.6</b> InClass Activity 3 (Additional)</a><ul>
<li class="chapter" data-level="4.6.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#back-to-basics"><i class="fa fa-check"></i><b>4.6.1</b> Back to Basics</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#assignment-3"><i class="fa fa-check"></i><b>4.7</b> Assignment</a><ul>
<li class="chapter" data-level="4.7.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#todays-topic---probability"><i class="fa fa-check"></i><b>4.7.1</b> Today’s Topic - Probability</a></li>
<li class="chapter" data-level="4.7.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueLib"><i class="fa fa-check"></i><b>4.7.2</b> Load in the Library</a></li>
<li class="chapter" data-level="4.7.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT1"><i class="fa fa-check"></i><b>4.7.3</b> Assignment Task 1</a></li>
<li class="chapter" data-level="4.7.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT2"><i class="fa fa-check"></i><b>4.7.4</b> Assignment Task 2</a></li>
<li class="chapter" data-level="4.7.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT3"><i class="fa fa-check"></i><b>4.7.5</b> Assignment Task 3</a></li>
<li class="chapter" data-level="4.7.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT4"><i class="fa fa-check"></i><b>4.7.6</b> Assignment Task 4</a></li>
<li class="chapter" data-level="4.7.7" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT5"><i class="fa fa-check"></i><b>4.7.7</b> Assignment Task 5</a></li>
<li class="chapter" data-level="4.7.8" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT6"><i class="fa fa-check"></i><b>4.7.8</b> Assignment Task 6</a></li>
<li class="chapter" data-level="4.7.9" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT7"><i class="fa fa-check"></i><b>4.7.9</b> Assignment Task 7</a></li>
<li class="chapter" data-level="4.7.10" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT8"><i class="fa fa-check"></i><b>4.7.10</b> Assignment Task 8</a></li>
<li class="chapter" data-level="4.7.11" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT9"><i class="fa fa-check"></i><b>4.7.11</b> Assignment Task 9</a></li>
<li class="chapter" data-level="4.7.12" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT10"><i class="fa fa-check"></i><b>4.7.12</b> Assignment Task 10</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#solutions-to-questions-3"><i class="fa fa-check"></i><b>4.8</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="4.8.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activities-2"><i class="fa fa-check"></i><b>4.8.1</b> InClass Activities</a></li>
<li class="chapter" data-level="4.8.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#assignment-solution-1"><i class="fa fa-check"></i><b>4.8.2</b> Assignment Solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html"><i class="fa fa-check"></i><b>5</b> Permutation Tests - A Skill Set</a><ul>
<li class="chapter" data-level="5.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#overview-5"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#preclass-activity-3"><i class="fa fa-check"></i><b>5.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="5.2.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-1-generating-random-numbers"><i class="fa fa-check"></i><b>5.2.1</b> Skill 1: Generating Random Numbers</a></li>
<li class="chapter" data-level="5.2.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-2-permuting-values"><i class="fa fa-check"></i><b>5.2.2</b> Skill 2: Permuting Values</a></li>
<li class="chapter" data-level="5.2.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-3-creating-tibbles"><i class="fa fa-check"></i><b>5.2.3</b> Skill 3: Creating Tibbles</a></li>
<li class="chapter" data-level="5.2.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-4-computing-differences-in-group-means"><i class="fa fa-check"></i><b>5.2.4</b> Skill 4: Computing Differences in Group Means</a></li>
<li class="chapter" data-level="5.2.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-5-creating-your-own-functions"><i class="fa fa-check"></i><b>5.2.5</b> Skill 5: Creating Your Own Functions</a></li>
<li class="chapter" data-level="5.2.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-6-replicating-operations"><i class="fa fa-check"></i><b>5.2.6</b> Skill 6: Replicating Operations</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#inclass-activity-2"><i class="fa fa-check"></i><b>5.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="5.3.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#permutation-tests-of-hypotheses"><i class="fa fa-check"></i><b>5.3.1</b> Permutation Tests of Hypotheses</a></li>
<li class="chapter" data-level="5.3.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT1"><i class="fa fa-check"></i><b>5.3.2</b> Step 1: Load in Add-on Packages and Data</a></li>
<li class="chapter" data-level="5.3.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT2"><i class="fa fa-check"></i><b>5.3.3</b> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></a></li>
<li class="chapter" data-level="5.3.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT3"><i class="fa fa-check"></i><b>5.3.4</b> Step 3: Permute the Group Labels</a></li>
<li class="chapter" data-level="5.3.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT4"><i class="fa fa-check"></i><b>5.3.5</b> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</a></li>
<li class="chapter" data-level="5.3.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT5"><i class="fa fa-check"></i><b>5.3.6</b> Step 5: Compare the Observed Mean Difference to the NHD</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#assignment-4"><i class="fa fa-check"></i><b>5.4</b> Assignment</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#solutions-to-questions-4"><i class="fa fa-check"></i><b>5.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="5.5.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#inclass-activities-3"><i class="fa fa-check"></i><b>5.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html"><i class="fa fa-check"></i><b>6</b> NHST and One-Sample t-tests</a><ul>
<li class="chapter" data-level="6.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#overview-6"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activity-1-2"><i class="fa fa-check"></i><b>6.2</b> PreClass Activity 1</a><ul>
<li class="chapter" data-level="6.2.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#the-binomial-test"><i class="fa fa-check"></i><b>6.2.1</b> The Binomial Test</a></li>
<li class="chapter" data-level="6.2.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT1"><i class="fa fa-check"></i><b>6.2.2</b> Task 1: Creating a Dataframe</a></li>
<li class="chapter" data-level="6.2.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT2"><i class="fa fa-check"></i><b>6.2.3</b> Task 2: Comparing Original and New Sample Reaction Times</a></li>
<li class="chapter" data-level="6.2.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT3"><i class="fa fa-check"></i><b>6.2.4</b> Task 3: Calculating Probability</a></li>
<li class="chapter" data-level="6.2.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#the-one-sample-t-test"><i class="fa fa-check"></i><b>6.2.5</b> The One-Sample t-test</a></li>
<li class="chapter" data-level="6.2.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT4"><i class="fa fa-check"></i><b>6.2.6</b> Task 4: Calculating the Mean and Standard Deviation</a></li>
<li class="chapter" data-level="6.2.7" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT5"><i class="fa fa-check"></i><b>6.2.7</b> Task 5: Calculating the Observed Test Statistic</a></li>
<li class="chapter" data-level="6.2.8" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT6"><i class="fa fa-check"></i><b>6.2.8</b> Task 6: Comparing the Observed Test Statistic to the t-distribution using <strong><code>pt()</code></strong></a></li>
<li class="chapter" data-level="6.2.9" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT7"><i class="fa fa-check"></i><b>6.2.9</b> Task 7: Comparing the Observed Test Statistic to the t-distribution using <strong><code>t.test()</code></strong></a></li>
<li class="chapter" data-level="6.2.10" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT8"><i class="fa fa-check"></i><b>6.2.10</b> Task 8: Drawing Conclusions about the new data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activity-2-additional"><i class="fa fa-check"></i><b>6.3</b> PreClass Activity 2 (Additional)</a><ul>
<li class="chapter" data-level="6.3.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#a-short-blog-on-barplots"><i class="fa fa-check"></i><b>6.3.1</b> A short blog on Barplots</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#inclass-activity-3"><i class="fa fa-check"></i><b>6.4</b> InClass Activity</a><ul>
<li class="chapter" data-level="6.4.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT1"><i class="fa fa-check"></i><b>6.4.1</b> Task 1: Evaluators</a></li>
<li class="chapter" data-level="6.4.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT2"><i class="fa fa-check"></i><b>6.4.2</b> Task 2: Ratings</a></li>
<li class="chapter" data-level="6.4.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT3"><i class="fa fa-check"></i><b>6.4.3</b> Task 3: Creating a Figure</a></li>
<li class="chapter" data-level="6.4.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT4"><i class="fa fa-check"></i><b>6.4.4</b> Task 4: t-tests</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#assignment-5"><i class="fa fa-check"></i><b>6.5</b> Assignment</a><ul>
<li class="chapter" data-level="6.5.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT1A"><i class="fa fa-check"></i><b>6.5.1</b> Task 1A: Libraries</a></li>
<li class="chapter" data-level="6.5.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT1B"><i class="fa fa-check"></i><b>6.5.2</b> Task 1B: Loading in the data</a></li>
<li class="chapter" data-level="6.5.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT2"><i class="fa fa-check"></i><b>6.5.3</b> Task 2: Selecting only relevant columns</a></li>
<li class="chapter" data-level="6.5.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT3"><i class="fa fa-check"></i><b>6.5.4</b> Task 3: Verify the number of subjects in each group</a></li>
<li class="chapter" data-level="6.5.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT4"><i class="fa fa-check"></i><b>6.5.5</b> Task 4: Reproduce Figure 2a</a></li>
<li class="chapter" data-level="6.5.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT5"><i class="fa fa-check"></i><b>6.5.6</b> Task 5: Interpreting your Figure</a></li>
<li class="chapter" data-level="6.5.7" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT6"><i class="fa fa-check"></i><b>6.5.7</b> Task 6: t-test</a></li>
<li class="chapter" data-level="6.5.8" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT7"><i class="fa fa-check"></i><b>6.5.8</b> Task 7: Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#solutions-to-questions-5"><i class="fa fa-check"></i><b>6.6</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="6.6.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activities-1"><i class="fa fa-check"></i><b>6.6.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="6.6.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#inclass-activities-4"><i class="fa fa-check"></i><b>6.6.2</b> InClass Activities</a></li>
<li class="chapter" data-level="6.6.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#homework-activity"><i class="fa fa-check"></i><b>6.6.3</b> Homework Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html"><i class="fa fa-check"></i><b>7</b> Within-Subjects t-test</a><ul>
<li class="chapter" data-level="7.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#overview-7"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#preclass-activity-4"><i class="fa fa-check"></i><b>7.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="7.2.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#reading"><i class="fa fa-check"></i><b>7.2.1</b> Reading</a></li>
<li class="chapter" data-level="7.2.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task"><i class="fa fa-check"></i><b>7.2.2</b> Task</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#inclass-activity-4"><i class="fa fa-check"></i><b>7.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="7.3.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT1"><i class="fa fa-check"></i><b>7.3.1</b> Task 1: Load the Data</a></li>
<li class="chapter" data-level="7.3.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT2"><i class="fa fa-check"></i><b>7.3.2</b> Task 2: Wrangle the Data</a></li>
<li class="chapter" data-level="7.3.3" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT3"><i class="fa fa-check"></i><b>7.3.3</b> Task 3: Look at the Histogram for Normality</a></li>
<li class="chapter" data-level="7.3.4" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT4"><i class="fa fa-check"></i><b>7.3.4</b> Task 4: A Boxplot of Outliers</a></li>
<li class="chapter" data-level="7.3.5" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT5"><i class="fa fa-check"></i><b>7.3.5</b> Task 5: The Violin Plot</a></li>
<li class="chapter" data-level="7.3.6" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT6"><i class="fa fa-check"></i><b>7.3.6</b> Task 6: Calculating Descriptives</a></li>
<li class="chapter" data-level="7.3.7" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT7"><i class="fa fa-check"></i><b>7.3.7</b> Task 7: Visualising Means and Descriptives</a></li>
<li class="chapter" data-level="7.3.8" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT8"><i class="fa fa-check"></i><b>7.3.8</b> Task 8: The t-test</a></li>
<li class="chapter" data-level="7.3.9" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT9"><i class="fa fa-check"></i><b>7.3.9</b> Task 9: The Write-up</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#assignment-6"><i class="fa fa-check"></i><b>7.4</b> Assignment</a></li>
<li class="chapter" data-level="7.5" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#solutions-to-questions-6"><i class="fa fa-check"></i><b>7.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="7.5.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#inclass-activities-5"><i class="fa fa-check"></i><b>7.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html"><i class="fa fa-check"></i><b>8</b> APES - Alpha, Power, Effect Sizes, Sample Size</a><ul>
<li class="chapter" data-level="8.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#overview-8"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#preclass-activity-5"><i class="fa fa-check"></i><b>8.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="8.2.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#reading-1"><i class="fa fa-check"></i><b>8.2.1</b> Reading</a></li>
<li class="chapter" data-level="8.2.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#watch"><i class="fa fa-check"></i><b>8.2.2</b> Watch</a></li>
<li class="chapter" data-level="8.2.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#optional"><i class="fa fa-check"></i><b>8.2.3</b> Optional</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#inclass-activity-5"><i class="fa fa-check"></i><b>8.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="8.3.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT1"><i class="fa fa-check"></i><b>8.3.1</b> Task 1: Effect size from a one-sample t-test</a></li>
<li class="chapter" data-level="8.3.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT2"><i class="fa fa-check"></i><b>8.3.2</b> Task 2: Effect size from between-subjects t-test</a></li>
<li class="chapter" data-level="8.3.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT3"><i class="fa fa-check"></i><b>8.3.3</b> Task 3: Effect Size from matched-pairs t-test</a></li>
<li class="chapter" data-level="8.3.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT4"><i class="fa fa-check"></i><b>8.3.4</b> Task 4: t-value and effect size for a between-subjects Experiment</a></li>
<li class="chapter" data-level="8.3.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT5"><i class="fa fa-check"></i><b>8.3.5</b> Task 5: Sample size for standard power one-sample t-test</a></li>
<li class="chapter" data-level="8.3.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT6"><i class="fa fa-check"></i><b>8.3.6</b> Task 6: Effect size from a high power between-subjects t-test</a></li>
<li class="chapter" data-level="8.3.7" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT7"><i class="fa fa-check"></i><b>8.3.7</b> Task 7: Power of Published Research</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#assignment-7"><i class="fa fa-check"></i><b>8.4</b> Assignment</a><ul>
<li class="chapter" data-level="8.4.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT1"><i class="fa fa-check"></i><b>8.4.1</b> Assignment Task 1</a></li>
<li class="chapter" data-level="8.4.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT2"><i class="fa fa-check"></i><b>8.4.2</b> Assignment Task 2</a></li>
<li class="chapter" data-level="8.4.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT3"><i class="fa fa-check"></i><b>8.4.3</b> Assignment Task 3</a></li>
<li class="chapter" data-level="8.4.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT4"><i class="fa fa-check"></i><b>8.4.4</b> Assignment Task 4</a></li>
<li class="chapter" data-level="8.4.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT5"><i class="fa fa-check"></i><b>8.4.5</b> Assignment Task 5</a></li>
<li class="chapter" data-level="8.4.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT6"><i class="fa fa-check"></i><b>8.4.6</b> Assignment Task 6</a></li>
<li class="chapter" data-level="8.4.7" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT7"><i class="fa fa-check"></i><b>8.4.7</b> Assignment Task 7</a></li>
<li class="chapter" data-level="8.4.8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT8"><i class="fa fa-check"></i><b>8.4.8</b> Assignment Task 8</a></li>
<li class="chapter" data-level="8.4.9" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT9"><i class="fa fa-check"></i><b>8.4.9</b> Assignment Task 9</a></li>
<li class="chapter" data-level="8.4.10" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT10"><i class="fa fa-check"></i><b>8.4.10</b> Assignment Task 10</a></li>
<li class="chapter" data-level="8.4.11" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT11"><i class="fa fa-check"></i><b>8.4.11</b> Assignment Task 11</a></li>
<li class="chapter" data-level="8.4.12" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#the-pwr-package"><i class="fa fa-check"></i><b>8.4.12</b> The <strong><code>pwr</code></strong> package</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#solutions-to-questions-7"><i class="fa fa-check"></i><b>8.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="8.5.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#inclass-activities-6"><i class="fa fa-check"></i><b>8.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="8.5.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#homework-activity-1"><i class="fa fa-check"></i><b>8.5.2</b> Homework Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html"><i class="fa fa-check"></i><b>9</b> Reflection - Semester 1</a><ul>
<li class="chapter" data-level="9.1" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#overview-9"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#preclass-activity-6"><i class="fa fa-check"></i><b>9.2</b> PreClass Activity</a></li>
<li class="chapter" data-level="9.3" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#inclass-activity-6"><i class="fa fa-check"></i><b>9.3</b> InClass Activity</a></li>
<li class="chapter" data-level="9.4" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#assignment-8"><i class="fa fa-check"></i><b>9.4</b> Assignment</a></li>
<li class="chapter" data-level="9.5" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#solutions-to-questions-8"><i class="fa fa-check"></i><b>9.5</b> Solutions to Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>10</b> Correlations</a><ul>
<li class="chapter" data-level="10.1" data-path="correlations.html"><a href="correlations.html#overview-10"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="correlations.html"><a href="correlations.html#preclass-activity-7"><i class="fa fa-check"></i><b>10.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="10.2.1" data-path="correlations.html"><a href="correlations.html#read"><i class="fa fa-check"></i><b>10.2.1</b> Read</a></li>
<li class="chapter" data-level="10.2.2" data-path="correlations.html"><a href="correlations.html#watch-1"><i class="fa fa-check"></i><b>10.2.2</b> Watch</a></li>
<li class="chapter" data-level="10.2.3" data-path="correlations.html"><a href="correlations.html#play"><i class="fa fa-check"></i><b>10.2.3</b> Play</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="correlations.html"><a href="correlations.html#inclass-activity-7"><i class="fa fa-check"></i><b>10.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="10.3.1" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT1"><i class="fa fa-check"></i><b>10.3.1</b> Task 1 - The Data</a></li>
<li class="chapter" data-level="10.3.2" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT2"><i class="fa fa-check"></i><b>10.3.2</b> Task 2 - Interval or Ordinal</a></li>
<li class="chapter" data-level="10.3.3" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT3"><i class="fa fa-check"></i><b>10.3.3</b> Task 3 - Missing Data</a></li>
<li class="chapter" data-level="10.3.4" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT4"><i class="fa fa-check"></i><b>10.3.4</b> Task 4 - Normality</a></li>
<li class="chapter" data-level="10.3.5" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT5"><i class="fa fa-check"></i><b>10.3.5</b> Task 5 - Descriptives</a></li>
<li class="chapter" data-level="10.3.6" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT6"><i class="fa fa-check"></i><b>10.3.6</b> Task 6 - Pearson or Spearman?</a></li>
<li class="chapter" data-level="10.3.7" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT7"><i class="fa fa-check"></i><b>10.3.7</b> Task 7 - Interpretation</a></li>
<li class="chapter" data-level="10.3.8" data-path="correlations.html"><a href="correlations.html#advanced-1-matrix-of-scatterplots"><i class="fa fa-check"></i><b>10.3.8</b> Advanced 1: Matrix of Scatterplots</a></li>
<li class="chapter" data-level="10.3.9" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT8"><i class="fa fa-check"></i><b>10.3.9</b> Task 8 - The Matrix</a></li>
<li class="chapter" data-level="10.3.10" data-path="correlations.html"><a href="correlations.html#advanced-2-attitudes-towards-vaping"><i class="fa fa-check"></i><b>10.3.10</b> Advanced 2: Attitudes towards Vaping</a></li>
<li class="chapter" data-level="10.3.11" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT9"><i class="fa fa-check"></i><b>10.3.11</b> Task 9 - Attitudes to Vaping</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="correlations.html"><a href="correlations.html#assignment-9"><i class="fa fa-check"></i><b>10.4</b> Assignment</a></li>
<li class="chapter" data-level="10.5" data-path="correlations.html"><a href="correlations.html#solutions-to-questions-9"><i class="fa fa-check"></i><b>10.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="10.5.1" data-path="correlations.html"><a href="correlations.html#inclass-activity-8"><i class="fa fa-check"></i><b>10.5.1</b> InClass Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html"><i class="fa fa-check"></i><b>11</b> Introduction to GLM: One-factor ANOVA</a><ul>
<li class="chapter" data-level="11.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#overview-11"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#preclass-activity-8"><i class="fa fa-check"></i><b>11.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="11.2.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#read-1"><i class="fa fa-check"></i><b>11.2.1</b> Read</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#inclass-activity-9"><i class="fa fa-check"></i><b>11.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="11.3.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#recreate-decomposition-matrix-from-the-raw-data"><i class="fa fa-check"></i><b>11.3.1</b> Recreate decomposition matrix from the raw data</a></li>
<li class="chapter" data-level="11.3.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT1"><i class="fa fa-check"></i><b>11.3.2</b> Step 1: Create the basic tibble</a></li>
<li class="chapter" data-level="11.3.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT2"><i class="fa fa-check"></i><b>11.3.3</b> Step 2: Estimate the Grand Mean <span class="math inline">\(\hat{\mu}\)</span></a></li>
<li class="chapter" data-level="11.3.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT3"><i class="fa fa-check"></i><b>11.3.4</b> Step 3: Entering the estimates <span class="math inline">\(\hat{A}_1\)</span>, <span class="math inline">\(\hat{A}_2\)</span>, <span class="math inline">\(\hat{A}_3\)</span></a></li>
<li class="chapter" data-level="11.3.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT4"><i class="fa fa-check"></i><b>11.3.5</b> Step 4: Calculate Residuals <span class="math inline">\(\widehat{S(A)}_{ij}\)</span></a></li>
<li class="chapter" data-level="11.3.6" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT5"><i class="fa fa-check"></i><b>11.3.6</b> Step 5: Sums of squares</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#assignment-10"><i class="fa fa-check"></i><b>11.4</b> Assignment</a><ul>
<li class="chapter" data-level="11.4.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT1"><i class="fa fa-check"></i><b>11.4.1</b> Question 1</a></li>
<li class="chapter" data-level="11.4.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT2"><i class="fa fa-check"></i><b>11.4.2</b> Question 2</a></li>
<li class="chapter" data-level="11.4.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT3"><i class="fa fa-check"></i><b>11.4.3</b> Question 3</a></li>
<li class="chapter" data-level="11.4.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT4"><i class="fa fa-check"></i><b>11.4.4</b> Question 4</a></li>
<li class="chapter" data-level="11.4.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT5"><i class="fa fa-check"></i><b>11.4.5</b> Question 5</a></li>
<li class="chapter" data-level="11.4.6" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT6"><i class="fa fa-check"></i><b>11.4.6</b> Question 6</a></li>
<li class="chapter" data-level="11.4.7" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT7"><i class="fa fa-check"></i><b>11.4.7</b> Question 7</a></li>
<li class="chapter" data-level="11.4.8" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT8"><i class="fa fa-check"></i><b>11.4.8</b> Question 8</a></li>
<li class="chapter" data-level="11.4.9" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT9"><i class="fa fa-check"></i><b>11.4.9</b> Question 9: Create your own decomposition matrix</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#solutions-to-questions-10"><i class="fa fa-check"></i><b>11.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="11.5.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#inclass-activities-7"><i class="fa fa-check"></i><b>11.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="11.5.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#homework-activities"><i class="fa fa-check"></i><b>11.5.2</b> Homework Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html"><i class="fa fa-check"></i><b>12</b> Continuing the GLM: One-factor ANOVA</a><ul>
<li class="chapter" data-level="12.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#overview-12"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#preclass-activity-9"><i class="fa fa-check"></i><b>12.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="12.2.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#read-2"><i class="fa fa-check"></i><b>12.2.1</b> Read</a></li>
<li class="chapter" data-level="12.2.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#try"><i class="fa fa-check"></i><b>12.2.2</b> Try</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#inclass-activity-10"><i class="fa fa-check"></i><b>12.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="12.3.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT1"><i class="fa fa-check"></i><b>12.3.1</b> Task 1 - Quick Checks</a></li>
<li class="chapter" data-level="12.3.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT2"><i class="fa fa-check"></i><b>12.3.2</b> Task 2 - Mean squares and degrees of freedom</a></li>
<li class="chapter" data-level="12.3.3" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT3"><i class="fa fa-check"></i><b>12.3.3</b> Task 3 - F-ratios</a></li>
<li class="chapter" data-level="12.3.4" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT4"><i class="fa fa-check"></i><b>12.3.4</b> Task 4 - Using ez::ezANOVA()</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#assignment-11"><i class="fa fa-check"></i><b>12.4</b> Assignment</a></li>
<li class="chapter" data-level="12.5" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#solutions-to-questions-11"><i class="fa fa-check"></i><b>12.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="12.5.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#inclass-activities-8"><i class="fa fa-check"></i><b>12.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html"><i class="fa fa-check"></i><b>13</b> Continuing the GLM: Two-factor designs</a><ul>
<li class="chapter" data-level="13.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#overview-13"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#preclass-activity-10"><i class="fa fa-check"></i><b>13.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="13.2.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#read-3"><i class="fa fa-check"></i><b>13.2.1</b> Read</a></li>
<li class="chapter" data-level="13.2.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#try-1"><i class="fa fa-check"></i><b>13.2.2</b> TRY</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#inclass-activity-11"><i class="fa fa-check"></i><b>13.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="13.3.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT1"><i class="fa fa-check"></i><b>13.3.1</b> Estimation equations and decomposition matrix</a></li>
<li class="chapter" data-level="13.3.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT2"><i class="fa fa-check"></i><b>13.3.2</b> Adding the missing columns</a></li>
<li class="chapter" data-level="13.3.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT3"><i class="fa fa-check"></i><b>13.3.3</b> Understanding the two-factor decomposition matrix</a></li>
<li class="chapter" data-level="13.3.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT4"><i class="fa fa-check"></i><b>13.3.4</b> Get your data ready for analysis</a></li>
<li class="chapter" data-level="13.3.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT5"><i class="fa fa-check"></i><b>13.3.5</b> Visualizing 2x2 designs: The interaction plot</a></li>
<li class="chapter" data-level="13.3.6" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT6"><i class="fa fa-check"></i><b>13.3.6</b> Running a 2x2 between-subjects ANOVA with ezANOVA</a></li>
<li class="chapter" data-level="13.3.7" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#app-understanding-main-effects-and-interactions"><i class="fa fa-check"></i><b>13.3.7</b> App: Understanding main effects and interactions</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#assignment-12"><i class="fa fa-check"></i><b>13.4</b> Assignment</a><ul>
<li class="chapter" data-level="13.4.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT1A"><i class="fa fa-check"></i><b>13.4.1</b> Task 1A: Libraries</a></li>
<li class="chapter" data-level="13.4.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT1B"><i class="fa fa-check"></i><b>13.4.2</b> Task 1B: Loading in the data</a></li>
<li class="chapter" data-level="13.4.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT2"><i class="fa fa-check"></i><b>13.4.3</b> Task 2: Calculate cell means</a></li>
<li class="chapter" data-level="13.4.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT3"><i class="fa fa-check"></i><b>13.4.4</b> Task 3: Marginal means for sex</a></li>
<li class="chapter" data-level="13.4.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT4"><i class="fa fa-check"></i><b>13.4.5</b> Task 4: Marginal means for condition</a></li>
<li class="chapter" data-level="13.4.6" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT5"><i class="fa fa-check"></i><b>13.4.6</b> Task 5: Interaction plot</a></li>
<li class="chapter" data-level="13.4.7" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT6"><i class="fa fa-check"></i><b>13.4.7</b> Task 6: Recap Question 1</a></li>
<li class="chapter" data-level="13.4.8" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT7"><i class="fa fa-check"></i><b>13.4.8</b> Task 7: Recap Question 2</a></li>
<li class="chapter" data-level="13.4.9" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT8"><i class="fa fa-check"></i><b>13.4.9</b> Task 8: Recap Question 3</a></li>
<li class="chapter" data-level="13.4.10" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT9"><i class="fa fa-check"></i><b>13.4.10</b> Task 9: Running the factorial ANOVA</a></li>
<li class="chapter" data-level="13.4.11" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT10"><i class="fa fa-check"></i><b>13.4.11</b> Task 10: Interpreting the ANOVA output Question</a></li>
<li class="chapter" data-level="13.4.12" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT11"><i class="fa fa-check"></i><b>13.4.12</b> Task 11: Report your results</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#solutions-to-questions-12"><i class="fa fa-check"></i><b>13.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="13.5.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#inclass-activities-9"><i class="fa fa-check"></i><b>13.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="13.5.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#homework-activities-1"><i class="fa fa-check"></i><b>13.5.2</b> Homework Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>14</b> Regression</a><ul>
<li class="chapter" data-level="14.1" data-path="regression.html"><a href="regression.html#overview-14"><i class="fa fa-check"></i><b>14.1</b> Overview</a></li>
<li class="chapter" data-level="14.2" data-path="regression.html"><a href="regression.html#preclass-activity-11"><i class="fa fa-check"></i><b>14.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="14.2.1" data-path="regression.html"><a href="regression.html#read-4"><i class="fa fa-check"></i><b>14.2.1</b> Read</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="regression.html"><a href="regression.html#inclass-activity-12"><i class="fa fa-check"></i><b>14.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="14.3.1" data-path="regression.html"><a href="regression.html#Ch14InClassQueT1"><i class="fa fa-check"></i><b>14.3.1</b> Task 1: Setup</a></li>
<li class="chapter" data-level="14.3.2" data-path="regression.html"><a href="regression.html#Ch14InClassQueT2"><i class="fa fa-check"></i><b>14.3.2</b> Task 2: Restructuring the ratings</a></li>
<li class="chapter" data-level="14.3.3" data-path="regression.html"><a href="regression.html#Ch14InClassQueT3"><i class="fa fa-check"></i><b>14.3.3</b> Task 3: Calculate mean trustworthiness rating for each voice</a></li>
<li class="chapter" data-level="14.3.4" data-path="regression.html"><a href="regression.html#Ch14InClassQueT4"><i class="fa fa-check"></i><b>14.3.4</b> Task 4: Joining the Data together</a></li>
<li class="chapter" data-level="14.3.5" data-path="regression.html"><a href="regression.html#Ch14InClassQueT5"><i class="fa fa-check"></i><b>14.3.5</b> Task 5: Scatterplot</a></li>
<li class="chapter" data-level="14.3.6" data-path="regression.html"><a href="regression.html#Ch14InClassQueT6"><i class="fa fa-check"></i><b>14.3.6</b> Task 6: Spreading the data</a></li>
<li class="chapter" data-level="14.3.7" data-path="regression.html"><a href="regression.html#Ch14InClassQueT7"><i class="fa fa-check"></i><b>14.3.7</b> Task 7: The Regressions</a></li>
<li class="chapter" data-level="14.3.8" data-path="regression.html"><a href="regression.html#Ch14InClassQueT8"><i class="fa fa-check"></i><b>14.3.8</b> Task 8: Making interpretations</a></li>
<li class="chapter" data-level="14.3.9" data-path="regression.html"><a href="regression.html#Ch14InClassQueT9"><i class="fa fa-check"></i><b>14.3.9</b> Task 9: Making predictions</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="regression.html"><a href="regression.html#assignment-13"><i class="fa fa-check"></i><b>14.4</b> Assignment</a></li>
<li class="chapter" data-level="14.5" data-path="regression.html"><a href="regression.html#solutions-to-questions-13"><i class="fa fa-check"></i><b>14.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="14.5.1" data-path="regression.html"><a href="regression.html#inclass-ativities"><i class="fa fa-check"></i><b>14.5.1</b> InClass Ativities</a></li>
<li class="chapter" data-level="14.5.2" data-path="regression.html"><a href="regression.html#task-3"><i class="fa fa-check"></i><b>14.5.2</b> Task 3</a></li>
<li class="chapter" data-level="14.5.3" data-path="regression.html"><a href="regression.html#task-4"><i class="fa fa-check"></i><b>14.5.3</b> Task 4</a></li>
<li class="chapter" data-level="14.5.4" data-path="regression.html"><a href="regression.html#task-5"><i class="fa fa-check"></i><b>14.5.4</b> Task 5</a></li>
<li class="chapter" data-level="14.5.5" data-path="regression.html"><a href="regression.html#task-6"><i class="fa fa-check"></i><b>14.5.5</b> Task 6</a></li>
<li class="chapter" data-level="14.5.6" data-path="regression.html"><a href="regression.html#task-7"><i class="fa fa-check"></i><b>14.5.6</b> Task 7</a></li>
<li class="chapter" data-level="14.5.7" data-path="regression.html"><a href="regression.html#task-8"><i class="fa fa-check"></i><b>14.5.7</b> Task 8</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html"><i class="fa fa-check"></i><b>15</b> Combining ANOVA and Regression (e.g. ANCOVAs)</a><ul>
<li class="chapter" data-level="15.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#overview-15"><i class="fa fa-check"></i><b>15.1</b> Overview</a></li>
<li class="chapter" data-level="15.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#preclass-activity-12"><i class="fa fa-check"></i><b>15.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="15.2.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#read-5"><i class="fa fa-check"></i><b>15.2.1</b> Read</a></li>
<li class="chapter" data-level="15.2.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#activity"><i class="fa fa-check"></i><b>15.2.2</b> Activity</a></li>
<li class="chapter" data-level="15.2.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT1"><i class="fa fa-check"></i><b>15.2.3</b> Loading in the data</a></li>
<li class="chapter" data-level="15.2.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT2"><i class="fa fa-check"></i><b>15.2.4</b> Compute the well-being score for each participant</a></li>
<li class="chapter" data-level="15.2.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT3"><i class="fa fa-check"></i><b>15.2.5</b> Visualising Screen time on all technologies</a></li>
<li class="chapter" data-level="15.2.6" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT4"><i class="fa fa-check"></i><b>15.2.6</b> Visualising the Screen time and Well-being relationship</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#inclass-activity-13"><i class="fa fa-check"></i><b>15.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="15.3.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT1"><i class="fa fa-check"></i><b>15.3.1</b> Smartphone and well-being for boys and girls</a></li>
<li class="chapter" data-level="15.3.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT2"><i class="fa fa-check"></i><b>15.3.2</b> Visualising and Interpreting the relationship between smartphone use and wellbeing by sex</a></li>
<li class="chapter" data-level="15.3.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#a-side-point-on-mean-centering-and-deviation-coding"><i class="fa fa-check"></i><b>15.3.3</b> A side point on mean centering and deviation coding</a></li>
<li class="chapter" data-level="15.3.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT3"><i class="fa fa-check"></i><b>15.3.4</b> Estimating model parameters</a></li>
<li class="chapter" data-level="15.3.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT4"><i class="fa fa-check"></i><b>15.3.5</b> Final Interpretations</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#assignment-14"><i class="fa fa-check"></i><b>15.4</b> Assignment</a></li>
<li class="chapter" data-level="15.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#solutions-to-questions-14"><i class="fa fa-check"></i><b>15.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="15.5.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#preclass-activities-2"><i class="fa fa-check"></i><b>15.5.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="15.5.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#inclass-activities-10"><i class="fa fa-check"></i><b>15.5.2</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html"><i class="fa fa-check"></i><b>16</b> Reflection - Semester 2</a><ul>
<li class="chapter" data-level="16.1" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#overview-16"><i class="fa fa-check"></i><b>16.1</b> Overview</a></li>
<li class="chapter" data-level="16.2" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#preclass-activity-13"><i class="fa fa-check"></i><b>16.2</b> PreClass Activity</a></li>
<li class="chapter" data-level="16.3" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#inclass-activity-14"><i class="fa fa-check"></i><b>16.3</b> InClass Activity</a></li>
<li class="chapter" data-level="16.4" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#assignment-15"><i class="fa fa-check"></i><b>16.4</b> Assignment</a></li>
<li class="chapter" data-level="16.5" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#solutions-to-questions-15"><i class="fa fa-check"></i><b>16.5</b> Solutions to Questions</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>A</b> References</a></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Level 2 Research Methods and Statistics Practical Skills</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="permutation-tests---a-skill-set" class="section level1">
<h1><span class="header-section-number">Lab 5</span> Permutation Tests - A Skill Set</h1>
<div id="overview-5" class="section level2">
<h2><span class="header-section-number">5.1</span> Overview</h2>
<p>In this week’s lab, you will perform your first hypothesis test using a procedure known as a <strong>permutation test</strong>. We will help you learn how to do this through building and running data simulation procedures. In order to complete this lab, you will require the following skills which we will teach you today:</p>
<ul>
<li>Skill 1: Generating random numbers with <code>base::rnorm()</code></li>
<li>Skill 2: Permuting values with <code>base::sample()</code><br />
</li>
<li>Skill 3: Creating a “tibble” (a type of data table) using <code>tibble::tibble()</code></li>
<li>Skill 4: Computing and extracting a difference in group means using <code>dplyr::pull()</code> and <code>purrr::pluck()</code></li>
<li>Skill 5: Creating your own custom functions using <code>base::function()</code></li>
<li>Skill 6: Repeating operations using <code>base::replicate()</code></li>
</ul>
<p>To many, a lot of statistics must seem a bit like blind faith as it deals with estimating quantities we haven’t observed (or can’t observe), e.g. the mean of a whole population. As such, we have to know if we can trust our procedures for making estimations and inferences because we rarely get a chance to compare the estimated values to the true values to see if they match up. One way to test a procedure, and in turn learn about statistics, is through data simulation. In simulations, <strong>we create</strong> a population and then draw samples and run tests on the data, i.e. on this <strong>known</strong> population. By running lots of simulations we can test our procedures and make sure they are acting as we expect them to. This approach is known as a <strong>Monte Carlo simulation</strong>, named after the city famous for the many games of chance that are played there.</p>
<div class="solution">
<button>
Portfolio Point - Monte Carlo or Bust
</button>
<div class="info">
<p>
You can go read up on the Monte Carlo approach if you like. It can, however, get quite indepth, as having a brief glance at the wikipedia entry on it highlights. The main thing to keep in mind is that the method involves creating a population and continually taking samples from that population in order to make an inference. This is what we will show you in the lab. Data simulation and “creating” your own datasets, to see how tests work, is a great way to understand statistics. When doing this lab, keep in mind how easy it really is to find a significant result if even randomly created data can give a significant result. This may help dispell any notion that there is something inherently important about a significant result, in itself.
</p>
</div>
</div>

</div>
<div id="preclass-activity-3" class="section level2">
<h2><span class="header-section-number">5.2</span> PreClass Activity</h2>
<p>We will now take each skill in turn. Be sure to try them all out. It looks a lot of reading but it is mainly just showing you the output of the functions so you can see you are doing it correctly. The key thing is to try them yourselves and don’t be scared to change things to see what might happen if you do it slightly differently. We will also ask a couple of questions along the way to make sure you understand the skills.</p>
<div id="skill-1-generating-random-numbers" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Skill 1: Generating Random Numbers</h3>
<p>The <code>base::rnorm()</code> function generates values from a normal distribution and takes the following arguments:</p>
<ul>
<li><code>n</code>: the number of observations to generate</li>
<li><code>mean</code>: the mean of the distribution (default 0)</li>
<li><code>sd</code> : the standard deviation of the distribution (default 1)</li>
</ul>
<p>To generate 10 or even 50 random numbers from a standard normal distribution (M = 0, SD = 1), you would use <code>rnorm(10)</code> or <code>rnorm(50)</code> respectively.</p>
<ul>
<li>Type <code>rnorm(50)</code> into your console and see what happens. Use the below example for <code>rnorm(10)</code> to help you.<br />
</li>
<li>Try increasing <code>n</code> to 1000.</li>
</ul>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" data-line-number="1"><span class="kw">rnorm</span>(<span class="dv">10</span>)</a></code></pre></div>
<pre><code>##  [1]  0.3305911 -0.9265012  0.1175676  0.1715754  0.2441749  1.5752561
##  [7]  0.5681333  0.6427852 -0.3356916  0.1501672</code></pre>
<p><br>
<span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>If you enter <code>rnorm(50)</code> again you will get different numbers. Why? <select class='solveme' data-answer='["The numbers are random"]'> <option></option> <option>I have made a mistake</option> <option>The numbers are random</option> <option>R has made a mistake</option> <option>Phil has made a mistake</option></select></p>
<p>If you want to change the mean or sd, you would need to pass additional arguments to the function as shown below.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb168-1" data-line-number="1"><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">mean =</span> <span class="dv">1</span>, <span class="dt">sd =</span> <span class="fl">.5</span>)</a></code></pre></div>
<ul>
<li>Try changing the mean and sd values a couple of times and see what happens. You get different numbers again that will be around the mean you set! Set a mean of 10, then a mean of 100, to test this.</li>
</ul>
<p>Finally, for this Skill, you can concatenate (i.e. link) numbers together into a single vector using the <code>c()</code> function from base R. For instance, say you wanted to create a vector with two sets of 50 random numbers from two separate samples: one set of 50 with a mean of 75 and the other with a mean of 90, you would use:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" data-line-number="1">random_numbers &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">50</span>, <span class="dv">75</span>),</a>
<a class="sourceLine" id="cb169-2" data-line-number="2">                    <span class="kw">rnorm</span>(<span class="dv">50</span>, <span class="dv">90</span>))</a></code></pre></div>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>In the above example code, what is the standard deviation of the two samples you have created? <select class='solveme' data-answer='["1"]'> <option></option> <option>50</option> <option>75</option> <option>90</option> <option>1</option></select></p>
<div class="solution">
<button>
Explain This - I don’t get this answer!
</button>
<div class="info">
<p>
What is the <strong>default</strong> sd of the function?
</p>
<p>
Both populations would have an sd of 1, because that is the default, although you could easily change that. Try it out!
</p>
</div>
</div>
<p><br>
It is always good to check that your new vector has the right number of data points in it - i.e. the total of the two samples; a sanity check if you will. The new vector <code>random_numbers</code> should have 100 elements. You could verify this using the <code>length()</code> function:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" data-line-number="1"><span class="kw">length</span>(random_numbers)</a></code></pre></div>
<pre><code>## [1] 100</code></pre>
<p><br>
<span style="font-size: 18px; font-weight: bold; color: var(--blue);">Skill 1 out of 6 Complete!</span></p>
</div>
<div id="skill-2-permuting-values" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Skill 2: Permuting Values</h3>
<p>Another thing that is useful to be able to do is to generate <strong>permutations</strong> of values.</p>
<div class="solution">
<button>
Portfolio Point - What are Permutations?
</button>
<div class="info">
<p>
A <strong>permutation</strong> is just a different ordering of the same values. For example, the numbers 1, 2, 3 can be permuted into the following 6 sequences:
</p>
<ul>
<li>
1, 2, 3
</li>
<li>
1, 3, 2
</li>
<li>
2, 1, 3
</li>
<li>
2, 3, 1
</li>
<li>
3, 1, 2
</li>
<li>
3, 2, 1
</li>
</ul>
<p>
The more values you have, the more permutations of the order you have. The number of permutations can be calculated by, for example, <code>3 x 2 x 1 = 6</code>, where 3 is the number of values you have. Or through code: <code>factorial(3) = 6</code>. This assumes that each value is used once in the sequence and that each value never changes, i.e. 1234 cannot suddenly become 1235.
</p>
</div>
</div>
<p>We can create random permutations of a vector using the <code>sample()</code> function. Let’s use one of R’s built in vectors: <code>letters</code>.</p>
<ul>
<li>Type <code>letters</code> into the console, as below, and press RETURN/ENTER. You will see it contains all the lowercase letters of the English alphabet. Now, I bet you are wondering what <code>LETTERS</code> does, right?</li>
</ul>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" data-line-number="1">letters</a></code></pre></div>
<pre><code>##  [1] &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot; &quot;f&quot; &quot;g&quot; &quot;h&quot; &quot;i&quot; &quot;j&quot; &quot;k&quot; &quot;l&quot; &quot;m&quot; &quot;n&quot; &quot;o&quot; &quot;p&quot; &quot;q&quot;
## [18] &quot;r&quot; &quot;s&quot; &quot;t&quot; &quot;u&quot; &quot;v&quot; &quot;w&quot; &quot;x&quot; &quot;y&quot; &quot;z&quot;</code></pre>
<p>We can combine <code>base::sample()</code> with <code>letters</code> to put the letters into a random order:</p>
<ul>
<li>Run the below line. Run it again. And again. What do you notice? And why is our output different from yours? (The answer is below)</li>
</ul>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" data-line-number="1"><span class="kw">sample</span>(letters)</a></code></pre></div>
<pre><code>##  [1] &quot;y&quot; &quot;j&quot; &quot;v&quot; &quot;o&quot; &quot;h&quot; &quot;b&quot; &quot;z&quot; &quot;x&quot; &quot;c&quot; &quot;t&quot; &quot;a&quot; &quot;r&quot; &quot;p&quot; &quot;u&quot; &quot;n&quot; &quot;s&quot; &quot;f&quot;
## [18] &quot;d&quot; &quot;q&quot; &quot;e&quot; &quot;i&quot; &quot;w&quot; &quot;m&quot; &quot;k&quot; &quot;g&quot; &quot;l&quot;</code></pre>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>If <code>month.name</code> contains the names of the twelve months of the year, how many possible permutations are there of <code>sample(month.name)</code>? <select class='solveme' data-answer='["479001600"]'> <option></option> <option>1</option> <option>12</option> <option>144</option> <option>479001600</option></select></p>
<div class="solution">
<button>
Portfolio Point - Different samples with sample()
</button>
<div class="info">
<p>
Each time you run <code>sample(letters)</code> it will give you another random permutation of the sequence. That is what <code>sample()</code> does - creates a random permutation of the values you give it. Try repeating this command many times in the console. Because there are so many possible sequences, it is very unlikely that you will ever see the same sequence twice!
</p>
<p>
An interesting thing about <code>sample()</code> is that <code>sample(c(1,2,3,4))</code> is the same as <code>sample(4)</code>. And to recap, there would be 24 different permutations based on <code>factorial(4)</code>, meaning that each time you type <code>sample(4)</code> you are getting one of those 24 different orders. So what would factorial(12) be?
</p>
<p>
Top Tip: Remember that you can scroll up through your command history in the console using the up arrow on your keyboard; this way, you don’t ever have to retype a command you’ve already entered.
</p>
</div>
</div>
<p><br>
<span style="font-size: 18px; font-weight: bold; color: var(--blue);">Skill 2 out of 6 Complete!</span></p>
</div>
<div id="skill-3-creating-tibbles" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Skill 3: Creating Tibbles</h3>
<p>Tables are important because most of the data we want to analyze comes in a table, i.e. tabular form. There are different ways to get tabular data into R for analysis. One common way is to load existing data in from a data file (for example, using <code>readr::read_csv()</code> which you have seen before). But other times, you might want to just type in data directly. You can do this using the <code>tibble::tibble()</code> function. Being able to create a tibble is a useful data analysis skill because sometimes you will want to create some data on the fly just to try certain codes or functions.</p>
<div id="entering-data-into-a-tibble" class="section level4">
<h4><span class="header-section-number">5.2.3.1</span> Entering Data into a Tibble</h4>
<p>The <code>tibble()</code> function takes named arguments - this means that the name you give each argument within the tibble function, e.g. <code>Y = rnorm(10)</code> will be the name of the column that appears in the table, i.e. <code>Y</code>. It’s best to see how it works through an example.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" data-line-number="1"><span class="kw">tibble</span>(<span class="dt">Y =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>))</a></code></pre></div>
<pre><code>## # A tibble: 10 x 1
##          Y
##      &lt;dbl&gt;
##  1  1.32  
##  2  2.04  
##  3  0.0949
##  4  0.599 
##  5  0.412 
##  6  1.51  
##  7  0.932 
##  8  1.54  
##  9 -0.703 
## 10 -1.64</code></pre>
<p>The above command creates a new table with one column named <code>Y</code>, and the values in that column are the result of a call to <code>rnorm(10)</code>: 10 randomly sampled values from a standard normal distribution (mean = 0, sd = 1) - See Skill 1.</p>
<p>If, however, we wanted to sample from two different populations for <code>Y</code>, we could combine two calls to <code>rnorm()</code> within the <code>c()</code> function. Again this was in Skill 1, here we are now just storing it in a tibble. See below:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" data-line-number="1"><span class="kw">tibble</span>(<span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span> <span class="dv">-10</span>), </a>
<a class="sourceLine" id="cb178-2" data-line-number="2">             <span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span>  <span class="dv">20</span>)))</a></code></pre></div>
<pre><code>## # A tibble: 10 x 1
##         Y
##     &lt;dbl&gt;
##  1 -11.4 
##  2 -10.3 
##  3  -9.65
##  4  -8.76
##  5  -9.22
##  6  19.7 
##  7  21.5 
##  8  19.0 
##  9  19.1 
## 10  20.5</code></pre>
<p>Now we have sampled a total of 10 observations - the first 5 come from a group with a mean of -10, and the second 5 come from a group with a mean of 20. Try changing the values in the above example to get an idea of how this works. Maybe even add a third group!</p>
<p>But, of course, it would be good to know which population each data point refers to and so we should add some group names. We can do this with some additional trickery using the <code>rep()</code> function.</p>
</div>
<div id="repeating-values-to-save-typing" class="section level4">
<h4><span class="header-section-number">5.2.3.2</span> Repeating Values to Save Typing</h4>
<p>Before finalising our table, let’s learn a little about the base R function, <code>rep()</code>. This is most useful for automatically repeating values in order to save typing. For instance, if we wanted 20 letter “A”s in a row, we would type:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" data-line-number="1"><span class="kw">rep</span>(<span class="st">&quot;A&quot;</span>, <span class="dv">20</span>)</a></code></pre></div>
<pre><code>##  [1] &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot;
## [18] &quot;A&quot; &quot;A&quot; &quot;A&quot;</code></pre>
<p>The first argument to <code>rep()</code> is the vector containing the information you want repeated, <strong>A</strong>, and the second argument, <code>times</code>, is the number of times to repeat it; in this case <strong>20</strong>.</p>
<p>If you wanted to add more information, e.g. if the first argument has more than one element, say “A” and “B”, it will repeat the entire vector that number of times; A B, A B, A B, … . Note that we enclose “A” and “B” in the <code>c()</code> function so that it is seen as a single argument.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" data-line-number="1"><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="dv">20</span>)</a></code></pre></div>
<pre><code>##  [1] &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot;
## [18] &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot;
## [35] &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot;</code></pre>
<p>But sometimes we want a specific number of As followed by a specific number of Bs; A A A B B B. If the <code>times</code> argument has the same number of elements as the vector given for the first argument, it will repeat each element of the first vector as many times as given by the corresponding element in the <code>times</code> vector. In other words, for example, <code>times = c(2, 4)</code> for vector <code>c(&quot;A&quot;, &quot;B&quot;)</code> will give you 2 As followed by 4 Bs.</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" data-line-number="1"><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>))</a></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;A&quot; &quot;B&quot; &quot;B&quot; &quot;B&quot; &quot;B&quot;</code></pre>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>The best way to learn about this function is to play around with it in the console and see what happens. From the dropdown menus, the correct output of the following function would be:</p>
<ol style="list-style-type: decimal">
<li><p><code>rep(c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;),(2, 3, 1))</code> - <select class='solveme' data-answer='["A A B B B C"]'> <option></option> <option>A A A B B C</option> <option>A A B B B C</option> <option>A A B B C C</option> <option>A B C A B C</option></select></p></li>
<li><p><code>rep(1:5, 5:1)</code> - <select class='solveme' data-answer='["1 1 1 1 1 2 2 2 2 3 3 3 4 4 5"]'> <option></option> <option>1 2 3 4 5 1 2 3 4 5 1 2 3 4 5</option> <option>5 5 5 5 5 4 4 4 4 3 3 3 2 2 1</option> <option>1 1 1 1 1 2 2 2 2 3 3 3 4 4 5</option> <option>1 1 1 1 1 1 1 1 5 5 5 5 5 5 5</option></select></p></li>
</ol>
</div>
<div id="bringing-it-together-in-a-tibble" class="section level4">
<h4><span class="header-section-number">5.2.3.3</span> Bringing it Together in a Tibble</h4>
<p>Now we know <code>rep()</code>, we can complete our table of simulated data by combining what we’ve learned about generating random numbers and repeating values. We want our table to look like this:</p>
<pre><code>## # A tibble: 10 x 2
##    group      Y
##    &lt;chr&gt;  &lt;dbl&gt;
##  1 A      -9.55
##  2 A     -10.2 
##  3 A     -10.0 
##  4 A     -10.9 
##  5 A     -12.6 
##  6 B      20.7 
##  7 B      21.4 
##  8 B      19.0 
##  9 B      20.2 
## 10 B      21.3</code></pre>
<p>You now know how to create this table. Have a look at the code below and make sure you understand it. We have one column called <code>group</code> where we create <strong>A</strong>s and <strong>B</strong>s through <code>rep()</code>, and one column called <strong>Y</strong>, our data, all in our <code>tibble()</code>:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" data-line-number="1"><span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">5</span>)),</a>
<a class="sourceLine" id="cb187-2" data-line-number="2">       <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span> <span class="dv">-10</span>), <span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span>  <span class="dv">20</span>)))</a></code></pre></div>
<p>Be sure to play around with the code chunk to get used to it. Try adding a third group or even a third column? Perhaps you want to give every participant a random age with a mean of 18, and an sd of 1; or even a participant number.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Try <code>row_number()</code> to create participant numbers.
</p>
</div>
</div>
<p><br>
Don’t forget, if you wanted to store your tibble, you would just assign it to a name, such as <code>my_data</code>:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" data-line-number="1">my_data &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">ID =</span> <span class="kw">row_number</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>), </a>
<a class="sourceLine" id="cb188-2" data-line-number="2">                    <span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">5</span>)),</a>
<a class="sourceLine" id="cb188-3" data-line-number="3">                    <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span> <span class="dv">-10</span>), <span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span>  <span class="dv">20</span>)),</a>
<a class="sourceLine" id="cb188-4" data-line-number="4">                    <span class="dt">Age =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">18</span>, <span class="dv">1</span>))</a></code></pre></div>
<p><br>
<span style="font-size: 18px; font-weight: bold; color: var(--blue);">Skill 3 out of 6 Complete!</span></p>
</div>
</div>
<div id="skill-4-computing-differences-in-group-means" class="section level3">
<h3><span class="header-section-number">5.2.4</span> Skill 4: Computing Differences in Group Means</h3>
<p>You have already learned how to calculate group means using <code>group_by()</code> and <code>summarise()</code>. For example, you might want to calculate sample means for a randomly generated dataset like so:</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" data-line-number="1">my_data &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">20</span>)),</a>
<a class="sourceLine" id="cb189-2" data-line-number="2">                  <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">20</span>,  <span class="dv">20</span>, <span class="dv">5</span>), <span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dv">-20</span>, <span class="dv">5</span>)))</a>
<a class="sourceLine" id="cb189-3" data-line-number="3"></a>
<a class="sourceLine" id="cb189-4" data-line-number="4">my_data_means &lt;-<span class="st"> </span>my_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb189-5" data-line-number="5"><span class="st">  </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb189-6" data-line-number="6"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y))</a>
<a class="sourceLine" id="cb189-7" data-line-number="7"></a>
<a class="sourceLine" id="cb189-8" data-line-number="8">my_data_means</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   group     m
##   &lt;chr&gt; &lt;dbl&gt;
## 1 A      21.4
## 2 B     -19.5</code></pre>
<p>Sometimes what we want though is to calculate <strong>the differences between means</strong> rather than just the means; so we’d like to subtract the second group mean -19.5 from the first group mean of 21.4, to get a single value, the difference: 40.8.</p>
<p>We can do this using the <code>dplyr::pull()</code> and <code>purrr::pluck()</code> functions. <code>pull()</code> will extract a single column from a dataframe and turn it into a vector. <code>pluck()</code> then allows you to pull out an element (i.e. a value or values) from within that vector.</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" data-line-number="1">vec &lt;-<span class="st"> </span>my_data_means <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb191-2" data-line-number="2"><span class="st">  </span><span class="kw">pull</span>(m)</a>
<a class="sourceLine" id="cb191-3" data-line-number="3"></a>
<a class="sourceLine" id="cb191-4" data-line-number="4">vec</a></code></pre></div>
<pre><code>## [1]  21.36420 -19.46171</code></pre>
<p>We have now created <code>vec</code> which is a vector containing only the group means; the rest of the information in the table has been discarded. Now that we have <code>vec</code>, we can calculate the mean difference as below, where <code>vec</code> is our vector of the two means and <code>[1]</code> and <code>[2]</code> refer to the two means:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" data-line-number="1">vec[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>vec[<span class="dv">2</span>]</a></code></pre></div>
<pre><code>## [1] 40.82591</code></pre>
<p>But <code>pluck()</code> is also useful, and can be written as so:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" data-line-number="1"><span class="kw">pluck</span>(vec, <span class="dv">1</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pluck</span>(vec, <span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 40.82591</code></pre>
<p>It can also be incorporated into a pipeline, as below, where we still <code>pull()</code> the means column, <code>m</code>, and then <code>pluck()</code> each value in turn and subtract them from each other.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" data-line-number="1"><span class="co">## whole thing in a pipeline</span></a>
<a class="sourceLine" id="cb197-2" data-line-number="2">my_data_means <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(m) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pluck</span>(<span class="dv">1</span>) <span class="op">-</span></a>
<a class="sourceLine" id="cb197-3" data-line-number="3"><span class="st">  </span>my_data_means <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(m) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pluck</span>(<span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 40.82591</code></pre>
<p>However, there is an alternative way to extract the difference between means which may make more intuitive sense. You already know how to calculate a difference between values in the same row of a table using <code>dplyr::mutate()</code>, e.g. <code>mutate(new_column = column1 minus column2)</code>. So if you can get the observations in <code>my_data_means</code> into the same row, different columns, you could then use <code>mutate()</code> to calculate the difference. Previously you learned <code>gather()</code> to bring columns together. Well the opposite of gather is the <code>tidyr::spread()</code> function to split columns apart - as below.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" data-line-number="1">my_data_means <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-2" data-line-number="2"><span class="st">  </span><span class="kw">spread</span>(group, m)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##       A     B
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  21.4 -19.5</code></pre>
<p>The spread function (<code>?spread</code>) splits the data in column <code>m</code> by the information, i.e. labels, in column <code>group</code> and puts the data into separate columns. A call to <code>spread()</code> followed by a <code>mutate()</code> can be used to calculate the difference in means - see below:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" data-line-number="1">my_data_means <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb201-2" data-line-number="2"><span class="st">  </span><span class="kw">spread</span>(group, m) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb201-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> A <span class="op">-</span><span class="st"> </span>B) </a></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##       A     B  diff
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  21.4 -19.5  40.8</code></pre>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>What is the name of the column containing the differences between the means of A and B? <select class='solveme' data-answer='["diff"]'> <option></option> <option>means</option> <option>group</option> <option>m</option> <option>diff</option></select></p>
<p>Finally, if you then wanted to just get <code>diff</code> and throw away everything else in the table:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" data-line-number="1">my_data_means <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb203-2" data-line-number="2"><span class="st">  </span><span class="kw">spread</span>(group, m) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb203-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> A <span class="op">-</span><span class="st"> </span>B) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb203-4" data-line-number="4"><span class="st">  </span><span class="kw">pull</span>(diff)</a></code></pre></div>
<pre><code>## [1] 40.82591</code></pre>
<div class="solution">
<button>
Portfolio Point - Reading pipes and verbalising tasks
</button>
<div class="info">
<p>
Keep in mind that a very useful technique for establishing what you want to do to a dataframe is to verbalise what you need, or to write it down in words, or to say it out loud. Take this last code chunk. What we wanted to do was to <code>spread()</code> the data in <code>m</code> into the groups A and B. Then we wanted to <code>mutate()</code> a new column that is the difference, <code>diff</code>, of A minus B. And finally we wanted to <code>pull()</code> out the value in <code>diff</code>.
</p>
<p>
Often step 1 of writing code or understanding code is knowing what it is you want to do in the first place. After that, you just need the correct functions. Fortunately for us, <code>tidyverse</code> names its functions based on what they specifically do!
</p>
</div>
</div>
<p><br>
<span style="font-size: 18px; font-weight: bold; color: var(--blue);">Skill 4 out of 6 Complete!</span></p>
</div>
<div id="skill-5-creating-your-own-functions" class="section level3">
<h3><span class="header-section-number">5.2.5</span> Skill 5: Creating Your Own Functions</h3>
<p>In Skills 1 to 4, we have looked at creating and sampling data, storing it in a tibble, and extracting information from that tibble. Now, say we wanted to do this over and over again. For instance, we might want to generate 100 random datasets just like the one in Skill 4. It would be a pain to have to type out the <code>tibble()</code> function 100 times or even to copy and paste it 100 times. We’d likely make an error somewhere and it would be hard to read. To help us, we can create a custom function that performs the action you want; in our case, creating a tibble of random data.</p>
<p>Remember, a function is just a procedure that takes an input and gives you the same output each time - like a toaster! A function has the following format:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" data-line-number="1">name_of_function &lt;-<span class="st"> </span><span class="cf">function</span>(arg1, arg2, arg3) {</a>
<a class="sourceLine" id="cb205-2" data-line-number="2">  <span class="co">## body of function goes between these curly brackets; i.e. what the function does for you.</span></a>
<a class="sourceLine" id="cb205-3" data-line-number="3">  <span class="co">## Note that the last value calculated will be returned if you call the function.</span></a>
<a class="sourceLine" id="cb205-4" data-line-number="4">}</a></code></pre></div>
<p>First, you define your own function name (e.g. <code>name_of_function</code>) and define the names of the arguments it will take (<code>arg1</code>, <code>arg2</code>, …) - an argument is the information that you feed into your function, e.g. data. Finally, you state the calculations or actions of the function in the body of the function (the portion that appears between the curly braces).</p>
<p>One of the most basic possible functions is one that takes no arguments and just prints a message. Here is an example:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" data-line-number="1">hello &lt;-<span class="st"> </span><span class="cf">function</span>() {</a>
<a class="sourceLine" id="cb206-2" data-line-number="2">  <span class="kw">print</span>(<span class="st">&quot;Hello World!&quot;</span>)</a>
<a class="sourceLine" id="cb206-3" data-line-number="3">}</a></code></pre></div>
<p>So this function is called <code>hello</code>. It can be run by typing <code>hello()</code> in your console and it will give the output of <code>Hello World!</code> every single time you run it; it has no other actions or information. Test this in the console now by typing:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" data-line-number="1"><span class="kw">hello</span>()</a></code></pre></div>
<pre><code>## [1] &quot;Hello World!&quot;</code></pre>
<p>Awesome right? Ok, so not very exciting. Let’s make it better by adding an argument, <code>name</code>, and have it say Hello to <code>name</code>.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" data-line-number="1">hello &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;World!&quot;</span>) {</a>
<a class="sourceLine" id="cb209-2" data-line-number="2">  <span class="kw">paste</span>(<span class="st">&quot;Hello&quot;</span>, name)</a>
<a class="sourceLine" id="cb209-3" data-line-number="3">}</a></code></pre></div>
<p>This new function is again called <code>hello()</code> and replaces the one you previously created. This time however you are supplying what is called a default argument, `name = “World!”, but it still has the same action as the previous function of putting “Hello” and “World!” together. So if you run it you get “Hello World!”. Try it yourself!</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" data-line-number="1"><span class="kw">hello</span>()</a></code></pre></div>
<pre><code>## [1] &quot;Hello World!&quot;</code></pre>
<p>The difference this time however is that because you have added an argument to the input, you can change the information you give the argument and therefore change the output of the function. More flexible. More exciting.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>Test your understanding by answering these questions:</p>
<ul>
<li><p>Typing <code>hello(&quot;Phil&quot;)</code> in the console with this new function will give: <select class='solveme' data-answer='["Hello Phil"]'> <option></option> <option>Hello Heather</option> <option>Hello Phil</option> <option>Hello Niamh</option> <option>Hello Kevin</option></select></p></li>
<li><p>Typing the argument as <code>&quot;is it me you are looking for&quot;</code> will give: <select class='solveme' data-answer='["Hello is it me you are looking for"]'> <option></option> <option>Hello is it me you are looking for</option> <option>I just called to say Hello</option> <option>You had me at Hello</option> <option>Hello seems to be the hardest word</option></select></p></li>
<li><p>What argument would you type to get “Hello Dolly!” as the output: <select class='solveme' data-answer='["Dolly!"]'> <option></option> <option>Dolly</option> <option>Molly</option> <option>Holly</option> <option>Dolly!</option></select></p></li>
</ul>
<p>Most of the time however we want to create a function that computes a value or constructs a table. For instance, let’s create a function that returns randomly generated data from two samples, as we learned in the previous skills - see below. All we are doing is taking the tibble we created in Skill 4 and putting it in the body (between the curly brackets) of the function.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" data-line-number="1">gen_data &lt;-<span class="st"> </span><span class="cf">function</span>() {</a>
<a class="sourceLine" id="cb212-2" data-line-number="2">  <span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">20</span>)),</a>
<a class="sourceLine" id="cb212-3" data-line-number="3">                  <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">20</span>,  <span class="dv">20</span>, <span class="dv">5</span>), <span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dv">-20</span>, <span class="dv">5</span>)))</a>
<a class="sourceLine" id="cb212-4" data-line-number="4">}</a></code></pre></div>
<p>This function is called <code>gen_data()</code> and when we run it we get a randomly generated table of two groups, each with 20 people, one with M = 20, SD = 5, the other with M = -20, sd = 5. Try running this <code>gen_data()</code> function in the console a few times; remember that as the data is random, the numbers will be different each time you run it.</p>
<p>But say we want to modify the function to allow us to get a table with smaller or larger numbers of observations per group. We can add an argument <code>n</code> and modify the code as follows. Create this function and run it a couple of times through <code>gen_data()</code>. The way to think about this is that every place that <code>n</code> appears in the body of the function (between the curly brackets) it will have the value of whatever you gave it in the arguments, i.e. in this case, 20.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" data-line-number="1">gen_data &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">n =</span> <span class="dv">20</span>) {</a>
<a class="sourceLine" id="cb213-2" data-line-number="2">  <span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(n, n)),</a>
<a class="sourceLine" id="cb213-3" data-line-number="3">                  <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(n,  <span class="dv">20</span>, <span class="dv">5</span>), <span class="kw">rnorm</span>(n, <span class="dv">-20</span>, <span class="dv">5</span>)))</a>
<a class="sourceLine" id="cb213-4" data-line-number="4">}</a></code></pre></div>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li><p>How many total participants would there be if you ran <code>gen_data(2)</code>? <select class='solveme' data-answer='["4"]'> <option></option> <option>2</option> <option>4</option> <option>20</option> <option>40</option></select></p></li>
<li><p>What would you type to get 100 participants per group? <select class='solveme' data-answer='["gen_data(100)"]'> <option></option> <option>gen_data(50)</option> <option>gen_data(10)</option> <option>gen_dota(100)</option> <option>gen_data(100)</option></select></p></li>
</ul>
<p><strong>Challenge Question:</strong></p>
<p>Keeping in mind that functions can take numerous arguments, and that each group in your function have separate means, can you modify the function <code>gen_data</code> to allow the user to change the means for the two calls to <code>rnorm</code>? Have a try before revealing the solution below.</p>
<div class="solution">
<button>
Solution To Challenge Question
</button>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" data-line-number="1">gen_data &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">m1 =</span> <span class="dv">20</span>, <span class="dt">m2 =</span> <span class="dv">-20</span>) {</a>
<a class="sourceLine" id="cb214-2" data-line-number="2">  <span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(n, n)),</a>
<a class="sourceLine" id="cb214-3" data-line-number="3">                  <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(n,  m1, <span class="dv">5</span>), <span class="kw">rnorm</span>(n, m2, <span class="dv">5</span>)))</a>
<a class="sourceLine" id="cb214-4" data-line-number="4">}</a>
<a class="sourceLine" id="cb214-5" data-line-number="5"></a>
<a class="sourceLine" id="cb214-6" data-line-number="6"><span class="co"># m1 is the mean of group A</span></a>
<a class="sourceLine" id="cb214-7" data-line-number="7"><span class="co"># m2 is mean of group B</span></a>
<a class="sourceLine" id="cb214-8" data-line-number="8"></a>
<a class="sourceLine" id="cb214-9" data-line-number="9"><span class="co"># The function would be called by: gen_data(20, 20, -20)</span></a>
<a class="sourceLine" id="cb214-10" data-line-number="10"><span class="co"># Giving 20 participants in each group, </span></a>
<a class="sourceLine" id="cb214-11" data-line-number="11"><span class="co"># The first group having a mean of 20, </span></a>
<a class="sourceLine" id="cb214-12" data-line-number="12"><span class="co"># The second group having a mean of -20. </span></a>
<a class="sourceLine" id="cb214-13" data-line-number="13"></a>
<a class="sourceLine" id="cb214-14" data-line-number="14"><span class="co"># Likewise, a call of: gen_data(4, 10, 5)</span></a>
<a class="sourceLine" id="cb214-15" data-line-number="15"><span class="co"># Would give two groups of 4, </span></a>
<a class="sourceLine" id="cb214-16" data-line-number="16"><span class="co"># The first having a mean of 10, </span></a>
<a class="sourceLine" id="cb214-17" data-line-number="17"><span class="co"># The second having a mean of 5.</span></a></code></pre></div>
</div>
<div class="solution">
<button>
Portfolio Point - Two important facts about functions
</button>
<div class="info">
<p>
Here are two important things to understand about functions.
</p>
<ol style="list-style-type: decimal">
<li>
<p>
<strong>Functions obey lexical scoping.</strong> What does this mean? It’s like what they say about Las Vegas: what happens in the function, stays in the function. Any variables created inside of a function will be discarded after the function executes and will not be accessible to the outside calling process. So if you have a line, say a variable <code>my_var &lt;- 17</code> inside of a function, and try to print <code>my_var</code> from outside of the function, you will get an error: <code>object ‘my_var’ not found</code>. Although the function can ‘read’ variables from the environment that are not passed to it through an argument, it cannot change them. So you can only write a function to return a value, not change a value.
</p>
</li>
<li>
<p>
<strong>Functions return the last value that was computed.</strong> You can compute many things inside of a function but only the last thing that was computed will be returned as part of the calling process. If you want to return <code>my_var</code>, which you computed earlier but not as the final computation, you can do so explicitly using <code>return(my_var)</code> at the end of the function (before the second curly bracket).
</p>
</li>
</ol>
</div>
</div>
<p><br>
<span style="font-size: 18px; font-weight: bold; color: var(--blue);">Skill 5 out of 6 Complete!</span></p>
</div>
<div id="skill-6-replicating-operations" class="section level3">
<h3><span class="header-section-number">5.2.6</span> Skill 6: Replicating Operations</h3>
<p>The last skill you will need for the upcoming lab is knowing how to repeat an action (or expression) multiple times. You saw this in Lab 4 so we will only briefly recap here. Here, we use the base function <code>replicate()</code>. For instance, say you wanted to calculate the mean from <code>rnorm(100)</code> ten times, you could write it like this:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" data-line-number="1"><span class="co">## bad way</span></a>
<a class="sourceLine" id="cb215-2" data-line-number="2"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb215-3" data-line-number="3"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb215-4" data-line-number="4"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb215-5" data-line-number="5"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb215-6" data-line-number="6"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb215-7" data-line-number="7"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb215-8" data-line-number="8"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb215-9" data-line-number="9"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb215-10" data-line-number="10"><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</a></code></pre></div>
<p>But it’s far easier and more readable to wrap the expression in the <code>replicate()</code> function where the first argument is the number of times you want to repeat the expression stated as the second argument, i.e. <code>replicate(times, expression)</code>. Below, we replicate the mean of 100 randomly generated numbers from the normal distribution, and we do this 10 times:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" data-line-number="1"><span class="kw">replicate</span>(<span class="dv">10</span>, <span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>())</a></code></pre></div>
<p>Also you’ll probably want to store the results in a variable, for example, <code>ten_samples</code>:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb217-1" data-line-number="1">ten_samples &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">10</span>, <span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>())</a>
<a class="sourceLine" id="cb217-2" data-line-number="2">ten_samples</a></code></pre></div>
<pre><code>##  [1] -0.11098848  0.01725155 -0.29229780 -0.05934204 -0.07037653
##  [6] -0.03581338  0.03356190 -0.14416740 -0.03456241 -0.03005085</code></pre>
<p>Each element (value) of the vector within <code>ten_samples</code> is the result of a single call to <code>rnorm(100) %&gt;% mean()</code>.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>Assuming that your <code>hello()</code> function from Skill 5 still exists, and it takes the argument <code>name = Goodbye</code>, what would happen in the console if you wrote, <code>replicate(1000, hello(&quot;Goodbye&quot;))</code>? <select class='solveme' data-answer='["Hello Goodbye would appear a thousand times"]'> <option></option> <option>Hello World would appear a thousand times</option> <option>hello Goodbye would appear a thousand times</option> <option>Hello Goodbye would appear a thousand times</option></select> - Try it and see if it works!</p>
<div class="solution">
<button>
Solution To Quickfire Question
</button>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb219-1" data-line-number="1"><span class="co"># the function would be:</span></a>
<a class="sourceLine" id="cb219-2" data-line-number="2">hello &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;World!&quot;</span>){</a>
<a class="sourceLine" id="cb219-3" data-line-number="3">  <span class="kw">paste</span>(<span class="st">&quot;Hello&quot;</span>, name)</a>
<a class="sourceLine" id="cb219-4" data-line-number="4">}</a>
<a class="sourceLine" id="cb219-5" data-line-number="5"></a>
<a class="sourceLine" id="cb219-6" data-line-number="6"><span class="co"># and would be called by:</span></a>
<a class="sourceLine" id="cb219-7" data-line-number="7"><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">hello</span>(<span class="st">&quot;Goodbye&quot;</span>))</a></code></pre></div>
</div>
<p><br></p>
<p><span style="font-size: 18px; font-weight: bold; color: var(--blue);">Skill 6 out of 6 Complete!</span></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span></p>
<p>To recap, we have shown you the following six skills:</p>
<ul>
<li>Skill 1: Generating random numbers with <code>base::rnorm()</code></li>
<li>Skill 2: Permuting values with <code>base::sample()</code><br />
</li>
<li>Skill 3: Creating a “tibble” (a type of data table) using <code>tibble::tibble()</code></li>
<li>Skill 4: Computing and extracting a difference in group means using <code>dplyr::pull()</code> and <code>purrr::pluck()</code></li>
<li>Skill 5: Creating your own custom functions using <code>base::function()</code></li>
<li>Skill 6: Repeating operations using <code>base::replicate()</code></li>
</ul>
<p>You will need these skills in the coming lab to help you perform a real <strong>permutation test</strong>. Through these skills and the permutation test you will learn about null hypothesis significance testing. If you have any questions please post them on the Moodle forum or the slack forum <a href = "https://rguppies.slack.com/" target = "_blank">rguppies.slack.com</a> under the channel <strong>#level2_2018</strong>. Finally, don’t forget to add any useful information to your Portfolio before you leave it too long and forget.</p>
<p>Great work today. That is all for now. See you in the lab!</p>

</div>
</div>
<div id="inclass-activity-2" class="section level2">
<h2><span class="header-section-number">5.3</span> InClass Activity</h2>
<div id="permutation-tests-of-hypotheses" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Permutation Tests of Hypotheses</h3>
<p>A common statistical question when comparing two groups might be, “<strong>Is there a real difference between the group means?</strong>” From this we can establish two contrasting hypotheses:</p>
<ol style="list-style-type: decimal">
<li>The <strong>null hypothesis</strong> which states that the group means <strong>are equivalent</strong> and is written as: <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>
<ul>
<li>where <span class="math inline">\(\mu_1\)</span> is the population mean of group 1</li>
<li>and <span class="math inline">\(\mu_2\)</span> is the population mean of group 2<br />
</li>
</ul></li>
<li>Or the <strong>alternative hypothesis</strong> which states that the group means <strong>are not equivalent</strong> and is written as: <span class="math inline">\(H_1: \mu_1 \ne \mu_2\)</span>.</li>
</ol>
<p>Using the techniques you read about in the PreClass and in previous labs, today you will learn how to test the null hypothesis of no difference between two independent groups. We will first do this using a <strong>permutation test</strong> before looking at other tests in later labs.</p>
<p>A permutation test is a basic inferential procedure that involves a reshuffling of group labels or values to create new possible outcomes of the data you collected to see how your original mean difference compares to a distribution of possible outcomes. The test can in fact be applied in many situations, this is just one, and it provides a good starting place for understanding hypothesis testing. The steps for the exercise below, and really the logic of a permutation test for two independent groups, are:</p>
<ol style="list-style-type: decimal">
<li>Calculate the real difference <span class="math inline">\(D_{orig}\)</span> between the means of two groups (e.g. Mean of A minus Mean of B).</li>
<li>Randomly shuffle the group labels (i.e. which group each participant belonged to - A or B) and re-calculate the difference, <span class="math inline">\(D&#39;\)</span>.</li>
<li>Repeat step 2 <span class="math inline">\(N_{r}\)</span> times, where <span class="math inline">\(N_r\)</span> is a large number (typically greater than 1000), storing each <span class="math inline">\(D_i&#39;\)</span> value to form a null hypothesis distribution.</li>
<li>Locate the difference you observed in step 1 (the real difference) on the null hypothesis distribution of possible differences.</li>
<li>Decide whether the original difference is sufficiently extreme to reject the null hypothesis of no difference (<span class="math inline">\(H_0\)</span>).</li>
</ol>
<p>This logic works because if the null hypothesis is true (there is no difference between the groups) then the labeling of the observations/participants into groups is arbitrary, and we can rearrange the labels in order to estimate the likelihood of our original difference under the <span class="math inline">\(H_0\)</span>. In other words, if you know the original value of the difference between two groups (or the true difference) falls in the middle of your permuted distribution then there is no significant difference between the two groups. If, however, the original difference falls in the tail of the permuted distribution then there might be a significant difference depending on how far into the tail it falls.</p>
<p>Let’s get started!</p>
</div>
<div id="Ch5InClassQueT1" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Step 1: Load in Add-on Packages and Data</h3>
<p>1.1. Open a new script and call <code>tidyverse</code> into your library.</p>
<p>1.2. Now type the statement <code>set.seed(1011)</code> at the top of your script after your library call and run it. (This ‘seeds’ the random number generator so that you will get the same results as everyone else. The number 1011 is a bit random but if everyone uses it then we all get the same outcome. Different seeds give different outcomes)</p>
<p>Note: This lab was written under RVersion 3.6.1. If you use a different RVersion (e.g. R 3.5.1) or set a different seed (e.g. <code>1012</code>) you may get different results.</p>
<p>1.3. <a href="data/05-s01/inclass/ch5-inclass-data.zip">Download the data file from here</a> and read the data in <code>perm_data.csv</code> into a variable called <code>dat</code>.</p>
<p>1.4. Let’s give every participant a participant number by adding a new column to <code>dat</code>. Something like this would work: <code>mutate(subj_id = row_number())</code></p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
1.1 - Something to do with <code>library()</code>
</p>
<p>
1.2 - <code>set.seed(1011)</code>
</p>
<p>
1.3 - Something to do with <code>read_csv()</code>
</p>
<p>
1.4 - pipe (<code>%&gt;%</code>) <code>dat</code> into the mutate line shown
</p>
</div>
</div>
<div class="solution">
<button>
Portfolio Point - Different uses of row_number
</button>
<div class="info">
<p>
You will see that, in the example here, to put a row number for each of the participants we do not have to state the number of participants we have. In the Preclass however, we did. What is the difference? Well, in the Preclass we were making a tibble and trying to create a column in that tibble using <code>row_numbers</code>. If you want to do that you have to state the number of rows, e.g. <code>1:20</code>. However, in this example in the lab today the tibble already exists, we are just adding to it. If that is the case then you can just mutate on a column of row numbers without stating the number of participants. In summary:
</p>
<ul>
<li>
When creating the tibble, state the number of participants in <code>row_numbers()</code>.
</li>
<li>
If tibble already exists, just mutate on <code>row_numbers()</code>. No need for specific numbers.
</li>
</ul>
</div>
</div>
<p>Have a look at the resulting tibble, <code>dat</code>.</p>
<pre><code>## # A tibble: 100 x 3
##    group     Y subj_id
##    &lt;chr&gt; &lt;dbl&gt;   &lt;int&gt;
##  1 A     113.        1
##  2 A      91.0       2
##  3 A      89.2       3
##  4 A     110.        4
##  5 A     118.        5
##  6 A     104.        6
##  7 A     100.        7
##  8 A      94.1       8
##  9 A      94.8       9
## 10 A      92.5      10
## # ... with 90 more rows</code></pre>
<ul>
<li>The column <code>Y</code> is your dependent variable (DV)</li>
<li>The column <code>group</code> is your independent variable (IV).</li>
<li>The column <code>subj_id</code> is the participant number.</li>
</ul>
</div>
<div id="Ch5InClassQueT2" class="section level3">
<h3><span class="header-section-number">5.3.3</span> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></h3>
<p>We now need to write a pipeline of five functions (i.e. commands) that calculates the mean difference between the groups in <code>dat</code>, Group A minus Group B. Broken down into steps this would be:</p>
<p>2.1.1. Use a pipe of two <code>dplyr</code> one-table verbs (e.g. Lab 2) to create a tibble where each row contains the mean of one of the groups. Name the column storing the means as <code>m</code>.</p>
<p>2.1.2. Continue the pipe to <code>spread()</code> your data from long to wide format, based on the columns <code>group</code> and <code>m</code>.</p>
<p>2.1.3. Now add a pipe that <strong>creates</strong> a new column in this wide dataset called <code>diff</code> which is the value of group A’s mean minus group B’s mean.</p>
<p>2.1.4. Pull out the value in <code>diff</code> (the mean of group A minus the mean of group B) to finish the pipe.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
<code>dat %&gt;%</code>
</p>
<p>
<code>group_by(?) %&gt;%</code>
</p>
<p>
<code>summarise(m = ?) %&gt;%</code>
</p>
<p>
<code>spread(group, m) %&gt;%</code>
</p>
<p>
<code>mutate(diff = ? - ?) %&gt;%</code>
</p>
<p>
<code>pull(?)</code>
</p>
</div>
</div>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li>Check that your value for <code>d_orig</code> is correct, without using the solution, by typing your <code>d_orig</code> value to two decimal places in the box. Include the sign, e.g. -1.23. The box will go green if you are correct. <input class='solveme nospaces' size='10' data-answer='["-7.39"]'/></li>
</ul>
<p>The above steps have created a pipeline of five functions to get one value. Nice! We now need to turn this into a function because we are going to be permuting the data set (specifically the grouping labels) and re-calculating the difference many, many times.</p>
<p>2.2. Wrap your pipeline in a function called <code>calc_diff</code> but swap <code>dat</code> for <code>x</code>. This function will take a single argument named <code>x</code>, where <code>x</code> is the tibble that you want to calculate group means from. As in the previous step, the function will return a single value which is the difference between the group means. The start will look like this below:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" data-line-number="1">calc_diff &lt;-<span class="st"> </span><span class="cf">function</span>(x){</a>
<a class="sourceLine" id="cb221-2" data-line-number="2">  x <span class="op">%&gt;%</span>.....</a>
<a class="sourceLine" id="cb221-3" data-line-number="3">}</a></code></pre></div>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" data-line-number="1">calc_diff &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb222-2" data-line-number="2">  x <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb222-3" data-line-number="3"><span class="st">    </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb222-4" data-line-number="4"><span class="st">    </span>the_rest_of_your_pipe...</a>
<a class="sourceLine" id="cb222-5" data-line-number="5">}</a></code></pre></div>
</div>
<p>2.3. Now call your new function where <code>x</code> = <code>dat</code> as the argument and store the result in a new variable called <code>d_orig</code>. Make sure that your function returns the same value as you got above and that your function returns a single value rather than a tibble. You can test this: <code>is.tibble(d_orig)</code> should give you <code>FALSE</code> and <code>is.numeric(d_orig)</code> should give you <code>TRUE</code>.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" data-line-number="1">d_orig &lt;-<span class="st"> </span><span class="kw">function_name</span>(<span class="dt">x =</span> data_name) </a>
<a class="sourceLine" id="cb223-2" data-line-number="2"><span class="co"># or</span></a>
<a class="sourceLine" id="cb223-3" data-line-number="3">d_orig &lt;-<span class="st"> </span><span class="kw">function_name</span>(data_name)</a>
<a class="sourceLine" id="cb223-4" data-line-number="4"></a>
<a class="sourceLine" id="cb223-5" data-line-number="5"><span class="co"># Then type the following in the Console and look at the answer:</span></a>
<a class="sourceLine" id="cb223-6" data-line-number="6"></a>
<a class="sourceLine" id="cb223-7" data-line-number="7"><span class="kw">is.tibble</span>(d_orig)</a>
<a class="sourceLine" id="cb223-8" data-line-number="8"><span class="co"># True (is a tibble) or False (is not a tibble)</span></a>
<a class="sourceLine" id="cb223-9" data-line-number="9"></a>
<a class="sourceLine" id="cb223-10" data-line-number="10"><span class="kw">is.numeric</span>(d_orig)</a>
<a class="sourceLine" id="cb223-11" data-line-number="11"><span class="co"># True (is numeric) or False (is not numeric; it is a character or integer instead.)</span></a></code></pre></div>
</div>
<p>So we now have the original difference between the groups stored in <code>d_orig</code>. Next we need to create a distribution of possible differences to see where our original difference lies in this distribution. But first we need to shuffle the <code>group</code> letters (A or B) in our dataset and find the difference…a few hundred times!</p>
</div>
<div id="Ch5InClassQueT3" class="section level3">
<h3><span class="header-section-number">5.3.4</span> Step 3: Permute the Group Labels</h3>
<p>3.1. Create a new function called <code>permute()</code> that takes as input a dataset <code>x</code> and returns the same dataset transformed such that the group labels (the values in the column <code>group</code>) are shuffled: started below for you. This will require using the <code>sample()</code> function within a <code>mutate()</code>. You have used <code>mutate()</code> twice already today and you saw how to <code>sample()</code> <strong>letters</strong> in the PreClass.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" data-line-number="1">permute &lt;-<span class="st"> </span><span class="cf">function</span>(x){</a>
<a class="sourceLine" id="cb224-2" data-line-number="2">  x <span class="op">%&gt;%</span>.....</a>
<a class="sourceLine" id="cb224-3" data-line-number="3">}</a></code></pre></div>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Might be easier to think of these steps in reverse.
</p>
<ol style="list-style-type: decimal">
<li>
<p>
Start with a <code>mutate()</code> function that rewrites the column <code>group</code> every time you run it, e.g. <code>dat %&gt;% mutate(variable = sample(variable))</code>
</p>
</li>
<li>
<p>
Now put that into your <code>permute()</code> function making the necessary adjustments to the code so it starts <code>x %&gt;%…</code>. Again <code>x</code> should be in the function and not <code>dat</code>. &quot;)
</p>
</li>
</ol>
</div>
</div>
<p>3.2. Try out your new <code>permute()</code> function by calling it on <code>dat</code> (i.e. <code>x = dat</code>) a few times. You should see the group labels in the <code>group</code> column changing randomly. The most common mistake is that people mutate a new column by mispelling <code>group</code>. You want to overwrite/change the information in the <code>group</code> column not make a new one, so be careful with the spelling.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--pink);">Group Discussion Point</span></p>
<p>Now would be an excellent time to spend five minutes as a group recapping what you are doing.</p>
<ul>
<li>You have the original difference between groups.</li>
<li>You have a function that calculates and stores this difference.</li>
<li>You have a function that reshuffles the labels of the group.</li>
</ul>
<p>Do you understand why? If not, go back to the principles of the permutation test at the start of the lab then read on…</p>
</div>
<div id="Ch5InClassQueT4" class="section level3">
<h3><span class="header-section-number">5.3.5</span> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</h3>
<p>Now that we have the original difference and our two functions, one to shuffle group labels and one to calculate the difference between two groups, we need to actually create the distribution of possible differences and see where the original difference lies in it.</p>
<p>4.1.1. Write a <strong>a single pipeline</strong> that takes <code>dat</code> as the input, permutes the group labels with a call to your function <code>permute()</code>, and then calculates the difference in means between these new groups with a call to your function <code>calc_diff()</code>.</p>
<p>4.1.2. Run this line manually a few times and watch the resulting value change as the labels get permuted.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Think about verbalising your pipelines. In a single pipeline:
</p>
<ol style="list-style-type: decimal">
<li>
I want to permute the data into two new groups.
</li>
<li>
Then I want to calculate the difference between these two new groups.
</li>
</ol>
<p>
The functions you have created do these steps. You just have to put them in order and pipe the data through it.
</p>
</div>
</div>
<p>4.2. Now take your pipeline of functions and repeat it 1000 times using the <code>replicate()</code> function. Store the output in a variable called <code>nhd</code>. <code>nhd</code> will contain 1000 values where each value is the mean difference of each of the 1000 random permutations of the data. (<strong>Warning:</strong> This will probably take a while to run, perhaps 10 seconds.)</p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb225-1" data-line-number="1"><span class="co"># replace expression with the pipeline you created in 4.1.1</span></a>
<a class="sourceLine" id="cb225-2" data-line-number="2">nhd &lt;-<span class="st"> </span><span class="kw">replicate</span>(times, expression)</a></code></pre></div>
</div>
<p>You now have 1000 possible values of the difference between the permuted groups A and B - your permuted distribution.</p>
<p>4.3 Let’s visualise this distribution through a frequency histogram of the values in <code>nhd</code>. This shows us the likelihood of various mean differences under <span class="math inline">\(H_0\)</span>. One thing to note however is that <code>nhd</code> is not a <code>tibble</code> and <code>ggplot</code> needs it to be a <code>tibble</code>. You need to convert it. You might start by do something like:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> <span class="kw">tibble</span>(<span class="dt">x =</span> <span class="ot">NULL</span>), <span class="kw">aes</span>(x)) <span class="op">+</span><span class="st"> </span><span class="ot">NULL</span></a></code></pre></div>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Remember that <code>ggplot</code> works as: <code>ggplot(data, aes(x)) + geom…</code>. Here you need to convert <code>nhd</code> into a tibble and put that in as your data. Look at the example above and keep in mind that, in this case, the first NULL could be replaced with the data in <code>nhd</code>.
</p>
</div>
</div>
<p><span style="font-size: 22px; font-weight: bold; color: var(--pink);">Group Discussion Point</span></p>
<ul>
<li>Looking at the histogram, visually locate where your original value would sit on this distribution. Would it be extreme, in the tail, or does it look rather common, in the middle? <select class='solveme' data-answer='["is in the tail so looks extreme"]'> <option></option> <option>is in the middle so looks common</option> <option>is in the tail so looks extreme</option></select></li>
</ul>
<p>Before moving on stop to think about what this means - that the difference between the two original groups is rather uncommon in this permuted distribution, i.e. is in the tails! Again, if unsure, go back to the principles of NHST or discuss it with your tutor!</p>
</div>
<div id="Ch5InClassQueT5" class="section level3">
<h3><span class="header-section-number">5.3.6</span> Step 5: Compare the Observed Mean Difference to the NHD</h3>
<p>If the null hypothesis is false, and there is a real difference between the groups, then the difference in means we observed for the original data (<code>d_orig</code>) should be somewhere in either tail of the null-hypothesis distribution we just estimated; it should be an “extreme” value. How can we test this beyond a visual inspection?</p>
<p>First, we have to decide on a false positive (Type I error) rate which is the rate at which we will falsely reject <span class="math inline">\(H_0\)</span> when it is true. This rate is referred to by the Greek letter <span class="math inline">\(\alpha\)</span> (“alpha”). Let’s just use the conventional level used in Psychology: <span class="math inline">\(\alpha = .05\)</span>.</p>
<p>So the question we must ask is, if the null hypothesis was true, what would be the probability of getting a difference in means as extreme as the one we observed in the original data? We will label this probability <code>p</code>.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--pink);">Group Discussion Point</span></p>
<p>Take a few moments as a group to see if you can figure out how you might compute <code>p</code> from the data before we show you how. We will then show you the process in the next few, final, steps.</p>
<p>5.1. Replace the NULLS in the code below to create a logical vector which states TRUE for all values of <code>nhd</code> greater than or equal to <code>d_orig</code> regardless of sign. <strong>Note:</strong> A logical vector is one that returns TRUE when the expression is true and FALSE when the expression is false.</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb227-1" data-line-number="1">lvec &lt;-<span class="st"> </span><span class="kw">abs</span>(<span class="ot">NULL</span>) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">abs</span>(<span class="ot">NULL</span>)</a></code></pre></div>
<div class="solution">
<button>
Portfolio Point - abs and the case of one or two tails
</button>
<div class="info">
<p>
In the code above, the function <code>abs()</code> says to ignore the sign and use the absolute value. For instance, if <code>d_orig = -7</code>, then <code>abs(d_orig) = 7</code>. Why do we do this here? Can you think why you want to know how extreme your value is in this distribution regardless of whether the value is positive or negative?
</p>
<p>
The answer relates to whether you are testing in one or two tails of your distribution; the positive side, the negative side, or both. You will have heard in your lectures of one or two-tailed tests. Most people would say to run two-tailed tests. This means looking at the negative and positive tails of the distribution to see if our original value is extreme, and the simplest way to do this is to ignore the sign of the values and treat both sides equally. If you wanted to only test one-tail, say that your value is extreme to the negative side of the tail, then you would not use the <code>abs()</code> and set the expression to make sure you only find values less than your original value. To test only on the positive side of the distribution, make sure you only get values higher than the original. But for now we will mostly look at two-tailed tests.
</p>
</div>
</div>
<p>5.2. Replace the NULL in the code below to <code>sum()</code> the <code>lvec</code> vector to get the total number of values equal to or greater than our original difference, <code>d_orig</code>. Fortunately, R is fine with summing TRUEs and FALSEs so you do not have to convert the data at all.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" data-line-number="1">n_exceeding_orig &lt;-<span class="st"> </span><span class="ot">NULL</span></a></code></pre></div>
<p>5.3. Replace the NULL in the code below to calculate the probability of finding a value of <code>d_orig</code> in our <code>nhd</code> distribution by dividing <code>n_exceeding_orig</code>, the number of values greater than or equal to your original value, by the <code>length()</code> of your whole distribution <code>nhd</code>. <strong>Note: the length of <code>nhd</code> is the same as the number of replications we ran. Using code reduces the chance of human error.</strong></p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb229-1" data-line-number="1">p &lt;-<span class="st"> </span><span class="ot">NULL</span></a></code></pre></div>
<p>5.4. Finally, complete the sentence below determining if the original value was extreme or not in regards to the distribution. Use inline coding, shown in Lab 1, to replace the <code>XXX</code>s. For example, when formatted without the space before the first r, <code>r length(nhd)</code> would present as 1000.</p>
<p><strong>&quot; The difference between Group A and Group B (M = <code>XXX</code>) was found to be have a probability of p = <code>XXX</code>. This means that the original mean difference was …… and the null hypothesis is …..&quot; </strong></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span></p>
<p>Well done in completing this lab. Let’s recap before finishing. We had two groups, A and B, that we had tested in an experiment. We calculated the mean difference between A and B and wanted to know if this was a significant difference. To test this, we created a distribution of possible differences between A and B using the premise of permutation tests and then found the probability of our original value in that permuted distribution. The more extreme the value in a distribution, the more likely that the difference is significant. And that is exactly what we found; an <span class="math inline">\(\alpha &lt; .05\)</span>. Next time we will look at using functions and inferential tests to perform this analysis but by understanding the above you now know how probability is determined.</p>
<p>You should now be ready to complete the Homework Assignment for this lab. <strong>The assignment for this Lab is summative and should be submitted through the Moodle Level 2 Assignment Submission Page no later than 1 minute before your next lab.</strong> If you have any questions, please post them on the slack forum under the channel #level2_2018. Finally, don’t forget to add any useful information to your Portfolio before you leave it too long and forget.</p>

</div>
</div>
<div id="assignment-4" class="section level2">
<h2><span class="header-section-number">5.4</span> Assignment</h2>
<p>This is a summative assignment. Instructions on how to access and submit your assignment will be made available during the course.</p>

</div>
<div id="solutions-to-questions-4" class="section level2">
<h2><span class="header-section-number">5.5</span> Solutions to Questions</h2>
<p>Below you will find the solutions to the questions for the Activities for this chapter. Only look at them after giving the questions a good try and speaking to the tutor about any issues.</p>
<div id="inclass-activities-3" class="section level3">
<h3><span class="header-section-number">5.5.1</span> InClass Activities</h3>
<div id="step-1" class="section level4">
<h4><span class="header-section-number">5.5.1.1</span> Step 1</h4>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</a>
<a class="sourceLine" id="cb230-2" data-line-number="2"></a>
<a class="sourceLine" id="cb230-3" data-line-number="3"><span class="co">## Note: </span></a>
<a class="sourceLine" id="cb230-4" data-line-number="4"><span class="co">## Here&#39;s how we created the data for today&#39;s task:</span></a>
<a class="sourceLine" id="cb230-5" data-line-number="5"><span class="co">## dat &lt;- tibble(group = rep(c(&quot;A&quot;, &quot;B&quot;), each = 50),</span></a>
<a class="sourceLine" id="cb230-6" data-line-number="6"><span class="co">##               Y = c(rnorm(50, 100, 15),</span></a>
<a class="sourceLine" id="cb230-7" data-line-number="7"><span class="co">##                     rnorm(50, 110, 15)))</span></a>
<a class="sourceLine" id="cb230-8" data-line-number="8"><span class="co">##</span></a>
<a class="sourceLine" id="cb230-9" data-line-number="9"><span class="co">## write_csv(dat, &quot;perm_data.csv&quot;)</span></a>
<a class="sourceLine" id="cb230-10" data-line-number="10"><span class="co">## You could create a new dataset yourself and try it again.</span></a>
<a class="sourceLine" id="cb230-11" data-line-number="11"></a>
<a class="sourceLine" id="cb230-12" data-line-number="12">dat &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;perm_data.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb230-13" data-line-number="13"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">subj_id =</span> <span class="kw">row_number</span>())</a></code></pre></div>
<p><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT1">Return to Task</a></p>
</div>
<div id="step-2" class="section level4">
<h4><span class="header-section-number">5.5.1.2</span> Step 2</h4>
<p><strong>Step 2.1.1 - the basic dat pipeline</strong></p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb231-1" data-line-number="1">dat <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb231-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb231-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   group     m
##   &lt;chr&gt; &lt;dbl&gt;
## 1 A      101.
## 2 B      109.</code></pre>
<p><strong>Step 2.1.2 - using <code>spread()</code> to separate the groups</strong></p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" data-line-number="1">dat <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb233-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb233-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb233-4" data-line-number="4"><span class="st">  </span><span class="kw">spread</span>(group, m)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##       A     B
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  101.  109.</code></pre>
<p><strong>Step 2.1.3 - <code>mutate()</code> the column of mean differences</strong></p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb235-1" data-line-number="1">dat <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb235-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb235-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb235-4" data-line-number="4"><span class="st">  </span><span class="kw">spread</span>(group, m) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb235-5" data-line-number="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> A <span class="op">-</span><span class="st"> </span>B)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##       A     B  diff
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  101.  109. -7.39</code></pre>
<p><strong>Step 2.1.4 - <code>pull()</code> out the difference</strong></p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb237-1" data-line-number="1">dat <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb237-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb237-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb237-4" data-line-number="4"><span class="st">  </span><span class="kw">spread</span>(group, m) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb237-5" data-line-number="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> A <span class="op">-</span><span class="st"> </span>B) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb237-6" data-line-number="6"><span class="st">  </span><span class="kw">pull</span>(diff)</a></code></pre></div>
<pre><code>## [1] -7.388401</code></pre>
<p><strong>Step 2.2 - setting up the <code>calc_diff()</code> function</strong></p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb239-1" data-line-number="1">calc_diff &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb239-2" data-line-number="2">  x <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb239-3" data-line-number="3"><span class="st">    </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb239-4" data-line-number="4"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb239-5" data-line-number="5"><span class="st">    </span><span class="kw">spread</span>(group, m) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb239-6" data-line-number="6"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">diff =</span> A <span class="op">-</span><span class="st"> </span>B) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb239-7" data-line-number="7"><span class="st">    </span><span class="kw">pull</span>(diff)</a>
<a class="sourceLine" id="cb239-8" data-line-number="8">}</a></code></pre></div>
<p><strong>Step 2.3 - Calculating d_orig using calc_diff()</strong></p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1">d_orig &lt;-<span class="st"> </span><span class="kw">calc_diff</span>(dat)</a>
<a class="sourceLine" id="cb240-2" data-line-number="2"><span class="kw">is_tibble</span>(d_orig)</a>
<a class="sourceLine" id="cb240-3" data-line-number="3"><span class="kw">is_numeric</span>(d_orig)</a></code></pre></div>
<pre><code>## Warning: Deprecated</code></pre>
<pre><code>## [1] FALSE
## [1] TRUE</code></pre>
<p><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT2">Return to Task</a></p>
</div>
<div id="step-3" class="section level4">
<h4><span class="header-section-number">5.5.1.3</span> Step 3</h4>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb243-1" data-line-number="1">permute &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb243-2" data-line-number="2">  x <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb243-3" data-line-number="3"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">group =</span> <span class="kw">sample</span>(group))</a>
<a class="sourceLine" id="cb243-4" data-line-number="4">}</a>
<a class="sourceLine" id="cb243-5" data-line-number="5"></a>
<a class="sourceLine" id="cb243-6" data-line-number="6"><span class="kw">permute</span>(dat)</a></code></pre></div>
<pre><code>## # A tibble: 100 x 3
##    group     Y subj_id
##    &lt;chr&gt; &lt;dbl&gt;   &lt;int&gt;
##  1 B     113.        1
##  2 A      91.0       2
##  3 A      89.2       3
##  4 B     110.        4
##  5 A     118.        5
##  6 B     104.        6
##  7 B     100.        7
##  8 A      94.1       8
##  9 B      94.8       9
## 10 B      92.5      10
## # ... with 90 more rows</code></pre>
<p><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT3">Return to Task</a></p>
</div>
<div id="step-4" class="section level4">
<h4><span class="header-section-number">5.5.1.4</span> Step 4</h4>
<p><strong>Step 4.1 - the pipeline</strong></p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb245-1" data-line-number="1">dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">permute</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">calc_diff</span>()</a></code></pre></div>
<pre><code>## [1] -1.53662</code></pre>
<p><strong>Step 4.2 - creating nhd</strong></p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb247-1" data-line-number="1">nhd &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">permute</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">calc_diff</span>())</a></code></pre></div>
<p><strong>Step 4.3 - plotting nhd</strong></p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="kw">tibble</span>(<span class="dt">x =</span> nhd), <span class="kw">aes</span>(x)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:histogram"></span>
<img src="05-s01-lab05e_files/figure-html/histogram-1.png" alt="**CAPTION THIS FIGURE!!**" width="100%" />
<p class="caption">
Figure 5.1: <strong>CAPTION THIS FIGURE!!</strong>
</p>
</div>
<p><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT4">Return to Task</a></p>
</div>
<div id="step-5" class="section level4">
<h4><span class="header-section-number">5.5.1.5</span> Step 5</h4>
<p><strong>Step 5.1 - The logical vector</strong></p>
<ul>
<li>This code establishes all the values in nhd that are equal to or greater than the value in d_orig</li>
<li>It returns all these values as TRUE and all other values as FALSE</li>
<li><code>abs()</code> tells the code to ignore the sign of the value (i.e. assumes everything is positive)</li>
</ul>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb249-1" data-line-number="1">lvec =<span class="st"> </span><span class="kw">abs</span>(nhd) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">abs</span>(d_orig)</a></code></pre></div>
<p><strong>Step 5.2 - Sum up all the TRUE values</strong></p>
<ul>
<li>This gives the total number of values greater or equal to d_orig</li>
</ul>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" data-line-number="1">n_exceeding_orig &lt;-<span class="st"> </span><span class="kw">sum</span>(lvec)</a></code></pre></div>
<p><strong>Step 5.3 - Calculate the probability</strong></p>
<ul>
<li>The probability of obtaining d_orig or greater is calculated by the number of values equal to or greater than d_orig, divided by the full size of nhd (or in other words, its length)</li>
</ul>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb251-1" data-line-number="1">p &lt;-<span class="st"> </span>n_exceeding_orig <span class="op">/</span><span class="st"> </span><span class="kw">length</span>(nhd)</a></code></pre></div>
<p><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT5">Return to Task</a></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--purple);">Chapter Complete!</span></p>

</div>
</div>
</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="revisiting-probability-distributions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="nhst-and-one-sample-t-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
