<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lab 14 Regression | Level 2 Research Methods and Statistics Practical Skills</title>
  <meta name="description" content="ug2-practical-materials" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Lab 14 Regression | Level 2 Research Methods and Statistics Practical Skills" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="ug2-practical-materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lab 14 Regression | Level 2 Research Methods and Statistics Practical Skills" />
  
  <meta name="twitter:description" content="ug2-practical-materials" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="continuing-the-glm-two-factor-designs.html"/>
<link rel="next" href="combining-anova-and-regression-e-g-ancovas.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include\psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Level 2 Practical</a></li>
<li><a href="https://zenodo.org/badge/latestdoi/166541567"><img src="https://zenodo.org/badge/166541567.svg" alt="DOI"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html"><i class="fa fa-check"></i><b>1</b> Starting with R Markdown</a><ul>
<li class="chapter" data-level="1.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#overview-1"><i class="fa fa-check"></i><b>1.1</b> Overview</a><ul>
<li class="chapter" data-level="1.1.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#what-is-r-markdown"><i class="fa fa-check"></i><b>1.1.1</b> What is R Markdown?</a></li>
<li class="chapter" data-level="1.1.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#advantages-of-using-r-markdown"><i class="fa fa-check"></i><b>1.1.2</b> Advantages of using R Markdown</a></li>
<li class="chapter" data-level="1.1.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#creating-an-r-markdown-.rmd-file"><i class="fa fa-check"></i><b>1.1.3</b> Creating an R Markdown (.Rmd) File</a></li>
<li class="chapter" data-level="1.1.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#one-last-thing-before-beginning"><i class="fa fa-check"></i><b>1.1.4</b> One last thing before beginning!</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#preclass-activiy"><i class="fa fa-check"></i><b>1.2</b> PreClass Activiy</a><ul>
<li class="chapter" data-level="1.2.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#lets-begin"><i class="fa fa-check"></i><b>1.2.1</b> Let’s Begin</a></li>
<li class="chapter" data-level="1.2.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#code-chunks"><i class="fa fa-check"></i><b>1.2.2</b> Code Chunks</a></li>
<li class="chapter" data-level="1.2.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#knitting-code"><i class="fa fa-check"></i><b>1.2.3</b> Knitting Code</a></li>
<li class="chapter" data-level="1.2.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#adding-code-chunk-rules-and-options"><i class="fa fa-check"></i><b>1.2.4</b> Adding Code Chunk Rules and Options</a></li>
<li class="chapter" data-level="1.2.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#adding-inline-code"><i class="fa fa-check"></i><b>1.2.5</b> Adding Inline Code</a></li>
<li class="chapter" data-level="1.2.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#formatting-the-r-markdown-file"><i class="fa fa-check"></i><b>1.2.6</b> Formatting the R Markdown File</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-activiy"><i class="fa fa-check"></i><b>1.3</b> InClass Activiy</a><ul>
<li class="chapter" data-level="1.3.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#r-markdown-and-the-experimental-design-portfolio"><i class="fa fa-check"></i><b>1.3.1</b> R Markdown and The Experimental Design Portfolio</a></li>
<li class="chapter" data-level="1.3.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#the-ponzo-illusion-and-age"><i class="fa fa-check"></i><b>1.3.2</b> The Ponzo Illusion and Age</a></li>
<li class="chapter" data-level="1.3.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT1"><i class="fa fa-check"></i><b>1.3.3</b> Task 1: Setting up Your R Markdown Portfolio</a></li>
<li class="chapter" data-level="1.3.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT2"><i class="fa fa-check"></i><b>1.3.4</b> Task 2: Give your Report a Heading</a></li>
<li class="chapter" data-level="1.3.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT3"><i class="fa fa-check"></i><b>1.3.5</b> Task 3: Creating a Code Chunk</a></li>
<li class="chapter" data-level="1.3.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT4"><i class="fa fa-check"></i><b>1.3.6</b> Task 4: Writing your Report</a></li>
<li class="chapter" data-level="1.3.7" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT5"><i class="fa fa-check"></i><b>1.3.7</b> Task 5: Making Text Bold or Italicized</a></li>
<li class="chapter" data-level="1.3.8" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT6"><i class="fa fa-check"></i><b>1.3.8</b> Task 6: Adding Links to the Data in your Methods</a></li>
<li class="chapter" data-level="1.3.9" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT7"><i class="fa fa-check"></i><b>1.3.9</b> Task 7: Adding an Image to your Methods</a></li>
<li class="chapter" data-level="1.3.10" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT8"><i class="fa fa-check"></i><b>1.3.10</b> Task 8: Adding a Table to your Results</a></li>
<li class="chapter" data-level="1.3.11" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT9"><i class="fa fa-check"></i><b>1.3.11</b> Task 9: Adding a Figure to your Results</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#assignment"><i class="fa fa-check"></i><b>1.4</b> Assignment</a></li>
<li class="chapter" data-level="1.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#solutions-to-questions"><i class="fa fa-check"></i><b>1.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="1.5.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-activities"><i class="fa fa-check"></i><b>1.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-comparison"><i class="fa fa-check"></i><b>1.6</b> InClass Comparison</a><ul>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#lab-1---the-magnitude-of-the-ponzo-illusion-varies-as-a-function-of-age"><i class="fa fa-check"></i>Lab 1 - The Magnitude of the Ponzo Illusion varies as a function of Age</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#methods"><i class="fa fa-check"></i>Methods</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#results"><i class="fa fa-check"></i>Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html"><i class="fa fa-check"></i><b>2</b> Data-Wrangling: A Key Skill</a><ul>
<li class="chapter" data-level="2.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#overview-2"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#preclass-activity"><i class="fa fa-check"></i><b>2.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#revisiting-the-wickham-six"><i class="fa fa-check"></i><b>2.2.1</b> Revisiting the Wickham Six</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#learning-to-wrangle-is-there-a-chastity-belt-on-perception"><i class="fa fa-check"></i><b>2.2.2</b> Learning to Wrangle: Is there a Chastity Belt on Perception</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT1"><i class="fa fa-check"></i><b>2.2.3</b> The <strong><code>select()</code></strong> Function - to keep only specific columns</a></li>
<li class="chapter" data-level="2.2.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT2"><i class="fa fa-check"></i><b>2.2.4</b> The <strong><code>arrange()</code></strong> Function - to sort and arrange columns</a></li>
<li class="chapter" data-level="2.2.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT3"><i class="fa fa-check"></i><b>2.2.5</b> The <strong><code>filter()</code></strong> Function - to keep only parts of the data</a></li>
<li class="chapter" data-level="2.2.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT4"><i class="fa fa-check"></i><b>2.2.6</b> The <strong><code>mutate()</code></strong> Function - for adding new columns</a></li>
<li class="chapter" data-level="2.2.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT5"><i class="fa fa-check"></i><b>2.2.7</b> The <strong><code>group_by()</code></strong> Function - to group parts of data altogether</a></li>
<li class="chapter" data-level="2.2.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT6"><i class="fa fa-check"></i><b>2.2.8</b> The <strong><code>summarise()</code></strong> Function - to do some calculations on the data</a></li>
<li class="chapter" data-level="2.2.9" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#two-other-useful-functions"><i class="fa fa-check"></i><b>2.2.9</b> Two Other Useful Functions</a></li>
<li class="chapter" data-level="2.2.10" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#last-but-not-least---pipes-to-make-your-code-efficient"><i class="fa fa-check"></i><b>2.2.10</b> Last but not least - Pipes (<strong><code>%&gt;%</code></strong>) to make your code efficient</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#inclass-activity"><i class="fa fa-check"></i><b>2.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#task-1-open-a-script"><i class="fa fa-check"></i><b>2.3.1</b> Task 1: Open a Script</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT2"><i class="fa fa-check"></i><b>2.3.2</b> Task 2: Bring in Your Library</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT3"><i class="fa fa-check"></i><b>2.3.3</b> Task 3: Load in the Data</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT4"><i class="fa fa-check"></i><b>2.3.4</b> Task 4: Review Your Data.</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT5"><i class="fa fa-check"></i><b>2.3.5</b> Task 5: Gathering Data with pivot_longer().</a></li>
<li class="chapter" data-level="2.3.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT6"><i class="fa fa-check"></i><b>2.3.6</b> Task 6: Combining Data.</a></li>
<li class="chapter" data-level="2.3.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT7"><i class="fa fa-check"></i><b>2.3.7</b> Task 7: Calculating the AQ Scores.</a></li>
<li class="chapter" data-level="2.3.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT8"><i class="fa fa-check"></i><b>2.3.8</b> Task 8: One Last Thing on Pipes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#assignment-1"><i class="fa fa-check"></i><b>2.4</b> Assignment</a><ul>
<li class="chapter" data-level="2.4.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#todays-topic---the-ageing-brain"><i class="fa fa-check"></i><b>2.4.1</b> Today’s Topic - The Ageing Brain</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#load-in-the-data"><i class="fa fa-check"></i><b>2.4.2</b> Load in the data</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT1"><i class="fa fa-check"></i><b>2.4.3</b> Task 1 - Oldest Participant</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT2"><i class="fa fa-check"></i><b>2.4.4</b> Task 2 - Arranging D-SPAN</a></li>
<li class="chapter" data-level="2.4.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT3"><i class="fa fa-check"></i><b>2.4.5</b> Task 3 - Foreign Language Speakers</a></li>
<li class="chapter" data-level="2.4.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT4"><i class="fa fa-check"></i><b>2.4.6</b> Task 4 - Creating Percentage MOCA scores</a></li>
<li class="chapter" data-level="2.4.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT5"><i class="fa fa-check"></i><b>2.4.7</b> Task 5 - Remove the MOCA column</a></li>
<li class="chapter" data-level="2.4.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT6"><i class="fa fa-check"></i><b>2.4.8</b> Task 6 - Gather the Responses together</a></li>
<li class="chapter" data-level="2.4.9" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT7"><i class="fa fa-check"></i><b>2.4.9</b> Task 7 - Joining the data</a></li>
<li class="chapter" data-level="2.4.10" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT8"><i class="fa fa-check"></i><b>2.4.10</b> Task 8 - Working the Pipes</a></li>
<li class="chapter" data-level="2.4.11" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT9"><i class="fa fa-check"></i><b>2.4.11</b> Task 9 - Difference in Musical Means</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#solutions-to-questions-1"><i class="fa fa-check"></i><b>2.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="2.5.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#preclass-activities"><i class="fa fa-check"></i><b>2.5.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="2.5.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#inclass-actitivies"><i class="fa fa-check"></i><b>2.5.2</b> InClass Actitivies</a></li>
<li class="chapter" data-level="2.5.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#assignment-solution"><i class="fa fa-check"></i><b>2.5.3</b> Assignment Solution</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#additional-material"><i class="fa fa-check"></i><b>2.6</b> Additional Material</a><ul>
<li class="chapter" data-level="" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#more-on-read_csv"><i class="fa fa-check"></i>More on read_csv()</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#more-on-code-layout"><i class="fa fa-check"></i>More on Code Layout</a></li>
<li><a href="data-wrangling-a-key-skill.html#more-on-gathering-data---pivot_longer-and-gather">More on gathering data - <code>pivot_longer()</code> and <code>gather()</code></a></li>
<li class="chapter" data-level="" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#more-on-binding-and-joining"><i class="fa fa-check"></i>More on binding and joining</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html"><i class="fa fa-check"></i><b>3</b> Visualisation Through <strong><code>ggplot2</code></strong></a><ul>
<li class="chapter" data-level="3.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#overview-3"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#preclass-activity-1"><i class="fa fa-check"></i><b>3.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="3.2.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#scatterplots---geom_point"><i class="fa fa-check"></i><b>3.2.1</b> Scatterplots - <code>geom_point()</code></a></li>
<li class="chapter" data-level="3.2.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#histograms---geom_histogram"><i class="fa fa-check"></i><b>3.2.2</b> Histograms - geom_histogram()</a></li>
<li class="chapter" data-level="3.2.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#boxplots---geom_boxplot"><i class="fa fa-check"></i><b>3.2.3</b> Boxplots - geom_boxplot()</a></li>
<li class="chapter" data-level="3.2.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#barplots---geom_bar-or-geom_col"><i class="fa fa-check"></i><b>3.2.4</b> Barplots - geom_bar() or geom_col()</a></li>
<li class="chapter" data-level="3.2.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#themes-labels-guides-and-facet_wraps"><i class="fa fa-check"></i><b>3.2.5</b> Themes, Labels, Guides, and <strong><code>facet_wraps()</code></strong></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#inclass-activity-1"><i class="fa fa-check"></i><b>3.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="3.3.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#mental-rotation-angle-and-reaction-time"><i class="fa fa-check"></i><b>3.3.1</b> Mental Rotation: Angle and Reaction Time</a></li>
<li class="chapter" data-level="3.3.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT1"><i class="fa fa-check"></i><b>3.3.2</b> Task 1: Loading and Viewing the Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT2"><i class="fa fa-check"></i><b>3.3.3</b> Task 2: Recreating the Figure</a></li>
<li class="chapter" data-level="3.3.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT3"><i class="fa fa-check"></i><b>3.3.4</b> Task 3: Examining Additional Variable Effects</a></li>
<li class="chapter" data-level="3.3.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT4"><i class="fa fa-check"></i><b>3.3.5</b> Task 4: Grouping the Figure Data</a></li>
<li class="chapter" data-level="3.3.6" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT5"><i class="fa fa-check"></i><b>3.3.6</b> Task 5: Identifying Groups Using <strong><code>aes()</code></strong></a></li>
<li class="chapter" data-level="3.3.7" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT6"><i class="fa fa-check"></i><b>3.3.7</b> Task 6: Changing the Shape and Size of Data Points</a></li>
<li class="chapter" data-level="3.3.8" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT7"><i class="fa fa-check"></i><b>3.3.8</b> Task 7: Adding Labels and Changing the Background</a></li>
<li class="chapter" data-level="3.3.9" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT8"><i class="fa fa-check"></i><b>3.3.9</b> Task 8: Separating a Variable and Removing Legends</a></li>
<li class="chapter" data-level="3.3.10" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#additional-considerations-briefly"><i class="fa fa-check"></i><b>3.3.10</b> Additional Considerations (briefly!)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#assignment-2"><i class="fa fa-check"></i><b>3.4</b> Assignment</a></li>
<li class="chapter" data-level="3.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#solutions-to-questions-2"><i class="fa fa-check"></i><b>3.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="3.5.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#inclass-activities-1"><i class="fa fa-check"></i><b>3.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#additional-material-1"><i class="fa fa-check"></i><b>3.6</b> Additional Material</a><ul>
<li class="chapter" data-level="3.6.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#more-on-aes---when-to-and-when-not-to"><i class="fa fa-check"></i><b>3.6.1</b> More on <code>aes()</code> - when to and when not to!</a></li>
<li class="chapter" data-level="" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#combining-plots-into-one-figure"><i class="fa fa-check"></i>Combining Plots into one Figure</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html"><i class="fa fa-check"></i><b>4</b> Revisiting Probability Distributions</a><ul>
<li class="chapter" data-level="4.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#overview-4"><i class="fa fa-check"></i><b>4.1</b> Overview</a><ul>
<li class="chapter" data-level="4.1.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#discrete-or-continuous-datasets"><i class="fa fa-check"></i><b>4.1.1</b> Discrete or Continuous Datasets</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#preclass-activity-1-1"><i class="fa fa-check"></i><b>4.2</b> PreClass Activity 1</a><ul>
<li class="chapter" data-level="4.2.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#general-probability-calculations"><i class="fa fa-check"></i><b>4.2.1</b> General Probability Calculations</a></li>
<li class="chapter" data-level="4.2.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#creating-a-simple-probability-distribution"><i class="fa fa-check"></i><b>4.2.2</b> Creating a Simple Probability Distribution</a></li>
<li class="chapter" data-level="4.2.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#the-binomial-distribution---creating-a-discrete-distribution"><i class="fa fa-check"></i><b>4.2.3</b> The Binomial Distribution - Creating a Discrete Distribution</a></li>
<li class="chapter" data-level="4.2.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#dbinom---the-density-function"><i class="fa fa-check"></i><b>4.2.4</b> <strong><code>dbinom()</code></strong> - The Density Function</a></li>
<li class="chapter" data-level="4.2.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#pbinom---the-cumulative-probability-function"><i class="fa fa-check"></i><b>4.2.5</b> <strong><code>pbinom()</code></strong> - The Cumulative Probability Function</a></li>
<li class="chapter" data-level="4.2.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#qbinom---the-quantile-function"><i class="fa fa-check"></i><b>4.2.6</b> <strong><code>qbinom()</code></strong> - The Quantile Function</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#preclass-activity-2"><i class="fa fa-check"></i><b>4.3</b> PreClass Activity 2</a><ul>
<li class="chapter" data-level="4.3.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#continuous-data---brief-recap-on-the-normal-distribution"><i class="fa fa-check"></i><b>4.3.1</b> Continuous Data - Brief Recap on The Normal Distribution</a></li>
<li class="chapter" data-level="4.3.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#properties-of-the-normal-distribution"><i class="fa fa-check"></i><b>4.3.2</b> Properties of the Normal distribution:</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-1-1"><i class="fa fa-check"></i><b>4.4</b> InClass Activity 1</a><ul>
<li class="chapter" data-level="4.4.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#continuous-data-and-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Continuous Data and the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#estimating-from-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.2</b> Estimating from the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#dnorm---the-density-function-for-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.3</b> <strong><code>dnorm()</code></strong> - The Density Function for the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#pnorm---the-cumulative-probability-function"><i class="fa fa-check"></i><b>4.4.4</b> <strong><code>pnorm()</code></strong> - The Cumulative Probability function</a></li>
<li class="chapter" data-level="4.4.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#qnorm---the-quantile-function"><i class="fa fa-check"></i><b>4.4.5</b> <strong><code>qnorm()</code></strong> - The Quantile Function</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-2-additional"><i class="fa fa-check"></i><b>4.5</b> InClass Activity 2 (Additional)</a><ul>
<li class="chapter" data-level="4.5.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#return-of-the-binomial-ch4inclassquebinomial"><i class="fa fa-check"></i><b>4.5.1</b> Return of the Binomial {Ch4InClassQueBinomial}</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-3-additional"><i class="fa fa-check"></i><b>4.6</b> InClass Activity 3 (Additional)</a><ul>
<li class="chapter" data-level="4.6.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#back-to-basics"><i class="fa fa-check"></i><b>4.6.1</b> Back to Basics</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#assignment-3"><i class="fa fa-check"></i><b>4.7</b> Assignment</a><ul>
<li class="chapter" data-level="4.7.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#todays-topic---probability"><i class="fa fa-check"></i><b>4.7.1</b> Today’s Topic - Probability</a></li>
<li class="chapter" data-level="4.7.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueLib"><i class="fa fa-check"></i><b>4.7.2</b> Load in the Library</a></li>
<li class="chapter" data-level="4.7.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT1"><i class="fa fa-check"></i><b>4.7.3</b> Assignment Task 1</a></li>
<li class="chapter" data-level="4.7.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT2"><i class="fa fa-check"></i><b>4.7.4</b> Assignment Task 2</a></li>
<li class="chapter" data-level="4.7.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT3"><i class="fa fa-check"></i><b>4.7.5</b> Assignment Task 3</a></li>
<li class="chapter" data-level="4.7.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT4"><i class="fa fa-check"></i><b>4.7.6</b> Assignment Task 4</a></li>
<li class="chapter" data-level="4.7.7" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT5"><i class="fa fa-check"></i><b>4.7.7</b> Assignment Task 5</a></li>
<li class="chapter" data-level="4.7.8" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT6"><i class="fa fa-check"></i><b>4.7.8</b> Assignment Task 6</a></li>
<li class="chapter" data-level="4.7.9" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT7"><i class="fa fa-check"></i><b>4.7.9</b> Assignment Task 7</a></li>
<li class="chapter" data-level="4.7.10" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT8"><i class="fa fa-check"></i><b>4.7.10</b> Assignment Task 8</a></li>
<li class="chapter" data-level="4.7.11" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT9"><i class="fa fa-check"></i><b>4.7.11</b> Assignment Task 9</a></li>
<li class="chapter" data-level="4.7.12" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT10"><i class="fa fa-check"></i><b>4.7.12</b> Assignment Task 10</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#solutions-to-questions-3"><i class="fa fa-check"></i><b>4.8</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="4.8.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activities-2"><i class="fa fa-check"></i><b>4.8.1</b> InClass Activities</a></li>
<li class="chapter" data-level="4.8.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#return-of-the-binomial"><i class="fa fa-check"></i><b>4.8.2</b> Return of the Binomial</a></li>
<li class="chapter" data-level="4.8.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#assignment-solution-1"><i class="fa fa-check"></i><b>4.8.3</b> Assignment Solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html"><i class="fa fa-check"></i><b>5</b> Permutation Tests - A Skill Set</a><ul>
<li class="chapter" data-level="5.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#overview-5"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#preclass-activity-3"><i class="fa fa-check"></i><b>5.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="5.2.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-1-generating-random-numbers"><i class="fa fa-check"></i><b>5.2.1</b> Skill 1: Generating Random Numbers</a></li>
<li class="chapter" data-level="5.2.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-2-permuting-values"><i class="fa fa-check"></i><b>5.2.2</b> Skill 2: Permuting Values</a></li>
<li class="chapter" data-level="5.2.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-3-creating-tibbles"><i class="fa fa-check"></i><b>5.2.3</b> Skill 3: Creating Tibbles</a></li>
<li class="chapter" data-level="5.2.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-4-computing-differences-in-group-means"><i class="fa fa-check"></i><b>5.2.4</b> Skill 4: Computing Differences in Group Means</a></li>
<li class="chapter" data-level="5.2.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-5-creating-your-own-functions"><i class="fa fa-check"></i><b>5.2.5</b> Skill 5: Creating Your Own Functions</a></li>
<li class="chapter" data-level="5.2.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-6-replicating-operations"><i class="fa fa-check"></i><b>5.2.6</b> Skill 6: Replicating Operations</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#inclass-activity-2"><i class="fa fa-check"></i><b>5.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="5.3.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#permutation-tests-of-hypotheses"><i class="fa fa-check"></i><b>5.3.1</b> Permutation Tests of Hypotheses</a></li>
<li class="chapter" data-level="5.3.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT1"><i class="fa fa-check"></i><b>5.3.2</b> Step 1: Load in Add-on Packages and Data</a></li>
<li class="chapter" data-level="5.3.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT2"><i class="fa fa-check"></i><b>5.3.3</b> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></a></li>
<li class="chapter" data-level="5.3.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT3"><i class="fa fa-check"></i><b>5.3.4</b> Step 3: Permute the Group Labels</a></li>
<li class="chapter" data-level="5.3.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT4"><i class="fa fa-check"></i><b>5.3.5</b> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</a></li>
<li class="chapter" data-level="5.3.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT5"><i class="fa fa-check"></i><b>5.3.6</b> Step 5: Compare the Observed Mean Difference to the NHD</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#assignment-4"><i class="fa fa-check"></i><b>5.4</b> Assignment</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#solutions-to-questions-4"><i class="fa fa-check"></i><b>5.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="5.5.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#inclass-activities-3"><i class="fa fa-check"></i><b>5.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#additional-material-2"><i class="fa fa-check"></i><b>5.6</b> Additional Material</a><ul>
<li class="chapter" data-level="5.6.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#more-on-pivot_wider"><i class="fa fa-check"></i><b>5.6.1</b> More on <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="5.6.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#more-on-simulating-your-own-data"><i class="fa fa-check"></i><b>5.6.2</b> More on Simulating your own data</a></li>
<li class="chapter" data-level="5.6.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#more-on-permutations"><i class="fa fa-check"></i><b>5.6.3</b> More on Permutations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html"><i class="fa fa-check"></i><b>6</b> NHST and One-Sample t-tests</a><ul>
<li class="chapter" data-level="6.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#overview-6"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activity-1-2"><i class="fa fa-check"></i><b>6.2</b> PreClass Activity 1</a><ul>
<li class="chapter" data-level="6.2.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#the-binomial-test"><i class="fa fa-check"></i><b>6.2.1</b> The Binomial Test</a></li>
<li class="chapter" data-level="6.2.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT1"><i class="fa fa-check"></i><b>6.2.2</b> Task 1: Creating a Dataframe</a></li>
<li class="chapter" data-level="6.2.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT2"><i class="fa fa-check"></i><b>6.2.3</b> Task 2: Comparing Original and New Sample Reaction Times</a></li>
<li class="chapter" data-level="6.2.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT3"><i class="fa fa-check"></i><b>6.2.4</b> Task 3: Calculating Probability</a></li>
<li class="chapter" data-level="6.2.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#the-one-sample-t-test"><i class="fa fa-check"></i><b>6.2.5</b> The One-Sample t-test</a></li>
<li class="chapter" data-level="6.2.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT4"><i class="fa fa-check"></i><b>6.2.6</b> Task 4: Calculating the Mean and Standard Deviation</a></li>
<li class="chapter" data-level="6.2.7" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT5"><i class="fa fa-check"></i><b>6.2.7</b> Task 5: Calculating the Observed Test Statistic</a></li>
<li class="chapter" data-level="6.2.8" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT6"><i class="fa fa-check"></i><b>6.2.8</b> Task 6: Comparing the Observed Test Statistic to the t-distribution using <strong><code>pt()</code></strong></a></li>
<li class="chapter" data-level="6.2.9" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT7"><i class="fa fa-check"></i><b>6.2.9</b> Task 7: Comparing the Observed Test Statistic to the t-distribution using <strong><code>t.test()</code></strong></a></li>
<li class="chapter" data-level="6.2.10" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT8"><i class="fa fa-check"></i><b>6.2.10</b> Task 8: Drawing Conclusions about the new data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activity-2-additional"><i class="fa fa-check"></i><b>6.3</b> PreClass Activity 2 (Additional)</a><ul>
<li class="chapter" data-level="6.3.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#a-short-blog-on-barplots"><i class="fa fa-check"></i><b>6.3.1</b> A short blog on Barplots</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#inclass-activity-3"><i class="fa fa-check"></i><b>6.4</b> InClass Activity</a><ul>
<li class="chapter" data-level="6.4.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT1"><i class="fa fa-check"></i><b>6.4.1</b> Task 1: Evaluators</a></li>
<li class="chapter" data-level="6.4.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT2"><i class="fa fa-check"></i><b>6.4.2</b> Task 2: Ratings</a></li>
<li class="chapter" data-level="6.4.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT3"><i class="fa fa-check"></i><b>6.4.3</b> Task 3: Creating a Figure</a></li>
<li class="chapter" data-level="6.4.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT4"><i class="fa fa-check"></i><b>6.4.4</b> Task 4: t-tests</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#assignment-5"><i class="fa fa-check"></i><b>6.5</b> Assignment</a><ul>
<li class="chapter" data-level="6.5.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT1A"><i class="fa fa-check"></i><b>6.5.1</b> Task 1A: Libraries</a></li>
<li class="chapter" data-level="6.5.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT1B"><i class="fa fa-check"></i><b>6.5.2</b> Task 1B: Loading in the data</a></li>
<li class="chapter" data-level="6.5.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT2"><i class="fa fa-check"></i><b>6.5.3</b> Task 2: Selecting only relevant columns</a></li>
<li class="chapter" data-level="6.5.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT3"><i class="fa fa-check"></i><b>6.5.4</b> Task 3: Verify the number of subjects in each group</a></li>
<li class="chapter" data-level="6.5.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT4"><i class="fa fa-check"></i><b>6.5.5</b> Task 4: Reproduce Figure 2a</a></li>
<li class="chapter" data-level="6.5.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT5"><i class="fa fa-check"></i><b>6.5.6</b> Task 5: Interpreting your Figure</a></li>
<li class="chapter" data-level="6.5.7" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT6"><i class="fa fa-check"></i><b>6.5.7</b> Task 6: t-test</a></li>
<li class="chapter" data-level="6.5.8" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT7"><i class="fa fa-check"></i><b>6.5.8</b> Task 7: Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#solutions-to-questions-5"><i class="fa fa-check"></i><b>6.6</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="6.6.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activities-1"><i class="fa fa-check"></i><b>6.6.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="6.6.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#inclass-activities-4"><i class="fa fa-check"></i><b>6.6.2</b> InClass Activities</a></li>
<li class="chapter" data-level="6.6.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#homework-activity"><i class="fa fa-check"></i><b>6.6.3</b> Homework Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html"><i class="fa fa-check"></i><b>7</b> Within-Subjects t-test</a><ul>
<li class="chapter" data-level="7.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#overview-7"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#preclass-activity-4"><i class="fa fa-check"></i><b>7.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="7.2.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#reading"><i class="fa fa-check"></i><b>7.2.1</b> Reading</a></li>
<li class="chapter" data-level="7.2.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task"><i class="fa fa-check"></i><b>7.2.2</b> Task</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#inclass-activity-4"><i class="fa fa-check"></i><b>7.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="7.3.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT1"><i class="fa fa-check"></i><b>7.3.1</b> Task 1: Load the Data</a></li>
<li class="chapter" data-level="7.3.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT2"><i class="fa fa-check"></i><b>7.3.2</b> Task 2: Wrangle the Data</a></li>
<li class="chapter" data-level="7.3.3" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT3"><i class="fa fa-check"></i><b>7.3.3</b> Task 3: Look at the Histogram for Normality</a></li>
<li class="chapter" data-level="7.3.4" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT4"><i class="fa fa-check"></i><b>7.3.4</b> Task 4: A Boxplot of Outliers</a></li>
<li class="chapter" data-level="7.3.5" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT5"><i class="fa fa-check"></i><b>7.3.5</b> Task 5: The Violin Plot</a></li>
<li class="chapter" data-level="7.3.6" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT6"><i class="fa fa-check"></i><b>7.3.6</b> Task 6: Calculating Descriptives</a></li>
<li class="chapter" data-level="7.3.7" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT7"><i class="fa fa-check"></i><b>7.3.7</b> Task 7: Visualising Means and Descriptives</a></li>
<li class="chapter" data-level="7.3.8" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT8"><i class="fa fa-check"></i><b>7.3.8</b> Task 8: The t-test</a></li>
<li class="chapter" data-level="7.3.9" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT9"><i class="fa fa-check"></i><b>7.3.9</b> Task 9: The Write-up</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#assignment-6"><i class="fa fa-check"></i><b>7.4</b> Assignment</a></li>
<li class="chapter" data-level="7.5" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#solutions-to-questions-6"><i class="fa fa-check"></i><b>7.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="7.5.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#inclass-activities-5"><i class="fa fa-check"></i><b>7.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html"><i class="fa fa-check"></i><b>8</b> APES - Alpha, Power, Effect Sizes, Sample Size</a><ul>
<li class="chapter" data-level="8.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#overview-8"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#preclass-activity-5"><i class="fa fa-check"></i><b>8.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="8.2.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#reading-1"><i class="fa fa-check"></i><b>8.2.1</b> Reading</a></li>
<li class="chapter" data-level="8.2.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#watch"><i class="fa fa-check"></i><b>8.2.2</b> Watch</a></li>
<li class="chapter" data-level="8.2.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#optional"><i class="fa fa-check"></i><b>8.2.3</b> Optional</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#inclass-activity-5"><i class="fa fa-check"></i><b>8.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="8.3.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT1"><i class="fa fa-check"></i><b>8.3.1</b> Task 1: Effect size from a one-sample t-test</a></li>
<li class="chapter" data-level="8.3.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT2"><i class="fa fa-check"></i><b>8.3.2</b> Task 2: Effect size from between-subjects t-test</a></li>
<li class="chapter" data-level="8.3.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT3"><i class="fa fa-check"></i><b>8.3.3</b> Task 3: Effect Size from matched-pairs t-test</a></li>
<li class="chapter" data-level="8.3.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT4"><i class="fa fa-check"></i><b>8.3.4</b> Task 4: t-value and effect size for a between-subjects Experiment</a></li>
<li class="chapter" data-level="8.3.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT5"><i class="fa fa-check"></i><b>8.3.5</b> Task 5: Sample size for standard power one-sample t-test</a></li>
<li class="chapter" data-level="8.3.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT6"><i class="fa fa-check"></i><b>8.3.6</b> Task 6: Effect size from a high power between-subjects t-test</a></li>
<li class="chapter" data-level="8.3.7" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT7"><i class="fa fa-check"></i><b>8.3.7</b> Task 7: Power of Published Research</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#assignment-7"><i class="fa fa-check"></i><b>8.4</b> Assignment</a><ul>
<li class="chapter" data-level="8.4.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT1"><i class="fa fa-check"></i><b>8.4.1</b> Assignment Task 1</a></li>
<li class="chapter" data-level="8.4.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT2"><i class="fa fa-check"></i><b>8.4.2</b> Assignment Task 2</a></li>
<li class="chapter" data-level="8.4.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT3"><i class="fa fa-check"></i><b>8.4.3</b> Assignment Task 3</a></li>
<li class="chapter" data-level="8.4.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT4"><i class="fa fa-check"></i><b>8.4.4</b> Assignment Task 4</a></li>
<li class="chapter" data-level="8.4.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT5"><i class="fa fa-check"></i><b>8.4.5</b> Assignment Task 5</a></li>
<li class="chapter" data-level="8.4.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT6"><i class="fa fa-check"></i><b>8.4.6</b> Assignment Task 6</a></li>
<li class="chapter" data-level="8.4.7" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT7"><i class="fa fa-check"></i><b>8.4.7</b> Assignment Task 7</a></li>
<li class="chapter" data-level="8.4.8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT8"><i class="fa fa-check"></i><b>8.4.8</b> Assignment Task 8</a></li>
<li class="chapter" data-level="8.4.9" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT9"><i class="fa fa-check"></i><b>8.4.9</b> Assignment Task 9</a></li>
<li class="chapter" data-level="8.4.10" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT10"><i class="fa fa-check"></i><b>8.4.10</b> Assignment Task 10</a></li>
<li class="chapter" data-level="8.4.11" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT11"><i class="fa fa-check"></i><b>8.4.11</b> Assignment Task 11</a></li>
<li class="chapter" data-level="8.4.12" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#the-pwr-package"><i class="fa fa-check"></i><b>8.4.12</b> The <strong><code>pwr</code></strong> package</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#solutions-to-questions-7"><i class="fa fa-check"></i><b>8.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="8.5.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#inclass-activities-6"><i class="fa fa-check"></i><b>8.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="8.5.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#homework-activity-1"><i class="fa fa-check"></i><b>8.5.2</b> Homework Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html"><i class="fa fa-check"></i><b>9</b> Reflection - Semester 1</a><ul>
<li class="chapter" data-level="9.1" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#overview-9"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#preclass-activity-6"><i class="fa fa-check"></i><b>9.2</b> PreClass Activity</a></li>
<li class="chapter" data-level="9.3" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#inclass-activity-6"><i class="fa fa-check"></i><b>9.3</b> InClass Activity</a></li>
<li class="chapter" data-level="9.4" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#assignment-8"><i class="fa fa-check"></i><b>9.4</b> Assignment</a></li>
<li class="chapter" data-level="9.5" data-path="reflection-semester-1.html"><a href="reflection-semester-1.html#solutions-to-questions-8"><i class="fa fa-check"></i><b>9.5</b> Solutions to Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>10</b> Correlations</a><ul>
<li class="chapter" data-level="10.1" data-path="correlations.html"><a href="correlations.html#overview-10"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="correlations.html"><a href="correlations.html#preclass-activity-7"><i class="fa fa-check"></i><b>10.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="10.2.1" data-path="correlations.html"><a href="correlations.html#read"><i class="fa fa-check"></i><b>10.2.1</b> Read</a></li>
<li class="chapter" data-level="10.2.2" data-path="correlations.html"><a href="correlations.html#watch-1"><i class="fa fa-check"></i><b>10.2.2</b> Watch</a></li>
<li class="chapter" data-level="10.2.3" data-path="correlations.html"><a href="correlations.html#play"><i class="fa fa-check"></i><b>10.2.3</b> Play</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="correlations.html"><a href="correlations.html#inclass-activity-7"><i class="fa fa-check"></i><b>10.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="10.3.1" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT1"><i class="fa fa-check"></i><b>10.3.1</b> Task 1 - The Data</a></li>
<li class="chapter" data-level="10.3.2" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT2"><i class="fa fa-check"></i><b>10.3.2</b> Task 2 - Interval or Ordinal</a></li>
<li class="chapter" data-level="10.3.3" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT3"><i class="fa fa-check"></i><b>10.3.3</b> Task 3 - Missing Data</a></li>
<li class="chapter" data-level="10.3.4" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT4"><i class="fa fa-check"></i><b>10.3.4</b> Task 4 - Normality</a></li>
<li class="chapter" data-level="10.3.5" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT5"><i class="fa fa-check"></i><b>10.3.5</b> Task 5 - Descriptives</a></li>
<li class="chapter" data-level="10.3.6" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT6"><i class="fa fa-check"></i><b>10.3.6</b> Task 6 - Pearson or Spearman?</a></li>
<li class="chapter" data-level="10.3.7" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT7"><i class="fa fa-check"></i><b>10.3.7</b> Task 7 - Interpretation</a></li>
<li class="chapter" data-level="10.3.8" data-path="correlations.html"><a href="correlations.html#advanced-1-matrix-of-scatterplots"><i class="fa fa-check"></i><b>10.3.8</b> Advanced 1: Matrix of Scatterplots</a></li>
<li class="chapter" data-level="10.3.9" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT8"><i class="fa fa-check"></i><b>10.3.9</b> Task 8 - The Matrix</a></li>
<li class="chapter" data-level="10.3.10" data-path="correlations.html"><a href="correlations.html#advanced-2-attitudes-towards-vaping"><i class="fa fa-check"></i><b>10.3.10</b> Advanced 2: Attitudes towards Vaping</a></li>
<li class="chapter" data-level="10.3.11" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT9"><i class="fa fa-check"></i><b>10.3.11</b> Task 9 - Attitudes to Vaping</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="correlations.html"><a href="correlations.html#assignment-9"><i class="fa fa-check"></i><b>10.4</b> Assignment</a></li>
<li class="chapter" data-level="10.5" data-path="correlations.html"><a href="correlations.html#solutions-to-questions-9"><i class="fa fa-check"></i><b>10.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="10.5.1" data-path="correlations.html"><a href="correlations.html#inclass-activity-8"><i class="fa fa-check"></i><b>10.5.1</b> InClass Activity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html"><i class="fa fa-check"></i><b>11</b> Introduction to GLM: One-factor ANOVA</a><ul>
<li class="chapter" data-level="11.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#overview-11"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#preclass-activity-8"><i class="fa fa-check"></i><b>11.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="11.2.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#read-1"><i class="fa fa-check"></i><b>11.2.1</b> Read</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#inclass-activity-9"><i class="fa fa-check"></i><b>11.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="11.3.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#recreate-decomposition-matrix-from-the-raw-data"><i class="fa fa-check"></i><b>11.3.1</b> Recreate decomposition matrix from the raw data</a></li>
<li class="chapter" data-level="11.3.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT1"><i class="fa fa-check"></i><b>11.3.2</b> Step 1: Create the basic tibble</a></li>
<li class="chapter" data-level="11.3.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT2"><i class="fa fa-check"></i><b>11.3.3</b> Step 2: Estimate the Grand Mean <span class="math inline">\(\hat{\mu}\)</span></a></li>
<li class="chapter" data-level="11.3.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT3"><i class="fa fa-check"></i><b>11.3.4</b> Step 3: Entering the estimates <span class="math inline">\(\hat{A}_1\)</span>, <span class="math inline">\(\hat{A}_2\)</span>, <span class="math inline">\(\hat{A}_3\)</span></a></li>
<li class="chapter" data-level="11.3.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT4"><i class="fa fa-check"></i><b>11.3.5</b> Step 4: Calculate Residuals <span class="math inline">\(\widehat{S(A)}_{ij}\)</span></a></li>
<li class="chapter" data-level="11.3.6" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT5"><i class="fa fa-check"></i><b>11.3.6</b> Step 5: Sums of squares</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#assignment-10"><i class="fa fa-check"></i><b>11.4</b> Assignment</a><ul>
<li class="chapter" data-level="11.4.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT1"><i class="fa fa-check"></i><b>11.4.1</b> Question 1</a></li>
<li class="chapter" data-level="11.4.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT2"><i class="fa fa-check"></i><b>11.4.2</b> Question 2</a></li>
<li class="chapter" data-level="11.4.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT3"><i class="fa fa-check"></i><b>11.4.3</b> Question 3</a></li>
<li class="chapter" data-level="11.4.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT4"><i class="fa fa-check"></i><b>11.4.4</b> Question 4</a></li>
<li class="chapter" data-level="11.4.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT5"><i class="fa fa-check"></i><b>11.4.5</b> Question 5</a></li>
<li class="chapter" data-level="11.4.6" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT6"><i class="fa fa-check"></i><b>11.4.6</b> Question 6</a></li>
<li class="chapter" data-level="11.4.7" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT7"><i class="fa fa-check"></i><b>11.4.7</b> Question 7</a></li>
<li class="chapter" data-level="11.4.8" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT8"><i class="fa fa-check"></i><b>11.4.8</b> Question 8</a></li>
<li class="chapter" data-level="11.4.9" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT9"><i class="fa fa-check"></i><b>11.4.9</b> Question 9: Create your own decomposition matrix</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#solutions-to-questions-10"><i class="fa fa-check"></i><b>11.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="11.5.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#inclass-activities-7"><i class="fa fa-check"></i><b>11.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="11.5.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#homework-activities"><i class="fa fa-check"></i><b>11.5.2</b> Homework Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html"><i class="fa fa-check"></i><b>12</b> Continuing the GLM: One-factor ANOVA</a><ul>
<li class="chapter" data-level="12.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#overview-12"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#preclass-activity-9"><i class="fa fa-check"></i><b>12.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="12.2.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#read-2"><i class="fa fa-check"></i><b>12.2.1</b> Read</a></li>
<li class="chapter" data-level="12.2.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#try"><i class="fa fa-check"></i><b>12.2.2</b> Try</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#inclass-activity-10"><i class="fa fa-check"></i><b>12.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="12.3.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT1"><i class="fa fa-check"></i><b>12.3.1</b> Task 1 - Quick Checks</a></li>
<li class="chapter" data-level="12.3.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT2"><i class="fa fa-check"></i><b>12.3.2</b> Task 2 - Mean squares and degrees of freedom</a></li>
<li class="chapter" data-level="12.3.3" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT3"><i class="fa fa-check"></i><b>12.3.3</b> Task 3 - F-ratios</a></li>
<li class="chapter" data-level="12.3.4" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT4"><i class="fa fa-check"></i><b>12.3.4</b> Task 4 - Using ez::ezANOVA()</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#assignment-11"><i class="fa fa-check"></i><b>12.4</b> Assignment</a></li>
<li class="chapter" data-level="12.5" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#solutions-to-questions-11"><i class="fa fa-check"></i><b>12.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="12.5.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#inclass-activities-8"><i class="fa fa-check"></i><b>12.5.1</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html"><i class="fa fa-check"></i><b>13</b> Continuing the GLM: Two-factor designs</a><ul>
<li class="chapter" data-level="13.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#overview-13"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#preclass-activity-10"><i class="fa fa-check"></i><b>13.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="13.2.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#read-3"><i class="fa fa-check"></i><b>13.2.1</b> Read</a></li>
<li class="chapter" data-level="13.2.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#try-1"><i class="fa fa-check"></i><b>13.2.2</b> TRY</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#inclass-activity-11"><i class="fa fa-check"></i><b>13.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="13.3.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT1"><i class="fa fa-check"></i><b>13.3.1</b> Estimation equations and decomposition matrix</a></li>
<li class="chapter" data-level="13.3.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT2"><i class="fa fa-check"></i><b>13.3.2</b> Adding the missing columns</a></li>
<li class="chapter" data-level="13.3.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT3"><i class="fa fa-check"></i><b>13.3.3</b> Understanding the two-factor decomposition matrix</a></li>
<li class="chapter" data-level="13.3.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT4"><i class="fa fa-check"></i><b>13.3.4</b> Get your data ready for analysis</a></li>
<li class="chapter" data-level="13.3.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT5"><i class="fa fa-check"></i><b>13.3.5</b> Visualizing 2x2 designs: The interaction plot</a></li>
<li class="chapter" data-level="13.3.6" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT6"><i class="fa fa-check"></i><b>13.3.6</b> Running a 2x2 between-subjects ANOVA with ezANOVA</a></li>
<li class="chapter" data-level="13.3.7" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#app-understanding-main-effects-and-interactions"><i class="fa fa-check"></i><b>13.3.7</b> App: Understanding main effects and interactions</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#assignment-12"><i class="fa fa-check"></i><b>13.4</b> Assignment</a><ul>
<li class="chapter" data-level="13.4.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT1A"><i class="fa fa-check"></i><b>13.4.1</b> Task 1A: Libraries</a></li>
<li class="chapter" data-level="13.4.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT1B"><i class="fa fa-check"></i><b>13.4.2</b> Task 1B: Loading in the data</a></li>
<li class="chapter" data-level="13.4.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT2"><i class="fa fa-check"></i><b>13.4.3</b> Task 2: Calculate cell means</a></li>
<li class="chapter" data-level="13.4.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT3"><i class="fa fa-check"></i><b>13.4.4</b> Task 3: Marginal means for sex</a></li>
<li class="chapter" data-level="13.4.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT4"><i class="fa fa-check"></i><b>13.4.5</b> Task 4: Marginal means for condition</a></li>
<li class="chapter" data-level="13.4.6" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT5"><i class="fa fa-check"></i><b>13.4.6</b> Task 5: Interaction plot</a></li>
<li class="chapter" data-level="13.4.7" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT6"><i class="fa fa-check"></i><b>13.4.7</b> Task 6: Recap Question 1</a></li>
<li class="chapter" data-level="13.4.8" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT7"><i class="fa fa-check"></i><b>13.4.8</b> Task 7: Recap Question 2</a></li>
<li class="chapter" data-level="13.4.9" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT8"><i class="fa fa-check"></i><b>13.4.9</b> Task 8: Recap Question 3</a></li>
<li class="chapter" data-level="13.4.10" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT9"><i class="fa fa-check"></i><b>13.4.10</b> Task 9: Running the factorial ANOVA</a></li>
<li class="chapter" data-level="13.4.11" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT10"><i class="fa fa-check"></i><b>13.4.11</b> Task 10: Interpreting the ANOVA output Question</a></li>
<li class="chapter" data-level="13.4.12" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT11"><i class="fa fa-check"></i><b>13.4.12</b> Task 11: Report your results</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#solutions-to-questions-12"><i class="fa fa-check"></i><b>13.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="13.5.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#inclass-activities-9"><i class="fa fa-check"></i><b>13.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="13.5.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#homework-activities-1"><i class="fa fa-check"></i><b>13.5.2</b> Homework Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>14</b> Regression</a><ul>
<li class="chapter" data-level="14.1" data-path="regression.html"><a href="regression.html#overview-14"><i class="fa fa-check"></i><b>14.1</b> Overview</a></li>
<li class="chapter" data-level="14.2" data-path="regression.html"><a href="regression.html#preclass-activity-11"><i class="fa fa-check"></i><b>14.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="14.2.1" data-path="regression.html"><a href="regression.html#read-4"><i class="fa fa-check"></i><b>14.2.1</b> Read</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="regression.html"><a href="regression.html#inclass-activity-12"><i class="fa fa-check"></i><b>14.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="14.3.1" data-path="regression.html"><a href="regression.html#Ch14InClassQueT1"><i class="fa fa-check"></i><b>14.3.1</b> Task 1: Setup</a></li>
<li class="chapter" data-level="14.3.2" data-path="regression.html"><a href="regression.html#Ch14InClassQueT2"><i class="fa fa-check"></i><b>14.3.2</b> Task 2: Restructuring the ratings</a></li>
<li class="chapter" data-level="14.3.3" data-path="regression.html"><a href="regression.html#Ch14InClassQueT3"><i class="fa fa-check"></i><b>14.3.3</b> Task 3: Calculate mean trustworthiness rating for each voice</a></li>
<li class="chapter" data-level="14.3.4" data-path="regression.html"><a href="regression.html#Ch14InClassQueT4"><i class="fa fa-check"></i><b>14.3.4</b> Task 4: Joining the Data together</a></li>
<li class="chapter" data-level="14.3.5" data-path="regression.html"><a href="regression.html#Ch14InClassQueT5"><i class="fa fa-check"></i><b>14.3.5</b> Task 5: Scatterplot</a></li>
<li class="chapter" data-level="14.3.6" data-path="regression.html"><a href="regression.html#Ch14InClassQueT6"><i class="fa fa-check"></i><b>14.3.6</b> Task 6: Spreading the data</a></li>
<li class="chapter" data-level="14.3.7" data-path="regression.html"><a href="regression.html#Ch14InClassQueT7"><i class="fa fa-check"></i><b>14.3.7</b> Task 7: The Regressions</a></li>
<li class="chapter" data-level="14.3.8" data-path="regression.html"><a href="regression.html#Ch14InClassQueT8"><i class="fa fa-check"></i><b>14.3.8</b> Task 8: Making interpretations</a></li>
<li class="chapter" data-level="14.3.9" data-path="regression.html"><a href="regression.html#Ch14InClassQueT9"><i class="fa fa-check"></i><b>14.3.9</b> Task 9: Making predictions</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="regression.html"><a href="regression.html#assignment-13"><i class="fa fa-check"></i><b>14.4</b> Assignment</a></li>
<li class="chapter" data-level="14.5" data-path="regression.html"><a href="regression.html#solutions-to-questions-13"><i class="fa fa-check"></i><b>14.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="14.5.1" data-path="regression.html"><a href="regression.html#inclass-ativities"><i class="fa fa-check"></i><b>14.5.1</b> InClass Ativities</a></li>
<li class="chapter" data-level="14.5.2" data-path="regression.html"><a href="regression.html#task-3"><i class="fa fa-check"></i><b>14.5.2</b> Task 3</a></li>
<li class="chapter" data-level="14.5.3" data-path="regression.html"><a href="regression.html#task-4"><i class="fa fa-check"></i><b>14.5.3</b> Task 4</a></li>
<li class="chapter" data-level="14.5.4" data-path="regression.html"><a href="regression.html#task-5"><i class="fa fa-check"></i><b>14.5.4</b> Task 5</a></li>
<li class="chapter" data-level="14.5.5" data-path="regression.html"><a href="regression.html#task-6"><i class="fa fa-check"></i><b>14.5.5</b> Task 6</a></li>
<li class="chapter" data-level="14.5.6" data-path="regression.html"><a href="regression.html#task-7"><i class="fa fa-check"></i><b>14.5.6</b> Task 7</a></li>
<li class="chapter" data-level="14.5.7" data-path="regression.html"><a href="regression.html#task-8"><i class="fa fa-check"></i><b>14.5.7</b> Task 8</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html"><i class="fa fa-check"></i><b>15</b> Combining ANOVA and Regression (e.g. ANCOVAs)</a><ul>
<li class="chapter" data-level="15.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#overview-15"><i class="fa fa-check"></i><b>15.1</b> Overview</a></li>
<li class="chapter" data-level="15.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#preclass-activity-12"><i class="fa fa-check"></i><b>15.2</b> PreClass Activity</a><ul>
<li class="chapter" data-level="15.2.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#read-5"><i class="fa fa-check"></i><b>15.2.1</b> Read</a></li>
<li class="chapter" data-level="15.2.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#activity"><i class="fa fa-check"></i><b>15.2.2</b> Activity</a></li>
<li class="chapter" data-level="15.2.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT1"><i class="fa fa-check"></i><b>15.2.3</b> Loading in the data</a></li>
<li class="chapter" data-level="15.2.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT2"><i class="fa fa-check"></i><b>15.2.4</b> Compute the well-being score for each participant</a></li>
<li class="chapter" data-level="15.2.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT3"><i class="fa fa-check"></i><b>15.2.5</b> Visualising Screen time on all technologies</a></li>
<li class="chapter" data-level="15.2.6" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT4"><i class="fa fa-check"></i><b>15.2.6</b> Visualising the Screen time and Well-being relationship</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#inclass-activity-13"><i class="fa fa-check"></i><b>15.3</b> InClass Activity</a><ul>
<li class="chapter" data-level="15.3.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT1"><i class="fa fa-check"></i><b>15.3.1</b> Smartphone and well-being for boys and girls</a></li>
<li class="chapter" data-level="15.3.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT2"><i class="fa fa-check"></i><b>15.3.2</b> Visualising and Interpreting the relationship between smartphone use and wellbeing by sex</a></li>
<li class="chapter" data-level="15.3.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#a-side-point-on-mean-centering-and-deviation-coding"><i class="fa fa-check"></i><b>15.3.3</b> A side point on mean centering and deviation coding</a></li>
<li class="chapter" data-level="15.3.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT3"><i class="fa fa-check"></i><b>15.3.4</b> Estimating model parameters</a></li>
<li class="chapter" data-level="15.3.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT4"><i class="fa fa-check"></i><b>15.3.5</b> Final Interpretations</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#assignment-14"><i class="fa fa-check"></i><b>15.4</b> Assignment</a></li>
<li class="chapter" data-level="15.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#solutions-to-questions-14"><i class="fa fa-check"></i><b>15.5</b> Solutions to Questions</a><ul>
<li class="chapter" data-level="15.5.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#preclass-activities-2"><i class="fa fa-check"></i><b>15.5.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="15.5.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#inclass-activities-10"><i class="fa fa-check"></i><b>15.5.2</b> InClass Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html"><i class="fa fa-check"></i><b>16</b> Reflection - Semester 2</a><ul>
<li class="chapter" data-level="16.1" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#overview-16"><i class="fa fa-check"></i><b>16.1</b> Overview</a></li>
<li class="chapter" data-level="16.2" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#preclass-activity-13"><i class="fa fa-check"></i><b>16.2</b> PreClass Activity</a></li>
<li class="chapter" data-level="16.3" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#inclass-activity-14"><i class="fa fa-check"></i><b>16.3</b> InClass Activity</a></li>
<li class="chapter" data-level="16.4" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#assignment-15"><i class="fa fa-check"></i><b>16.4</b> Assignment</a></li>
<li class="chapter" data-level="16.5" data-path="reflection-semester-2.html"><a href="reflection-semester-2.html#solutions-to-questions-15"><i class="fa fa-check"></i><b>16.5</b> Solutions to Questions</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>A</b> References</a></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Level 2 Research Methods and Statistics Practical Skills</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression" class="section level1">
<h1><span class="header-section-number">Lab 14</span> Regression</h1>
<div id="overview-14" class="section level2">
<h2><span class="header-section-number">14.1</span> Overview</h2>
<p>For the past few weeks we have been looking at designs where you have categorical factors/IVs and where you want to see whether there is an effect of a given factor or an interaction between two factors on a continuous DV. And we have looked at this through decomposition matrices and through the <strong><code>ezANOVA</code></strong> package. We also briefly mentioned how this approach can be extrapolated into designs with more than two-factors such as three-way ANOVAs (three factors) and larger, but also into within-subject designs where every participant sees every stimuli, and mixed-designs where you have at least one between and one within factor. We will look in-depth at these different types of designs next year.</p>
<p>Today, however, we want to start looking at predicting relationships from continuous variables through regression. You will already be familiar with many of the terms here from your lecture series.In addition, by looking at a practical example (relating to voice research) in the lab, and by reading about regression in Miller and Haden (2013) in the PreClass, it should start to become more concrete for you. Regression is still part of the GLM and eventually the goal will be to show you how to analyse designs that has both categorical and continuous variables as much of real data is made up like that. But for now we will just look at simple and multitple linear regression to make you more comfortable with carrying out and interpreting these analyses.</p>
<p>The goals of this chapter are to:</p>
<ol style="list-style-type: decimal">
<li>Introduce the concepts that underpin linear regression.</li>
<li>Demonstrate and practice carrying out and interpreting regression analysis with one or more predictor variables.</li>
<li>Demonstrate and practice being able to make predictions based on your regression model.</li>
</ol>

</div>
<div id="preclass-activity-11" class="section level2">
<h2><span class="header-section-number">14.2</span> PreClass Activity</h2>
<p>As in previous chapters, the PreClass activity is to read the following chapter from Miller and Haden (2013). You may also want to try reading Chapter 14 as well on Multiple Regression but really more to add to your understanding of the general goal, as opposed to the underlying computations. Finally, reviewing your lecture on Simple Linear and Multiple Linear Regression will really help your understanding of this lab.</p>
<div id="read-4" class="section level3">
<h3><span class="header-section-number">14.2.1</span> Read</h3>
<p><strong>Chapter</strong></p>
<p>Read Chapter 12 of <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" target = "_blank">Miller and Haden (2013)</a> and try to understand the how the GLM applies to regression. The concept of regression will be familiar to you based on the stats lectures of this semester so some of the terms will just be recapping. Some will be an expansion of your understanding and basing the analysis in terms of the GLM.</p>
<p><strong>Optional</strong></p>
<p>Read Chapter 14 of <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" target = "_blank">Miller and Haden (2013)</a>. This covers Multiple Linear Regression. Again the concepts will be familiar to you from the lecture series and reading this chapter would be to enhance your overall understanding, not necessarily the underlying computations.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span></p>

</div>
</div>
<div id="inclass-activity-12" class="section level2">
<h2><span class="header-section-number">14.3</span> InClass Activity</h2>
<p>You have been reading about regression in Miller and Haden (2013) and have been looking at it in the lectures. Today, to help get a practical understanding of regression, you will be working with real data and using regression to explore the question of whether there is a relationship between voice acoustics and ratings of perceived trustworthiness.</p>
<p><strong>The Voice</strong></p>
<p>The prominent theory of voice production is the <strong>source-filter theory</strong> (Fant, 1960) which suggests that vocalisation is a two step process: air is pushed through the larynx (vocal chords) creating a vibration, i.e. the source, and this is then shaped and moulded into words and utterances as it passes through the neck, mouth and nose, and depending on the shape of those structures at any given time you produce different sounds, i.e. the filter. One common measure of the source is pitch (otherwise called Fundamental Frequency or F0 (F-zero)) (Titze, 1994), which is a measure of the vibration of the vocal chords, in Hertz (Hz); males have on average a lower pitch than females for example. Likewise, one measure of the filter is called formant dispersion (measured again in Hz), and is effectively a measure of the length of someone’s vocal tract (or neck). Height and neck length are suggested to be negatively correlated with formant dispersion, so tall people tend to have smaller formant dispersion. So all in, the sound of your voice is thought to give some indication of what you look like.</p>
<p>More recently, work has focussed on what the sound of your voice suggests about your personality. <a href = "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090779" target = "_blank">McAleer, Todorov and Belin (2014)</a> suggested that vocal acoustics give a perception of your trustworthiness and dominance to others, regardless of whether or not it is accurate. One extension of this is that trust may be driven by malleable aspects of your voice (e.g. your pitch) but not so much by static aspects of your voice (e.g. your formant dispersion). Pitch is considered malleable because you can control the air being pushed through your vocal chords (though you have no conscious control of your vocal chords), whereas dispersion may be controlled by the structure of your throat which is much more rigid due to muscle, bone, and other things that keep your head attached. This idea of certain traits being driven by malleable features and others by static features was previously suggested by <a href = "https://www.pnas.org/content/105/32/11087" target = "_blank">Oosterhof and Todorov (2008)</a> and has been tested with some validation by <a href = "https://link.springer.com/article/10.1007/s10919-015-0214-8" target = "_blank">Rezlescu, Penton, Walsh, Tsujimura, Scott and Banissy (2015)</a>.</p>
<p>So the research question today is: can vocal acoustics, namely pitch and formant dispersion, predict perceived trustworthiness from a person’s voice? We will only look at male voices today, but you have the data for female voices as well should you wish to practice (note that in the field, tendency is to analyse male and female voices separately as they are effectively sexually dimorphic). As such, we hypothesise that <strong>a linear combination of pitch and dispersion will predict perceived vocal trustworthiness in male voices</strong>. This is what we will analyse.</p>
<p><strong>Let’s begin.</strong></p>
<p>First, to run this analysis you will need to download the data from Moodle or <a href="data/14-s02/inclass/ch14-inclass-data.zip">from here</a>. You will see in this folder that there are two datafiles:</p>
<ul>
<li>voice_acoustics.csv - shows the VoiceID, the sex of voice, and the pitch and dispersion values</li>
<li>voice_ratings.csv - shows the VoiceID and the ratings of each voice by 28 participants on a scale of 1 to 9 where 9 was extremely trustworthy and 1 was extremely untrustworthy</li>
</ul>
<p>Have a look at the layout of the data and familiarise yourself with it. The ratings data is rather messy and in a different layout to the acoustics but can you tell what is what?</p>
<ul>
<li>Looking at the layout of the acoustics data it appears to be in <select class='solveme' data-answer='["tidy"]'> <option></option> <option>long</option> <option>wide</option> <option>tidy</option></select></li>
<li>Looking at the layout of the ratings data it appears to be in <select class='solveme' data-answer='["wide"]'> <option></option> <option>long</option> <option>wide</option></select></li>
</ul>
<p>We are going to need to do some data-wrangling before we do any analysis!!!</p>
<div id="Ch14InClassQueT1" class="section level3">
<h3><span class="header-section-number">14.3.1</span> Task 1: Setup</h3>
<p>Open a new script or Rmd (depending on how you like to work) and load in the tidyverse, broom, and the two CSV datasets into tibbles called <code>ratings</code> and <code>acoustics</code>. Probably best if the ratings are in <code>ratings</code> and the acoustics in <code>acoustics</code>.</p>
</div>
<div id="Ch14InClassQueT2" class="section level3">
<h3><span class="header-section-number">14.3.2</span> Task 2: Restructuring the ratings</h3>
<p>Next we need to calculate a mean rating score for each voice. We are analysing the voices and not specifically what each participant rated each voice as (that is for another year) so we need to average across all participants, their ratings for each individual voice and get a mean rating for each voice. You will see in your data that the voices are identified in the VoiceID column.</p>
<p>Recall the difference between <strong>wide</strong> and <strong>long</strong> data. In wide data, each row represents an individual case, with observations for that case in separate columns; in long data, each row represents a single observation, and the observations are grouped together into cases based on the value of a variable (for these data, the <code>VoiceID</code> variable). Before we calculate means, what you need to do is to restructure the ratings data into the appropriate “tidy” format; i.e., so that it looks like the table below.</p>
<table>
<caption>
<span id="tab:ratings-wide">Table 14.1: </span>Gather the data into Tidy format
</caption>
<thead>
<tr>
<th style="text-align:center;">
VoiceID
</th>
<th style="text-align:center;">
participant
</th>
<th style="text-align:center;">
rating
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
P1
</td>
<td style="text-align:center;">
7.0
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
P1
</td>
<td style="text-align:center;">
8.0
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
P1
</td>
<td style="text-align:center;">
7.5
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
P1
</td>
<td style="text-align:center;">
6.0
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
P1
</td>
<td style="text-align:center;">
4.0
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
P1
</td>
<td style="text-align:center;">
5.0
</td>
</tr>
</tbody>
</table>
<ul>
<li>Write code to restructure the ratings data as above and store the resulting table as <code>ratings_tidy</code>. Only the first six rows are shown. In the table above you see the first 6 voices all rated by Participant 1.</li>
</ul>
<div class="solution">
<button>
Hint for Task 2
</button>
<div class="info">
<ul>
<li>
gather(data, new_column_name, new_column_name, first-column:last-column)
</li>
</ul>
</div>
</div>
</div>
<div id="Ch14InClassQueT3" class="section level3">
<h3><span class="header-section-number">14.3.3</span> Task 3: Calculate mean trustworthiness rating for each voice</h3>
<p>Now that you’ve gotten your ratings data into a more tidy format, the next step is to calculate the mean rating (<code>mean_rating</code>) for each voice. Remember that each voice is identified by the <code>VoiceID</code> variable. Store the resulting table in a variable named <code>ratings_mean</code>.</p>
<div class="solution">
<button>
Hint for Task 3
</button>
<div class="info">
<ul>
<li>
a group_by and summarise would do the trick
</li>
<li>
remember if there are any NAs then na.rm = TRUE would help
</li>
</ul>
</div>
</div>
</div>
<div id="Ch14InClassQueT4" class="section level3">
<h3><span class="header-section-number">14.3.4</span> Task 4: Joining the Data together</h3>
<p>Great! We are so hot at wrangling now we are like hot wrangling irons! Ok but, before we get ahead of ourselves, in order to perform the regression analysis we need to combine the data from <code>ratings_mean</code> (the mean ratings) with <code>acoustics</code> (the pitch and dispersion ratings). Also, as we said, we only want to analyse Male voices today.</p>
<ul>
<li>Go ahead and join the two tibbles and filter out the Female voices to keep the Male voices only. Call the resulting tibble <code>joined</code>. The first few rows should look like this:</li>
</ul>
<table>
<caption>
<span id="tab:combine-ex">Table 14.2: </span>Only the Male Voices
</caption>
<thead>
<tr>
<th style="text-align:right;">
VoiceID
</th>
<th style="text-align:right;">
mean_rating
</th>
<th style="text-align:left;">
sex
</th>
<th style="text-align:left;">
measures
</th>
<th style="text-align:right;">
value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.803571
</td>
<td style="text-align:left;">
M
</td>
<td style="text-align:left;">
Pitch
</td>
<td style="text-align:right;">
118.6140
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.803571
</td>
<td style="text-align:left;">
M
</td>
<td style="text-align:left;">
Dispersion
</td>
<td style="text-align:right;">
1061.1148
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
6.517857
</td>
<td style="text-align:left;">
M
</td>
<td style="text-align:left;">
Pitch
</td>
<td style="text-align:right;">
215.2936
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
6.517857
</td>
<td style="text-align:left;">
M
</td>
<td style="text-align:left;">
Dispersion
</td>
<td style="text-align:right;">
1023.9048
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
5.910714
</td>
<td style="text-align:left;">
M
</td>
<td style="text-align:left;">
Pitch
</td>
<td style="text-align:right;">
147.9080
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
5.910714
</td>
<td style="text-align:left;">
M
</td>
<td style="text-align:left;">
Dispersion
</td>
<td style="text-align:right;">
1043.0630
</td>
</tr>
</tbody>
</table>
<div class="solution">
<button>
Hint for Task 4
</button>
<div class="info">
<ul>
<li>
inner_join by the common column in both datasets
</li>
<li>
filter to keep just Male voices
</li>
</ul>
</div>
</div>
</div>
<div id="Ch14InClassQueT5" class="section level3">
<h3><span class="header-section-number">14.3.5</span> Task 5: Scatterplot</h3>
<p>As always, where possible, it is a good idea to visualise your data. Now that we have all of the variables in one place, reproduce the scatterplot shown below and then try to answer the following questions.</p>
<ul>
<li>According to the scatterplot, there appears to be a <select class='solveme' data-answer='["positive relationship"]'> <option></option> <option>negative relationship</option> <option>positive relationship</option></select> between both pitch and trustworthiness and dispersion and trustworthiness though the relationship with <select class='solveme' data-answer='["pitch"]'> <option></option> <option>dispersion</option> <option>pitch</option></select> seems stronger.</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:scatter"></span>
<img src="14-s02-lab14c_files/figure-html/scatter-1.png" alt="Scatterplot showing the relationship between the voice measures of Dispersion (left) and Pitch (right) and Mean Trustworthiness Rating" width="100%" />
<p class="caption">
Figure 14.1: Scatterplot showing the relationship between the voice measures of Dispersion (left) and Pitch (right) and Mean Trustworthiness Rating
</p>
</div>
<div class="solution">
<button>
Hint for Task 5
</button>
<div class="info">
<ul>
<li>
ggplot()
</li>
<li>
geom_smooth(method = “lm”)
</li>
<li>
coord_cartesian or scale_y_continuous
</li>
<li>
facet_wrap(scales = “free”)
</li>
<li>
did you know also that you can control the number of columns and rows in a facet_wrap by adding nrow and ncol?
</li>
</ul>
</div>
</div>
</div>
<div id="Ch14InClassQueT6" class="section level3">
<h3><span class="header-section-number">14.3.6</span> Task 6: Spreading the data</h3>
<p>Ok so we are starting to get an understanding of our data and we want to start thinking about the regression. However, the regression would be easier to work with if Pitch and Dispersion were in separate columns.</p>
<ul>
<li>Create a new tibble where Pitch and Dispersion data have been split into two columns called <code>Pitch</code> and <code>Dispersion</code> respectively.</li>
</ul>
<div class="solution">
<button>
Hint for Task 6
</button>
<div class="info">
<ul>
<li>
spread() needs the data, name of the categorical column to spread, and the name of the data to spread
</li>
</ul>
</div>
</div>
</div>
<div id="Ch14InClassQueT7" class="section level3">
<h3><span class="header-section-number">14.3.7</span> Task 7: The Regressions</h3>
<p>Excellent, we are now in a position to regress away. Oh hang on, we should probably check the correlation between Pitch and Dispersion as remember the issue of <strong>collinearity</strong>. Calculate the correlation between Pitch and Dispersion and fill in this statement.</p>
<ul>
<li>The correlation between Pitch and Dispersion is <select class='solveme' data-answer='["rho = .239"]'> <option></option> <option>rho = .239</option> <option>rho = -.239</option> <option>rho = .186</option> <option>rho = -.186</option></select> which would suggest that we have no issues with collinearity as our two predictors are only slightly correlated and the correlation here is not significant.</li>
</ul>
<p>Ok, let’s do some regression. The <code>lm()</code> function in R is the main function we will use to estimate a <strong>L</strong>inear <strong>M</strong>odel (hence the function name <code>lm</code>). Use the <code>lm()</code> function to run the following three regression models.</p>
<p><strong>Simple Linear Regression</strong></p>
<ul>
<li>Run the simple linear regression of predicting trustworthiness mean ratings from Pitch, and store the model in <code>mod_pitch</code></li>
<li>Run the simple linear regression of predicting trustworthiness mean ratings from Dispersion, and store the model in <code>mod_disp</code></li>
</ul>
<p><strong>Multitple Linear Regression</strong></p>
<ul>
<li>Run the multiple linear regression of predicting trustworthiness mean ratings from Pitch and Dispersion, and store the model in <code>mod_pitchdisp</code></li>
</ul>
<p>Now look at the results of each one in turn, and try to interpret them, using the function <code>summary()</code>, e.g. <code>summary(mod_pitch)</code>.</p>
<div class="solution">
<button>
Hint for Task 7
</button>
<div class="info">
<p>
<strong>Correlations</strong>
</p>
<ul>
<li>
You should probably use a Spearman correlation for the correlation between Pitch and Dispersion because the scales are very different although measured both in (Hz)
</li>
<li>
You may need to refer back to Chapter 10 on correlations to remember how to use <code>cor.test()</code>.
</li>
</ul>
<p>
<strong>Regressions</strong>
</p>
<ul>
<li>
lm(dv ~ iv, data = my_data) for simple linear regression
</li>
<li>
lm(dv ~ iv1 + iv2, data = my_data) for multiple linear regression
</li>
</ul>
</div>
</div>
</div>
<div id="Ch14InClassQueT8" class="section level3">
<h3><span class="header-section-number">14.3.8</span> Task 8: Making interpretations</h3>
<p>Let’s look at the <code>mod_pitch</code> model together.</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb511-1" data-line-number="1"><span class="kw">summary</span>(mod_pitch)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mean_rating ~ Pitch, data = joined_wide)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.52562 -0.30181  0.04361  0.33398  1.20492 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.921932   0.583801   5.005  2.3e-05 ***
## Pitch       0.015607   0.004052   3.852 0.000573 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6279 on 30 degrees of freedom
## Multiple R-squared:  0.3309, Adjusted R-squared:  0.3086 
## F-statistic: 14.83 on 1 and 30 DF,  p-value: 0.0005732</code></pre>
<p>From the output we can see that this model, when relating to the population, would predict approximately 30.8% of the variance in trustworthiness ratings (Adjusted-R^2 = .3086). We could also say that a linear regression model revealed that pitch significantly predicted perceived trustworthiness scores in male voices in that as pitch increased so does perceived trustworthiness (b = .0156, t(30) = 3.852, p &lt; .001). (Remember that these are unstandardised coefficients so the “Estimate” would mean that a one unit change in pitch would result in a .0156 unit change in perceived trust, a rather small change.)</p>
<p>Overall we have a model of small to medium prediction but it is better than no model - or just using mean values as a prediction - as shown by the F-test being significant. Worth also pointing out here that in a simple linear regression the F-test and the t-value for the predictor are the same based on t^2 = F, as seen in Semester 2 Lab 3.</p>
<p>Ok, based on that knowledge, answer the following questions about the two remaining models.</p>
<ul>
<li>The dispersion as a predictor by itself model would explain approximately <select class='solveme' data-answer='["3%"]'> <option></option> <option>3%</option> <option>13%</option> <option>31%</option> <option>33%</option></select></li>
<li>In fact, the dispersion by itself model is <select class='solveme' data-answer='["not significant"]'> <option></option> <option>not significant</option> <option>significant</option></select> and therefor <select class='solveme' data-answer='["no use"]'> <option></option> <option>no use</option> <option>very useful</option></select> as a model</li>
<li>Looking at the multiple linear regression model, the explained variance is <select class='solveme' data-answer='["30.5%"]'> <option></option> <option>3.05%</option> <option>13.5%</option> <option>30.5%</option> <option>33.5%</option></select>and as such explains <select class='solveme' data-answer='["less"]'> <option></option> <option>less</option> <option>more</option></select> variance than the pitch only model.</li>
</ul>
<p>What the above should remind you is that it is not the case that simply putting all the possible predictors into a model will make it a better model. For every predictor you add there is a penalty associated with the Adjusted-R^2 and if the explained variance attributable to the new predictor is not greater than the penalty to overall explained variance then you may actually end up with a worse model despite having more predictors. We will look at model comparison more in the coming months and years but it is always good to keep the rule of parsimony in mind!</p>
</div>
<div id="Ch14InClassQueT9" class="section level3">
<h3><span class="header-section-number">14.3.9</span> Task 9: Making predictions</h3>
<p>Congratulations! You have successfully constructed a linear model relating trustworthiness to pitch and dispersion and you can think about applying this knowledge to other challenges - perhaps go look at female voices? However, one last thing you might want to do that we will quickly show you is how to make a prediction using the <code>predict()</code> function. One way you use this, though see solutions, is:</p>
<pre><code>predict(mod, newdata)</code></pre>
<p>where <code>newdata</code> is a tibble with new observations on X (e.g. <code>pitch</code> or <code>dispersion</code>) for which you want to predict the corresponding Y values (<code>mean_rating</code>).</p>
<ul>
<li><p>Make a tibble with two columns, one called <code>Pitch</code> and one called <code>Dispersion</code> - exactly as spelt in the model. Give <code>Pitch</code> a value of 150 Hz (quite a high voice) and give <code>Dispersion</code> a value of 1100 Hz - somewhere in the middle. Now put that tibble, <code>newdata</code> into the <code>predict()</code> function to run it on the <code>mod_pitchdisp</code></p></li>
<li><p>To one decimal place, what is the predicted trustworthiness rating of a person with 150 Hz Pitch and 1100 Hz Dispersion - <input class='solveme nospaces' size='4' data-answer='["5.3"]'/></p></li>
</ul>
<div class="solution">
<button>
Hint for Task 9
</button>
<div class="info">
<ul>
<li>
tibble(Pitch = Value, Dispersion = Value)
</li>
</ul>
</div>
</div>
<p><br></p>
<p><strong>WAIT!</strong> - Didn’t we just say that the <code>mod_pitchdisp</code> model is not as good as <code>mod_pitch</code>. Yep. We did. But we wanted to show you how to enter different predictors into the <code>predict()</code> function. So whilst this is a good teaching aid, you are 100% correct in thinking that in reality we would be better making predictions with just the <code>mod_pitch</code> model as it explains more variance overall. Well done for spotting that!</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span></p>
<p>Great! Now you know how to make predictions why not try a few more. Choose some pitch values see what you get! Go record your voice. Extract the pitch using something like <a href = "http://www.fon.hum.uva.nl/praat/" target = "_blank">PRAAT</a>. Put it in the <code>predict()</code> function. Get a rating of trustworthiness for your voice. Go run a study that has your voice rated for trustworthiness and see how close the model was. Given the explained variance is not great it probably won’t be that close but you start to see how, in principle, the idea of regression and prediction of relationships works. The greater the explained variance of your predictors, the better your prediction will be for a novel participant/observation/event!</p>
<p>You should now be ready to complete the Homework Assignment for this lab. <strong>The assignment for this Lab is summative and should be submitted through the Moodle Level 2 Assignment Submission Page no later than 1 minute before your next lab.</strong> If you have any questions, please post them on the slack forum under the channel <strong>#level2_2019</strong>. Finally, don’t forget to add any useful information to your Portfolio before you leave it too long and forget.</p>

</div>
</div>
<div id="assignment-13" class="section level2">
<h2><span class="header-section-number">14.4</span> Assignment</h2>
<p>This is a summative assignment. Instructions as to how to access and submit your assignment will be made available during the course.</p>

</div>
<div id="solutions-to-questions-13" class="section level2">
<h2><span class="header-section-number">14.5</span> Solutions to Questions</h2>
<p>Below you will find the solutions to the questions for the Activities in this chapter. Only look at them after giving the questions a good try and speaking to the tutor about any issues.</p>
<div id="inclass-ativities" class="section level3">
<h3><span class="header-section-number">14.5.1</span> InClass Ativities</h3>
<div id="task-1-1" class="section level4">
<h4><span class="header-section-number">14.5.1.1</span> Task 1</h4>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb514-1" data-line-number="1"><span class="kw">library</span>(<span class="st">&quot;broom&quot;</span>)</a>
<a class="sourceLine" id="cb514-2" data-line-number="2"><span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</a>
<a class="sourceLine" id="cb514-3" data-line-number="3"></a>
<a class="sourceLine" id="cb514-4" data-line-number="4">ratings &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;voice_ratings.csv&quot;</span>)</a>
<a class="sourceLine" id="cb514-5" data-line-number="5">acoustics &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;voice_acoustics.csv&quot;</span>)</a></code></pre></div>
<p><a href="regression.html#Ch14InClassQueT1">Return to Task</a></p>
</div>
<div id="task-2" class="section level4">
<h4><span class="header-section-number">14.5.1.2</span> Task 2</h4>
<ul>
<li>We are calling the new tibble <code>ratings_tidy</code>. We did not state what to call it as by now you can make that decision yourself. Just remember that when debugging your analysis paths from now on, the tibble names might not match up so, you may need to do a little bit of backtracking to see where tibbles were created.</li>
</ul>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb515-1" data-line-number="1">ratings_tidy &lt;-<span class="st"> </span><span class="kw">gather</span>(ratings, participant, rating, P1<span class="op">:</span>P28)</a></code></pre></div>
<p><a href="regression.html#Ch14InClassQueT2">Return to Task</a></p>
</div>
</div>
<div id="task-3" class="section level3">
<h3><span class="header-section-number">14.5.2</span> Task 3</h3>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb516-1" data-line-number="1">ratings_mean &lt;-<span class="st"> </span>ratings_tidy <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb516-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(VoiceID) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb516-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_rating =</span> <span class="kw">mean</span>(rating))</a></code></pre></div>
<p><a href="regression.html#Ch14InClassQueT3">Return to Task</a></p>
</div>
<div id="task-4" class="section level3">
<h3><span class="header-section-number">14.5.3</span> Task 4</h3>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb517-1" data-line-number="1">joined &lt;-<span class="st"> </span><span class="kw">inner_join</span>(ratings_mean, acoustics, <span class="st">&quot;VoiceID&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(sex <span class="op">==</span><span class="st"> &quot;M&quot;</span>)</a></code></pre></div>
<p><a href="regression.html#Ch14InClassQueT4">Return to Task</a></p>
</div>
<div id="task-5" class="section level3">
<h3><span class="header-section-number">14.5.4</span> Task 5</h3>
<div class="figure" style="text-align: center"><span id="fig:ch14-t5-scatter-sol"></span>
<img src="14-s02-lab14e_files/figure-html/ch14-t5-scatter-sol-1.png" alt="Scatterplot showing the relationship between the voice measures of Dispersion (left) and Pitch (right) and Mean Trustworthiness Rating" width="100%" />
<p class="caption">
Figure 14.2: Scatterplot showing the relationship between the voice measures of Dispersion (left) and Pitch (right) and Mean Trustworthiness Rating
</p>
</div>
<p><a href="regression.html#Ch14InClassQueT5">Return to Task</a></p>
</div>
<div id="task-6" class="section level3">
<h3><span class="header-section-number">14.5.5</span> Task 6</h3>
<ul>
<li><code>spread()</code> often catches people out. It is a bit like the reverse of <code>gather()</code></li>
<li>It takes in the data and you tell it which values you want spread and by which column - though in the order of data, column, value. Makes sense huh!</li>
</ul>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb518-1" data-line-number="1">joined_wide &lt;-<span class="st"> </span>joined <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">spread</span>(measures, value)</a></code></pre></div>
<p><a href="regression.html#Ch14InClassQueT6">Return to Task</a></p>
</div>
<div id="task-7" class="section level3">
<h3><span class="header-section-number">14.5.6</span> Task 7</h3>
<p><strong>Simple Linear Regression - Pitch</strong></p>
<p>The pitch model would be written as such:</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb519-1" data-line-number="1">mod_pitch &lt;-<span class="st"> </span><span class="kw">lm</span>(mean_rating <span class="op">~</span><span class="st"> </span>Pitch, joined_wide)</a></code></pre></div>
<p>And give the following output:</p>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb520-1" data-line-number="1"><span class="kw">summary</span>(mod_pitch)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mean_rating ~ Pitch, data = joined_wide)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.52562 -0.30181  0.04361  0.33398  1.20492 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.921932   0.583801   5.005  2.3e-05 ***
## Pitch       0.015607   0.004052   3.852 0.000573 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6279 on 30 degrees of freedom
## Multiple R-squared:  0.3309, Adjusted R-squared:  0.3086 
## F-statistic: 14.83 on 1 and 30 DF,  p-value: 0.0005732</code></pre>
<p><strong>Simple Linear Regression - Dispersion</strong></p>
<p>The Dispersion model would be written as such:</p>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb522-1" data-line-number="1">mod_disp &lt;-<span class="st"> </span><span class="kw">lm</span>(mean_rating <span class="op">~</span><span class="st"> </span>Dispersion, joined_wide)</a></code></pre></div>
<p>And give the following output:</p>
<div class="sourceCode" id="cb523"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb523-1" data-line-number="1"><span class="kw">summary</span>(mod_disp)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mean_rating ~ Dispersion, data = joined_wide)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.87532 -0.41300 -0.02435  0.29850  1.52664 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 2.345300   1.982971   1.183    0.246
## Dispersion  0.002584   0.001836   1.407    0.170
## 
## Residual standard error: 0.7434 on 30 degrees of freedom
## Multiple R-squared:  0.06191,    Adjusted R-squared:  0.03064 
## F-statistic:  1.98 on 1 and 30 DF,  p-value: 0.1697</code></pre>
<p><strong>Multiple Linear Regression - Pitch + Dispersion</strong></p>
<p>The model with both Pitch and Dispersion as predictors would be written as such:</p>
<div class="sourceCode" id="cb525"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb525-1" data-line-number="1">mod_pitchdisp &lt;-<span class="st"> </span><span class="kw">lm</span>(mean_rating <span class="op">~</span><span class="st"> </span>Pitch <span class="op">+</span><span class="st"> </span>Dispersion, joined_wide)</a></code></pre></div>
<p>And give the following output:</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb526-1" data-line-number="1"><span class="kw">summary</span>(mod_pitchdisp)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mean_rating ~ Pitch + Dispersion, data = joined_wide)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.54962 -0.36428  0.04033  0.36327  1.18915 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) 1.444290   1.697362   0.851  0.40179   
## Pitch       0.014855   0.004142   3.586  0.00121 **
## Dispersion  0.001470   0.001585   0.927  0.36137   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6293 on 29 degrees of freedom
## Multiple R-squared:  0.3501, Adjusted R-squared:  0.3053 
## F-statistic: 7.813 on 2 and 29 DF,  p-value: 0.001931</code></pre>
<p><a href="regression.html#Ch14InClassQueT7">Return to Task</a></p>
</div>
<div id="task-8" class="section level3">
<h3><span class="header-section-number">14.5.7</span> Task 8</h3>
<p><strong>A brief explanation:</strong></p>
<p>From the models you can see that the Dispersion only model is not actually significant (F(1,30) = 1.98, p = .17) meaning that it is not actually any use as a model. This is backed up by it only explaining 3% of the variance. Looking at the multiple linear regression model which contains both pitch and dispersion we can see that it is a useful model ((F(2,29) - 7.81, P = .002) explaining 30.5% of the variance). However only pitch is a significant predictor in this model and actually the multiple regression model has smaller predictive ability than the pitch alone model. There is an arguement to be made that the pitch alone model is the best model in the current analysis.</p>
<p><a href="regression.html#Ch14InClassQueT8">Return to Task</a></p>
<div id="task-9" class="section level4">
<h4><span class="header-section-number">14.5.7.1</span> Task 9</h4>
<p><strong>Solution Version 1</strong></p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb528-1" data-line-number="1">newdata &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">Pitch =</span> <span class="dv">150</span>, <span class="dt">Dispersion =</span> <span class="dv">1100</span>)</a></code></pre></div>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb529-1" data-line-number="1"><span class="kw">predict</span>(mod_pitchdisp, newdata)</a></code></pre></div>
<pre><code>##        1 
## 5.289819</code></pre>
<p><strong>Solution Version 2</strong></p>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb531-1" data-line-number="1"><span class="kw">predict</span>(mod_pitchdisp, <span class="kw">tibble</span>(<span class="dt">Pitch =</span> <span class="dv">150</span>, </a>
<a class="sourceLine" id="cb531-2" data-line-number="2">                              <span class="dt">Dispersion =</span> <span class="dv">1100</span>))</a></code></pre></div>
<pre><code>##        1 
## 5.289819</code></pre>
<p><strong>Solution Version 3</strong></p>
<ul>
<li>And if you want to bring it out as a single value, say for a write-up, you could do the following</li>
<li>This does pop out a warning about a <code>deprecated</code> function meaning that this won’t work in future updates but for now it is ok to use.</li>
</ul>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb533-1" data-line-number="1"><span class="kw">predict</span>(mod_pitchdisp, <span class="kw">tibble</span>(<span class="dt">Pitch =</span> <span class="dv">150</span>, </a>
<a class="sourceLine" id="cb533-2" data-line-number="2">                              <span class="dt">Dispersion =</span> <span class="dv">1100</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## Warning: &#39;tidy.numeric&#39; is deprecated.
## See help(&quot;Deprecated&quot;)</code></pre>
<pre><code>## [1] 5.3</code></pre>
<p><a href="regression.html#Ch14InClassQueT9">Return to Task</a></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--purple);">Chapter Complete!</span></p>

</div>
</div>
</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="continuing-the-glm-two-factor-designs.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="combining-anova-and-regression-e-g-ancovas.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
